# Auto-generated from responses_api.py
# Model: Conversation2

# generated by datamodel-codegen:
#   filename:  filtered_openapi.yaml
#   timestamp: 2025-10-18T15:02:20+00:00


from pydantic import BaseModel, Field


class Conversation2(BaseModel):
    id: str = Field(..., description="The unique ID of the conversation.")
