# Auto-generated from responses_api.py
# Model: Type57

# generated by datamodel-codegen:
#   filename:  filtered_openapi.yaml
#   timestamp: 2025-10-18T15:02:20+00:00


from enum import Enum


class Type57(Enum):
    response_audio_done = "response.audio.done"
