from playwright_stealth_plugin.python import async_api, sync_api

# import typing
# script_folder = ...
# script_names: typing.List[str] = ...
# browser_options: typing.Dict[str, typing.Any] = ...
# context_options: typing.Dict[str, typing.Any] = ...

__all__ = ["async_api", "sync_api"]
