# Copyright 2025 Cegal AS
# All rights reserved.
# Unauthorized copying of this file, via any medium is strictly prohibited.



from enum import Enum

class WellKnownObjectDescription(str, Enum):
    Borehole = "borehole"
    BoreholeCollection = "borehole collection"
    CheckShot = "checkshot"
    CompletionsCasingString = "casing string"
    CompletionsPerforation = "perforation"
    CompletionsSqueeze = "squeeze"
    CompletionsPlugback = "plugback"
    FaultInterpretation = "fault interpretation"
    Folder = "folder"
    Grid = "grid"
    GridProperty = "grid property"
    GridDiscreteProperty = "grid discrete property"
    HorizonInterpretation = "horizon interpretation"
    HorizonInterpretation3D = "horizon interpretation 3d"
    HorizonProperty3D = "horizon property 3d"
    InterpretationCollection = "interpretation collection"
    MarkerAttribute = "marker attribute"
    MarkerAttributeDiscrete = "discrete marker attribute"
    MarkerCollection = "marker collection"
    MarkerStratigraphy = "marker stratigraphy"
    MarkerStratigraphyHorizon = "stratigraphy horizon"
    MarkerStratigraphyZone = "stratigraphy zone"
    ObservedData = "observed data"
    ObservedDataSet = "observed data set"
    ObservedDataSetGlobal = "global observed data set"
    PointSet = "pointset"
    PolylineSet = "polylineset"
    PolylineAttribute = "polyline attribute"
    PolylineAttributeDiscrete = "discrete polyline attribute"
    PropertyCollection = "property collection"
    PropertyFolder = "property folder"
    ReferenceVariable = "referencevariable"
    RootInput = "root input"
    SavedSearch = "saved search"
    Segment = "segment"
    SeismicLine = "seismic 2d"
    SeismicCube = "seismic cube"
    Surface = "surface"
    SurfaceCollection = "surface collection"
    SurfaceProperty = "surface property"
    SurfaceDiscreteProperty = "surface discrete property"
    Template = "template"
    TemplateDiscrete = "discrete template"
    Wavelet = "wavelet"
    WellAttribute = "well attribute"
    WellAttributeDiscrete = "discrete well attribute"
    WellLog = "well log"
    WellLogDiscrete = "discrete well log"
    WellLogFolderGlobal = "global well log folder"
    WellLogGlobal = "global well log"
    WellLogGlobalDiscrete = "global discrete well log"
    WellSurvey = "well survey"
    WellSurveyDxDyTVD = "dxdytvd well survey"
    WellSurveyExplicit = "explicit well survey"
    WellSurveyMdInclAzim = "mdinclazim well survey"
    WellSurveyXYTVD = "xytvd well survey"
    WellSurveyXYZ = "xyz well survey"
    Workflow = "workflow"
    Zone = "zone"

    def find_string(self) -> str:
        """Returns the well known find string for this object type."""
        if "property" in self.value:
            return f"find {str(self.value).replace('property', 'properties')}"
        return f"find {self.value}s"