# Generated by Django 4.2.16 on 2024-12-08 23:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minidebconf", "0010_registration_check_in_registration_check_out"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=24,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        inverse_match=True, regex="[^0-9() +-]"
                    )
                ],
                verbose_name="Phone number",
            ),
        ),
    ]
