from typing import Protocol, Optional, Sequence
from baltra_sdk.domain.models.company_screening import CompanyScreening

class CompanyScreeningRepository(Protocol):
    def create(self, entity: CompanyScreening) -> CompanyScreening: ...
    def get(self, company_id: int) -> Optional[CompanyScreening]: ...
    def list(self, limit: int = 100, offset: int = 0) -> Sequence[CompanyScreening]: ...
