from typing import Protocol, List, Optional
from baltra_sdk.domain.models.role import Role

class RoleRepository(Protocol):
    def create(self, entity: Role) -> Role: ...
    def bulk_create(self, entities: List[Role]) -> List[Role]: ...
    def get(self, role_id: int) -> Optional[Role]: ...
