from typing import Any

class PreprocessingOptions:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class ConversionOptions:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class InlineImageConfig:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class ConversionOptionsHandle:
    def __init__(self, options: ConversionOptions | None = None) -> None: ...

def convert(html: str, options: ConversionOptions | None = None) -> str: ...
def convert_with_inline_images(
    html: str,
    options: ConversionOptions | None = None,
    image_config: InlineImageConfig | None = None,
) -> tuple[str, list[Any], list[Any]]: ...
def create_options_handle(options: ConversionOptions | None = None) -> ConversionOptionsHandle: ...
def convert_with_options_handle(html: str, handle: ConversionOptionsHandle) -> str: ...
