"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from kombo_python.types import BaseModel
from kombo_python.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, TypedDict


class PostConnectCreateLinkPositiveResponseDataTypedDict(TypedDict):
    link: str


class PostConnectCreateLinkPositiveResponseData(BaseModel):
    link: str


class PostConnectCreateLinkPositiveResponseTypedDict(TypedDict):
    data: PostConnectCreateLinkPositiveResponseDataTypedDict
    status: Literal["success"]


class PostConnectCreateLinkPositiveResponse(BaseModel):
    data: PostConnectCreateLinkPositiveResponseData

    STATUS: Annotated[
        Annotated[Literal["success"], AfterValidator(validate_const("success"))],
        pydantic.Field(alias="status"),
    ] = "success"
