import logging
from _typeshed import Incomplete
from pathlib import Path
from rich.console import Console

LogOutputMode: Incomplete

class Logger:
    DEBUG: Incomplete
    INFO: Incomplete
    WARNING: Incomplete
    ERROR: Incomplete
    CRITICAL: Incomplete
    def __new__(cls, log_dir: str | Path = './logs', filename_prefix: str = '', level_console: int = ..., level_file: int = ..., *args, **kwargs): ...
    def get_logger(self) -> logging.Logger: ...
    def get_console(self) -> Console: ...
    def get_log_file_path(self) -> Path: ...
    def debug(self, *messages, output: LogOutputMode = 'both', sep: str = ' ', **kwargs): ...
    def info(self, *messages, output: LogOutputMode = 'both', sep: str = ' ', **kwargs): ...
    def warning(self, *messages, output: LogOutputMode = 'both', sep: str = ' ', **kwargs): ...
    def error(self, *messages, output: LogOutputMode = 'both', sep: str = ' ', **kwargs): ...
    def critical(self, *messages, output: LogOutputMode = 'both', sep: str = ' ', **kwargs): ...
    def exception(self, *messages, output: LogOutputMode = 'both', sep: str = ' ', exc_info: bool = True, **kwargs): ...
