
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-11-11T16:36:53+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e1bc8af0eb192c10ae747b96da003224b5991f8a",
 "version": "1.2.0a2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
