import playwright.sync_api

# import typing
# browser_options = ...
# context_options = ...
# original_launch: typing.Callable[..., playwright.sync_api.Browser]
# original_new_context: typing.Callable[..., playwright.sync_api.BrowserContext]
# original_launch_persistent_context: typing.Callable[..., playwright.sync_api.BrowserContext]

# def plugin_code(context: playwright.sync_api.BrowserContext) -> None: ...
# def custom_launch(self: playwright.sync_api.BrowserType, *args: typing.Any, **kwargs: typing.Any) -> playwright.sync_api.Browser: ...
# def custom_new_context(self: playwright.sync_api.Browser, *args: typing.Any, **kwargs: typing.Any) -> playwright.sync_api.BrowserContext: ...
# def custom_launch_persistent_context(self: playwright.sync_api.BrowserType, *args: typing.Any, **kwargs: typing.Any) -> playwright.sync_api.BrowserContext: ...
def apply(playwright: playwright.sync_api.Playwright) -> None: ...

__all__ = ["apply"]
