from setuptools import find_packages, setup

setup(
    name="yarik-django-airflow-api-manager",
    version="2.0.17.1",
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        "asgiref<=3.10.0",
        "Django<=5.2.8",
        "greenlet<=3.2.4",
        "psycopg2-binary<=2.9.11",
        "pydantic<=2.12.4",
        "pydantic_core<=2.41.5",
        "pyparsing<=3.2.5",
        "six<=1.17.0",
        "SQLAlchemy<=2.0.44",
        "sqlparse<=0.5.3",
        "typing_extensions<=4.15.0",
        "requests<=2.32.5",
        "PyJWT<=2.10.1",
        "cryptography<=46.0.3",
    ],
    classifiers=[
        "Environment :: Web Environment",
        "Framework :: Django",
        "Framework :: Django :: 5.2",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: BSD License",
        "Operating System :: OS Independent",
        "Programming Language :: Python",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3 :: Only",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Programming Language :: Python :: 3.13",
        "Topic :: Internet :: WWW/HTTP",
        "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
    ],
)
