# Generated by Django 4.2.21 on 2025-06-05 14:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import grimoirelab.core.models
import grimoirelab_toolkit.datetime


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0002_ecosystem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', grimoirelab.core.models.CreationDateTimeField(default=grimoirelab_toolkit.datetime.datetime_utcnow, editable=False)),
                ('last_modified', grimoirelab.core.models.LastModificationDateTimeField(default=grimoirelab_toolkit.datetime.datetime_utcnow, editable=False)),
                ('name', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator('^[a-z]+(?:-[a-z0-9]+)*$', 'Field may only contain alphanumeric characters or hyphens. It may only start with a letter and cannot end with a hyphen.', 'invalid')])),
                ('title', models.CharField(max_length=128, null=True)),
                ('parent_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='subprojects', to='datasources.project')),
                ('ecosystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasources.ecosystem')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'ecosystem')},
            },
        ),
    ]
