"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import importlib.metadata

__title__: str = "glean"
__version__: str = "0.11.14"
__openapi_doc_version__: str = "0.9.0"
__gen_version__: str = "2.743.2"
__user_agent__: str = "speakeasy-sdk/python 0.11.14 2.743.2 0.9.0 glean"

try:
    if __package__ is not None:
        __version__ = importlib.metadata.version(__package__)
except importlib.metadata.PackageNotFoundError:
    pass
