# (generated with --quick)

import lithi.core.logger
import lithi.interface.target
from typing import Callable, Optional, TypeVar

BaseTarget: type[lithi.interface.target.BaseTarget]
CoreRegister: type[lithi.interface.target.CoreRegister]
MemoryArea: type[lithi.interface.target.MemoryArea]
logger: lithi.core.logger._GlobalLoggerProxy

_T = TypeVar('_T', bound=lithi.interface.target.BaseTarget)

class SimulationTarget(lithi.interface.target.BaseTarget):
    __doc__: str
    _core_registers: list[lithi.interface.target.CoreRegister]
    _is_connected: bool
    _is_stopped: bool
    def __del__(self) -> None: ...
    def __init__(self) -> None: ...
    def __str__(self) -> str: ...
    def _read_coreregister(self, _: lithi.interface.target.CoreRegister) -> int: ...
    def _read_memoryarea(self, memory: lithi.interface.target.MemoryArea) -> list[int]: ...
    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def get_core_registers(self) -> list[lithi.interface.target.CoreRegister]: ...
    def is_connected(self) -> bool: ...
    def is_stopped(self) -> bool: ...
    def run(self) -> None: ...
    def stop(self) -> None: ...

def register_target(name: str, config_cls: Optional[type] = ...) -> Callable[[type[_T]], type[_T]]: ...
