# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agentic_mesh_protocol/module_registry/v1/metadata.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'agentic_mesh_protocol/module_registry/v1/metadata.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7agentic_mesh_protocol/module_registry/v1/metadata.proto\x12(agentic_mesh_protocol.module_registry.v1\x1a\x1b\x62uf/validate/validate.proto\"#\n\x03Tag\x12\x1c\n\x03tag\x18\x01 \x01(\tB\n\xbaH\x07r\x02\x10\x01\xc8\x01\x01R\x03tag\"\xb0\x01\n\x08Metadata\x12\x1e\n\x04name\x18\x01 \x01(\tB\n\xbaH\x07r\x02\x10\x01\xc8\x01\x01R\x04name\x12\x41\n\x04tags\x18\x02 \x03(\x0b\x32-.agentic_mesh_protocol.module_registry.v1.TagR\x04tags\x12\x31\n\x0b\x64\x65scription\x18\x03 \x01(\tB\n\xbaH\x07r\x02\x10\x01\xc8\x01\x01H\x00R\x0b\x64\x65scription\x88\x01\x01\x42\x0e\n\x0c_descriptionB\xf3\x01\n,com.agentic_mesh_protocol.module_registry.v1B\rMetadataProtoP\x01\xa2\x02\x03\x41MX\xaa\x02%AgenticMeshProtocol.ModuleRegistry.V1\xca\x02%AgenticMeshProtocol\\ModuleRegistry\\V1\xe2\x02\x31\x41genticMeshProtocol\\ModuleRegistry\\V1\\GPBMetadata\xea\x02\'AgenticMeshProtocol::ModuleRegistry::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agentic_mesh_protocol.module_registry.v1.metadata_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n,com.agentic_mesh_protocol.module_registry.v1B\rMetadataProtoP\001\242\002\003AMX\252\002%AgenticMeshProtocol.ModuleRegistry.V1\312\002%AgenticMeshProtocol\\ModuleRegistry\\V1\342\0021AgenticMeshProtocol\\ModuleRegistry\\V1\\GPBMetadata\352\002\'AgenticMeshProtocol::ModuleRegistry::V1'
  _globals['_TAG'].fields_by_name['tag']._loaded_options = None
  _globals['_TAG'].fields_by_name['tag']._serialized_options = b'\272H\007r\002\020\001\310\001\001'
  _globals['_METADATA'].fields_by_name['name']._loaded_options = None
  _globals['_METADATA'].fields_by_name['name']._serialized_options = b'\272H\007r\002\020\001\310\001\001'
  _globals['_METADATA'].fields_by_name['description']._loaded_options = None
  _globals['_METADATA'].fields_by_name['description']._serialized_options = b'\272H\007r\002\020\001\310\001\001'
  _globals['_TAG']._serialized_start=130
  _globals['_TAG']._serialized_end=165
  _globals['_METADATA']._serialized_start=168
  _globals['_METADATA']._serialized_end=344
# @@protoc_insertion_point(module_scope)
