# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.context import Context
from ..types.create_task_response import CreateTaskResponse
from ..types.list_tasks_response import ListTasksResponse
from ..types.message import Message
from .raw_client import AsyncRawControllerApiClient, RawControllerApiClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ControllerApiClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawControllerApiClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawControllerApiClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawControllerApiClient
        """
        return self._raw_client

    def list_user_tasks(
        self,
        *,
        user_id: str,
        page: typing.Optional[int] = None,
        size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListTasksResponse:
        """
        Parameters
        ----------
        user_id : str

        page : typing.Optional[int]

        size : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListTasksResponse
            Successful Response

        Examples
        --------
        from aui import ApolloClient

        client = ApolloClient(
            network_api_key="YOUR_NETWORK_API_KEY",
        )
        client.controller_api.list_user_tasks(
            user_id="user_id",
            page=1,
            size=1,
        )
        """
        _response = self._raw_client.list_user_tasks(
            user_id=user_id, page=page, size=size, request_options=request_options
        )
        return _response.data

    def create_task(
        self, *, user_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> CreateTaskResponse:
        """
        Parameters
        ----------
        user_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateTaskResponse
            Successful Response

        Examples
        --------
        from aui import ApolloClient

        client = ApolloClient(
            network_api_key="YOUR_NETWORK_API_KEY",
        )
        client.controller_api.create_task(
            user_id="user_id",
        )
        """
        _response = self._raw_client.create_task(user_id=user_id, request_options=request_options)
        return _response.data

    def get_task_messages(
        self, task_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[Message]:
        """
        Parameters
        ----------
        task_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[Message]
            Successful Response

        Examples
        --------
        from aui import ApolloClient

        client = ApolloClient(
            network_api_key="YOUR_NETWORK_API_KEY",
        )
        client.controller_api.get_task_messages(
            task_id="task_id",
        )
        """
        _response = self._raw_client.get_task_messages(task_id, request_options=request_options)
        return _response.data

    def send_message(
        self,
        *,
        task_id: str,
        text: str,
        is_external_api: typing.Optional[bool] = None,
        context: typing.Optional[Context] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Message:
        """
        Parameters
        ----------
        task_id : str

        text : str

        is_external_api : typing.Optional[bool]

        context : typing.Optional[Context]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Message
            Successful Response

        Examples
        --------
        from aui import ApolloClient

        client = ApolloClient(
            network_api_key="YOUR_NETWORK_API_KEY",
        )
        client.controller_api.send_message(
            is_external_api=True,
            task_id="task_id",
            text="text",
        )
        """
        _response = self._raw_client.send_message(
            task_id=task_id,
            text=text,
            is_external_api=is_external_api,
            context=context,
            request_options=request_options,
        )
        return _response.data


class AsyncControllerApiClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawControllerApiClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawControllerApiClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawControllerApiClient
        """
        return self._raw_client

    async def list_user_tasks(
        self,
        *,
        user_id: str,
        page: typing.Optional[int] = None,
        size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListTasksResponse:
        """
        Parameters
        ----------
        user_id : str

        page : typing.Optional[int]

        size : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListTasksResponse
            Successful Response

        Examples
        --------
        import asyncio

        from aui import AsyncApolloClient

        client = AsyncApolloClient(
            network_api_key="YOUR_NETWORK_API_KEY",
        )


        async def main() -> None:
            await client.controller_api.list_user_tasks(
                user_id="user_id",
                page=1,
                size=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_user_tasks(
            user_id=user_id, page=page, size=size, request_options=request_options
        )
        return _response.data

    async def create_task(
        self, *, user_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> CreateTaskResponse:
        """
        Parameters
        ----------
        user_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateTaskResponse
            Successful Response

        Examples
        --------
        import asyncio

        from aui import AsyncApolloClient

        client = AsyncApolloClient(
            network_api_key="YOUR_NETWORK_API_KEY",
        )


        async def main() -> None:
            await client.controller_api.create_task(
                user_id="user_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_task(user_id=user_id, request_options=request_options)
        return _response.data

    async def get_task_messages(
        self, task_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[Message]:
        """
        Parameters
        ----------
        task_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[Message]
            Successful Response

        Examples
        --------
        import asyncio

        from aui import AsyncApolloClient

        client = AsyncApolloClient(
            network_api_key="YOUR_NETWORK_API_KEY",
        )


        async def main() -> None:
            await client.controller_api.get_task_messages(
                task_id="task_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_task_messages(task_id, request_options=request_options)
        return _response.data

    async def send_message(
        self,
        *,
        task_id: str,
        text: str,
        is_external_api: typing.Optional[bool] = None,
        context: typing.Optional[Context] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Message:
        """
        Parameters
        ----------
        task_id : str

        text : str

        is_external_api : typing.Optional[bool]

        context : typing.Optional[Context]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Message
            Successful Response

        Examples
        --------
        import asyncio

        from aui import AsyncApolloClient

        client = AsyncApolloClient(
            network_api_key="YOUR_NETWORK_API_KEY",
        )


        async def main() -> None:
            await client.controller_api.send_message(
                is_external_api=True,
                task_id="task_id",
                text="text",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.send_message(
            task_id=task_id,
            text=text,
            is_external_api=is_external_api,
            context=context,
            request_options=request_options,
        )
        return _response.data
