# coding: utf-8

"""
    RankVectors API

    Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Page-Based Plans**: Predictable pricing by number of pages monitored - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage page usage and limits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins. 

    The version of the OpenAPI document: 1.3.1
    Contact: tj@rankvectors.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from rankvectors.models.page_info import PageInfo
from typing import Optional, Set
from typing_extensions import Self

class LinkOpportunity(BaseModel):
    """
    LinkOpportunity
    """ # noqa: E501
    relevance_score: Union[Annotated[float, Field(le=1, strict=True, ge=0)], Annotated[int, Field(le=1, strict=True, ge=0)]] = Field(description="AI-calculated relevance score (0-1)", alias="relevanceScore")
    anchor_text: StrictStr = Field(description="Suggested anchor text", alias="anchorText")
    context: Optional[StrictStr] = Field(default=None, description="Context where the link should be placed")
    source_page: PageInfo = Field(alias="sourcePage")
    target_page: PageInfo = Field(alias="targetPage")
    reasoning: Optional[StrictStr] = Field(default=None, description="AI reasoning for the suggestion")
    __properties: ClassVar[List[str]] = ["relevanceScore", "anchorText", "context", "sourcePage", "targetPage", "reasoning"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LinkOpportunity from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of source_page
        if self.source_page:
            _dict['sourcePage'] = self.source_page.to_dict()
        # override the default output from pydantic by calling `to_dict()` of target_page
        if self.target_page:
            _dict['targetPage'] = self.target_page.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LinkOpportunity from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "relevanceScore": obj.get("relevanceScore"),
            "anchorText": obj.get("anchorText"),
            "context": obj.get("context"),
            "sourcePage": PageInfo.from_dict(obj["sourcePage"]) if obj.get("sourcePage") is not None else None,
            "targetPage": PageInfo.from_dict(obj["targetPage"]) if obj.get("targetPage") is not None else None,
            "reasoning": obj.get("reasoning")
        })
        return _obj


