# coding: utf-8

"""
    Fortanix SDKMS REST API

    This is a set of REST APIs for accessing the Fortanix Self-Defending Key Management System. This includes APIs for managing accounts, and for performing cryptographic and key management operations. 

    OpenAPI spec version: 1.0.0-20200608
    Contact: support@fortanix.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
    
        http://www.apache.org/licenses/LICENSE-2.0
    
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""


from pprint import pformat
from six import iteritems
import re

from .base_enum_object import BaseEnumObject

# NOTE: This class is auto generated by the swagger code generator program.
# Do not edit the class manually.
class BlsVariant(BaseEnumObject):
    """
    The BLS variant. It is a trade-off between signature size, and public key size.

    Enumeration values::

        BlsVariant.SIGNATURES = "small_signatures"
        BlsVariant.PUBLIC_KEYS = "small_public_keys"

    This class doesnt use python standard enumeration since they dont support unknown values. 
    
    This is an object of type BaseEnumObject and provides similar functionality as a String Enumeration::

        Get a standard instance of enum: BlsVariant.FOO or BlsVariant("FOO")
        Get non standard instance of enum: BlsVariant("BAR")
        Enum instance to String value: BlsVariant.FOO.value , BlsVariant.FOO.name (Gives "FOO")
        Equality: BlsVariant.FOO == BlsVariant("FOO") , BlsVariant.FOO != BlsVariant.BAR
        Provides str func:  str(BlsVariant.FOO) == "BlsVariant.FOO"

    Also the class maintains a static dict of values. hence BlsVariant.FOO and BlsVariant("FOO") are really backed by same data. 
    """
    
    """
    Inner class that stores the actual value
    """
    class __BlsVariant(BaseEnumObject):

        def __init__(self, value):
            self.__value = value

        @property
        def value(self):
            return self.__value

        @property
        def name(self):
            return self.__value

        def __str__(self):
            return "BlsVariant." + self.__value

    """
    allowed enum values
    """
    SIGNATURES = __BlsVariant("small_signatures")
    PUBLIC_KEYS = __BlsVariant("small_public_keys")

    """
    dictionary that keeps the enum value mapping for static access
    """
    __VALUES = dict()
    __VALUES["small_signatures"] = SIGNATURES
    __VALUES["small_public_keys"] = PUBLIC_KEYS

    def __init__(self, name):
        if name in BlsVariant.__VALUES:
            self.__instance = BlsVariant.__VALUES[name]
        else:
            new_value = BlsVariant.__BlsVariant(name)
            BlsVariant.__VALUES[name] = new_value
            self.__instance = new_value

    @property
    def value(self):
        return self.__instance.value

    @property
    def name(self):
        return self.__instance.name

    def __str__(self):
        return "BlsVariant." + self.__instance.name

    """ 
    This is to ensure equals work for both static defined values and client defined ones.
    """
    def __eq__(self, other):
        if (isinstance(self, BlsVariant) or isinstance(self, BlsVariant.__BlsVariant)) and \
                (isinstance(other, BlsVariant) or isinstance(other, BlsVariant.__BlsVariant)):
                return self.value == other.value

        return False

    def __ne__(self, other):
        if (isinstance(self, BlsVariant) or isinstance(self, BlsVariant.__BlsVariant)) and \
                (isinstance(other, BlsVariant) or isinstance(other, BlsVariant.__BlsVariant)):
                return self.value != other.value

        return True


