import pygame


FPS = 15

PROG_STATE_MAINMENU = 1
PROG_STATE_LOADMENU = 2
PROG_STATE_OPTIONSMENU = 3
PROG_STATE_GAME = 4
PROG_STATE_PAUSED = 5
PROG_STATE_SAVEMENU = 6
PROG_STATE_PAUSEOPTIONS = 7
PROG_STATE_INVENTORY = 8
PROG_STATE_INVINSPECT = 9
PROG_STATE_DIALOG = 10

GAME_CONTROL_PAUSE_CLICKED = pygame.USEREVENT + 1
GAME_CONTROL_INVENTORY_CLICKED = pygame.USEREVENT + 2
DISCARD_SELECTED_ITEM = pygame.USEREVENT + 3
PAUSE_MENU_RESUME_CLICKED = pygame.USEREVENT + 4
PAUSE_MENU_QUIT_CLICKED = pygame.USEREVENT + 5
SAVE_MENU_GAME_SAVED = pygame.USEREVENT + 6
INVENTORY_MENU_CLOSE_CLICKED = pygame.USEREVENT + 7
INVENTORY_MENU_RESET_PAGE = pygame.USEREVENT + 8
DIALOG_FROM_STR = pygame.USEREVENT + 9
DIALOG_START = pygame.USEREVENT + 10
DIALOG_SHOW = pygame.USEREVENT + 11
DIALOG_REPLY = pygame.USEREVENT + 12
DIALOG_CONTINUE = pygame.USEREVENT + 13
DIALOG_PAUSE_START = pygame.USEREVENT + 14
DIALOG_PAUSE_END = pygame.USEREVENT + 15
DIALOG_TIMEOUT = pygame.USEREVENT + 16
DIALOG_CLEAR_TIMEOUT = pygame.USEREVENT + 17
GOTO_SCENE = pygame.USEREVENT + 18
REFRESH_SCENE = pygame.USEREVENT + 19
SCENE_TRANSITION_START = pygame.USEREVENT + 20
SCENE_TRANSITION_END = pygame.USEREVENT + 21
REFRESH_INVENTORY = pygame.USEREVENT + 22
PLAY_SOUND = pygame.USEREVENT + 23
OPT_UPDATE_ENABLE_MUSIC = pygame.USEREVENT + 24
OPT_UPDATE_ENABLE_SOUND = pygame.USEREVENT + 25
START_ANIMATION = pygame.USEREVENT + 26
ANIMATION_COMPLETE = pygame.USEREVENT + 27
MUSIC_2_COMPLETE = pygame.USEREVENT + 28
UPDATE_PROGRAM_STATE = pygame.USEREVENT + 29
REDO_LAYOUT = pygame.USEREVENT + 30
BLOCK_INPUT_START = pygame.USEREVENT + 31
BLOCK_INPUT_END = pygame.USEREVENT + 32
PAUSE_ACTIONS_START = pygame.USEREVENT + 33
PAUSE_ACTIONS_END = pygame.USEREVENT + 34
END_GAME = pygame.USEREVENT + 35
