# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openobd_protocol/Communication/Messages/Doip.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2openobd_protocol/Communication/Messages/Doip.proto\x12\nopenOBD.v1\"H\n\x0b\x44oipMessage\x12(\n\x07\x63hannel\x18\x01 \x01(\x0b\x32\x17.openOBD.v1.DoipChannel\x12\x0f\n\x07payload\x18\x02 \x01(\t\"V\n\x0b\x44oipChannel\x12\x10\n\x08\x62us_name\x18\x01 \x01(\t\x12\x12\n\ngateway_id\x18\x02 \x01(\r\x12\x11\n\ttester_id\x18\x03 \x01(\r\x12\x0e\n\x06\x65\x63u_id\x18\x04 \x01(\rB/\n+com.jifeline.OpenOBD.Communication.MessagesP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'openobd_protocol.Communication.Messages.Doip_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n+com.jifeline.OpenOBD.Communication.MessagesP\001'
  _globals['_DOIPMESSAGE']._serialized_start=66
  _globals['_DOIPMESSAGE']._serialized_end=138
  _globals['_DOIPCHANNEL']._serialized_start=140
  _globals['_DOIPCHANNEL']._serialized_end=226
# @@protoc_insertion_point(module_scope)
