# generated by datamodel-codegen:
#   filename:  javascript-asset.json
#   timestamp: 2025-11-18T03:35:10+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated

from adcp.types.base import AdCPBaseModel
from pydantic import ConfigDict, Field


class ModuleType(Enum):
    esm = 'esm'
    commonjs = 'commonjs'
    script = 'script'


class JavascriptAsset(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    content: Annotated[str, Field(description='JavaScript content')]
    module_type: Annotated[ModuleType | None, Field(description='JavaScript module type')] = None
