// @generated by protoc-gen-es v2.6.3
// @generated from file ar/v1/authoring_config.proto (package ar.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { FeedbackMessage } from "./feedback_pb";
import type { ActionMessage } from "./action_pb";
import type { HelperMessage } from "./helper_pb";
import type { Property } from "../../common/v1/property_pb";

/**
 * Describes the file ar/v1/authoring_config.proto.
 */
export declare const file_ar_v1_authoring_config: GenFile;

/**
 * @generated from message ar.v1.ConfigNewMessage
 */
export declare type ConfigNewMessage = Message<"ar.v1.ConfigNewMessage"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string description = 2;
   */
  description: string;

  /**
   * Template id is used to pre-populate a configuration. Leave empty for a new fresh start.
   *
   * @generated from field: string template_id = 3;
   */
  templateId: string;
};

/**
 * Describes the message ar.v1.ConfigNewMessage.
 * Use `create(ConfigNewMessageSchema)` to create a new message.
 */
export declare const ConfigNewMessageSchema: GenMessage<ConfigNewMessage>;

/**
 * @generated from message ar.v1.ConfigUpdateMessage
 */
export declare type ConfigUpdateMessage = Message<"ar.v1.ConfigUpdateMessage"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string icon = 3;
   */
  icon: string;

  /**
   * @generated from field: string description = 4;
   */
  description: string;

  /**
   * @generated from field: repeated ar.v1.FeedbackMessage feedback = 5;
   */
  feedback: FeedbackMessage[];

  /**
   * @generated from field: repeated ar.v1.ActionMessage actions = 6;
   */
  actions: ActionMessage[];

  /**
   * @generated from field: repeated ar.v1.HelperMessage helpers = 7;
   */
  helpers: HelperMessage[];

  /**
   * @generated from field: repeated common.v1.Property properties = 8;
   */
  properties: Property[];

  /**
   * Threshold distance in cm when the UI is expected to disable the AR for this marker
   *
   * @generated from field: int64 ar_disappear_distance = 9;
   */
  arDisappearDistance: bigint;
};

/**
 * Describes the message ar.v1.ConfigUpdateMessage.
 * Use `create(ConfigUpdateMessageSchema)` to create a new message.
 */
export declare const ConfigUpdateMessageSchema: GenMessage<ConfigUpdateMessage>;

/**
 * @generated from message ar.v1.ConfigDeleteMessage
 */
export declare type ConfigDeleteMessage = Message<"ar.v1.ConfigDeleteMessage"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message ar.v1.ConfigDeleteMessage.
 * Use `create(ConfigDeleteMessageSchema)` to create a new message.
 */
export declare const ConfigDeleteMessageSchema: GenMessage<ConfigDeleteMessage>;

