# Hardcoded options for fondsweb search. You can regenerate them from the notebook fondsweb_get_options.ipynb

etf_options = {'nur ETFs': '1'}

yields_options = {'ausschüttend': '1', 'thesaurierend': '2', 'alle': '0'}

sort_options = {'PremiumService-Fonds': 'psf',
                'Fondsname': 'fundname',
                'KVG-Name': 'issuername',
                'Performance laufendes Jahr': 'perytd',
                'Performance 1 Jahr': 'per1j',
                'Performance 3 Jahre': 'per3j',
                'Performance 5 Jahre': 'per5j',
                'Performance 10 Jahre': 'per10j',
                'Volatilität 1 Jahr': 'vol1j',
                'Volatilität 3 Jahre': 'vol3j',
                'Volatilität 5 Jahre': 'vol5j',
                'Volatilität 10 Jahre': 'vol10j',
                'Sharpe Ratio 1 Jahr': 'sharpe1j',
                'Sharpe Ratio 3 Jahre': 'sharpe3j',
                'Sharpe Ratio 5 Jahre': 'sharpe5j',
                'FWW FundStars®': 'fundstars',
                'ISS ESG Fund Rating': 'esgrating',
                'SRI': 'sri',
                'Summe laufende Kosten': 'oc'}

focus_options = {
    'afocus': {
        'Aktienfonds': '2-123',
        'Aktienfonds All Cap': '3-4',
        'Aktienfonds Biotechnologie': '5-6',
        'Aktienfonds Finanz-Dienstleistungen': '7-8',
        'Aktienfonds Gesundheit / Pharma': '9-10',
        'Aktienfonds Immobilien': '11-12',
        'Aktienfonds Industrie': '13-14',
        'Aktienfonds Infrastruktur': '15-16',
        'Aktienfonds Kommunikation': '17-18',
        'Aktienfonds Konsum': '19-20',
        'Aktienfonds Large Cap': '21-22',
        'Aktienfonds Mid Cap': '25-26',
        'Aktienfonds Rohstoffe': '35-46',
        'Aktienfonds Rohstoffe Agrar': '36-37',
        'Aktienfonds Rohstoffe Edelmetalle': '38-39',
        'Aktienfonds Rohstoffe Energie': '40-41',
        'Aktienfonds Rohstoffe gemischt': '42-43',
        'Aktienfonds Rohstoffe Industriemetalle': '44-45',
        'Aktienfonds Small & Mid Cap': '47-48',
        'Aktienfonds Small Cap': '49-50',
        'Aktienfonds Technologie': '51-52',
        'Aktienfonds Umwelt / Klima / Neue Energien': '117-118',
        'Aktienfonds Versorger': '119-120',
        'Garantiefonds': '182-233',
        'Garantiefonds Ablaufzeitpunkt (2021-2030)': '189-190',
        'Garantiefonds Ablaufzeitpunkt (2031-2040)': '193-194',
        'Garantiefonds Ablaufzeitpunkt (2041-2050)': '195-196',
        'Garantiefonds Ablaufzeitpunkt (2051-2060)': '197-198',
        'Garantiefonds ohne Ablaufzeitpunkt': '229-230',
        'Geldmarktfonds': '234-243',
        'Geldmarktfonds allgemein': '235-236',
        'Geldmarktfonds gemischt': '237-238',
        'Geldmarktfonds Staatsanleihen': '239-240',
        'Immobilienfonds': '244-245',
        'Mischfonds': '576-617',
        'Mischfonds ausgewogen': '577-578',
        'Mischfonds defensiv': '585-586',
        'Mischfonds dynamisch': '587-588',
        'Mischfonds flexibel': '589-590',
        'Mischfonds Thema': '615-616',
        'Rentenfonds': '618-689',
        'Rentenfonds allgemein': '619-628',
        'Rentenfonds allgemein gemischte Laufzeiten': '620-621',
        'Rentenfonds allgemein kurze Laufzeiten': '622-623',
        'Rentenfonds allgemein lange Laufzeiten': '624-625',
        'Rentenfonds allgemein mittlere Laufzeiten': '626-627',
        'Rentenfonds gemischt': '629-634',
        'Rentenfonds gemischt höherverzinst': '630-631',
        'Rentenfonds gemischt Investment Grade': '632-633',
        'Rentenfonds inflationsgeschützt': '645-646',
        'Rentenfonds Laufzeitfonds': '655-656',
        'Rentenfonds Pfandbriefe': '657-658',
        'Rentenfonds Sonstige': '663-664',
        'Rentenfonds Staatsanleihen': '665-674',
        'Rentenfonds Staatsanleihen gemischte Laufzeiten': '666-667',
        'Rentenfonds Staatsanleihen kurze Laufzeiten': '668-669',
        'Rentenfonds Staatsanleihen lange Laufzeiten': '670-671',
        'Rentenfonds Staatsanleihen mittlere Laufzeiten': '672-673',
        'Rentenfonds Unternehmensanleihen': '675-686',
        'Rentenfonds Unternehmensanleihen höherverzinst': '678-679',
        'Rentenfonds Unternehmensanleihen Investment Grade': '680-681',
        'Rentenfonds Unternehmensanleihen nachrangig': '682-683',
        'Rentenfonds Wandelanleihen': '687-688',
        'Rohstofffonds': '690-711',
        'Rohstofffonds Edelmetalle': '693-702',
        'Rohstofffonds Edelmetalle gemischt': '694-695',
        'Rohstofffonds Edelmetalle Gold': '696-697',
        'Rohstofffonds gemischt': '705-706',
        'Spezialitätenfonds': '714-729',
        'Spezialitätenfonds Asset Backed Securities (ABS)': '715-716',
        'Spezialitätenfonds ELTIF': '717-718',
        'Spezialitätenfonds Insurance Linked Securities (ILS)': '719-720',
        'Spezialitätenfonds Sonstige': '727-728',
        'Strategiefonds': '730-835',
        'Strategiefonds Aktien-Strategie': '731-756',
        'Strategiefonds Aktien-Strategie Equity Active Market Timing': '734-735',
        'Strategiefonds Aktien-Strategie Equity L/S Flexible': '738-739',
        'Strategiefonds Aktien-Strategie Equity L/S Long Bias': '740-741',
        'Strategiefonds Aktien-Strategie Equity L/S Market Neutral': '742-743',
        'Strategiefonds Aktien-Strategie Equity Leverage': '744-745',
        'Strategiefonds Aktien-Strategie Equity Short': '748-749',
        'Strategiefonds Aktien-Strategie Event Driven': '750-751',
        'Strategiefonds Misch-Strategie': '763-768',
        'Strategiefonds Misch-Strategie defensiv': '764-765',
        'Strategiefonds Misch-Strategie dynamisch': '766-767',
        'Strategiefonds Multi-Asset-Strategie': '771-782',
        'Strategiefonds Multi-Asset-Strategie Makro defensiv': '774-775',
        'Strategiefonds Multi-Asset-Strategie Makro dynamisch': '776-777',
        'Strategiefonds Multi-Asset-Strategie systematisch defensiv': '778-779',
        'Strategiefonds Multi-Asset-Strategie systematisch dynamisch': '780-781',
        'Strategiefonds Options-Strategie': '783-802',
        'Strategiefonds Options-Strategie defensiv': '788-789',
        'Strategiefonds Options-Strategie dynamisch': '792-793',
        'Strategiefonds Renten-Strategie': '803-818',
        'Strategiefonds Renten-Strategie Bond L/S': '804-805',
        'Strategiefonds Renten-Strategie Bond Short': '808-809',
        'Strategiefonds Renten-Strategie Credit': '810-811',
        'Strategiefonds Renten-Strategie Multi-Strategy': '814-815',
        'Strategiefonds Rohstoff-Strategie': '819-824',
        'Strategiefonds Rohstoff-Strategie Commodity Long / Short': '820-821',
        'Strategiefonds Volatilitäts-Strategie': '825-832',
        'Strategiefonds Volatilitäts-Strategie Aktien': '826-827',
        'Strategiefonds Währungs-Strategie': '833-834',
        'Zielzeitfonds': '858-869',
        'Zielzeitfonds Ablaufzeitpunkt (2021-2030)': '861-862',
        'Zielzeitfonds Ablaufzeitpunkt (2031-2040)': '863-864',
        'Zielzeitfonds Ablaufzeitpunkt (2041-2050)': '865-866',
        'Zielzeitfonds Ablaufzeitpunkt (2051-2060)': '867-868'},
    'rfocus': {'Afrika': '116',
               'ASEAN': '119',
               'Asien (ex Japan)': '136',
               'Asien/Pazifik': '138',
               'Asien/Pazifik (ex Japan)': '137',
               'Australien': '6',
               'Brasilien': '12',
               'BRIC': '277',
               'China': '17',
               'Deutschland': '1',
               'Emerging Markets': '113',
               'Euroland': '106',
               'Europa': '123',
               'Europa (ex UK)': '140',
               'Frankreich': '24',
               'Großbritannien': '26',
               'Großchina': '120',
               'Indien': '29',
               'Italien': '36',
               'Japan': '38',
               'Lateinamerika': '118',
               'MENA': '275',
               'Nordamerika': '112',
               'Österreich': '71',
               'Osteuropa': '109',
               'Osteuropa (ex Russland)': '274',
               'Russland': '80',
               'Schweiz': '84',
               'Skandinavien': '108',
               'Südkorea': '93',
               'Taiwan': '94',
               'Türkei': '98',
               'USA': '102',
               'Welt': '122'},
    'cfocus': {'Britisches Pfund Sterling': '5',
               'Euro': '4',
               'Hart- und Weichwährungen (Europa)': '132',
               'Hart- und Weichwährungen (Welt)': '139',
               'Hartwährungen (Europa)': '133',
               'Hartwährungen (Welt)': '137',
               'Schweizer Franken': '3',
               'US-Dollar': '7',
               'verschiedene (Skandinavien)': '135',
               'Weichwährungen (Welt)': '138'},
    'issuer': {'1741 Fund Management AG': '2256',
               '1741 Fund Services S.A.': '161',
               '1741 Fund Solutions AG': '2078',
               '3 Banken-Generali Investment-Gesellschaft mbH': '4',
               'Aachener Grundvermögen Kapitalverwaltungsgesellschaft mbH': '5',
               'Abalone Asset Management Ltd': '2043',
               'Aberdeen Asset Management Deutschland AG': '70',
               'ABN AMRO Investment Solutions': '2017',
               'abrdn Investments Luxembourg S.A.': '1710',
               'ACATIS Investment Kapitalverwaltungsgesellschaft mbH': '2096',
               'Accuro Fund Solutions AG': '1772',
               'AcomeA SGR S.p.A.': '2267',
               'Aegon Asset Management Europe ICAV': '2104',
               'Aegon Investment Management B.V': '2303',
               'AFFM S.A.': '1577',
               'Ahead Wealth Solutions AG': '1621',
               'Algebris Investments (Ireland) Limited': '1997',
               'AllianceBernstein (Luxembourg) S.à r.l.': '152',
               'Allianz Global Investors GmbH': '76',
               'Allianz Invest Kapitalanlagegesellschaft mbH': '1189',
               'Allspring Global Investments Luxembourg S.A.': '1985',
               'Alma Capital Investment Management': '2067',
               'Alpina Fund Management S.A.': '2198',
               'Altana UCITS Funds plc': '1999',
               'ALTE LEIPZIGER Trust Investment-Gesellschaft mbH': '51',
               'Alter Domus Management Company S.A.': '2308',
               'Altum Management Company (Luxembourg) S.A.': '2231',
               'Ambienta Sgr S.p.A.': '2253',
               'Ampega Investment GmbH': '93',
               'Amundi Asset Management': '1359',
               'Amundi Austria GmbH': '55',
               'Amundi Deutschland GmbH': '147',
               'Amundi Ireland Limited': '1759',
               'Amundi Luxembourg S.A.': '95',
               'Anaxis Asset Management S.A.S.': '1977',
               'Andbank Asset Management Luxembourg': '2264',
               'ANIMA Funds plc': '2036',
               'Architas Multi-Manager Europe Limited': '2091',
               'AS Avaron Asset Management': '2217',
               'Ashmore Investment Management (Ireland) Limited': '2183',
               'Aspect UCITS Funds plc': '1766',
               'Assenagon Asset Management S.A.': '1583',
               'Aviva Investors Luxembourg S.A.': '1176',
               'AXA Funds Management S.A.': '1237',
               'AXA Investment Managers Deutschland GmbH': '52',
               'AXA Investment Managers Paris': '1331',
               'AXXION S.A.': '1194',
               'Azimut Investments S.A.': '2122',
               'Baillie Gifford Investment Management (Europe) Limited': '2141',
               'Bantleon Invest AG': '1501',
               'Baring Fund Managers Limited': '1391',
               'Baring International Fund Managers (Ireland) Limited': '54',
               'Barometer Management (Ireland) Limited': '2048',
               'BayernInvest Kapitalverwaltungsgesellschaft mbH': '1500',
               'BayernInvest Luxembourg S.A.': '57',
               'BCEE ASSET MANAGEMENT S.A.': '1301',
               'BIL Manage Invest S.A.': '2083',
               'BlackRock (Luxembourg) S.A.': '110',
               'BlackRock Asset Management Deutschland AG': '1110',
               'BlackRock Asset Management Ireland Limited': '1887',
               'Blackstone Alternative Investment Funds plc': '2117',
               'Blackstone Europe Fund Management S.à r.l.': '2274',
               'BLACKSTONE SYSTEMATIC CREDIT UMBRELLA FUND PLC': '1961',
               'BLI - Banque de Luxembourg Investments S.A.': '1511',
               'BlueBay Funds Management Company S.A.': '1553',
               'BNP Paribas Asset Management Europe': '1537',
               'BNP Paribas Asset Management Luxembourg': '119',
               'BNP Paribas Real Estate Investment Management Germany GmbH': '102',
               'BNY Mellon Fund Management (Luxembourg) S.A.': '2258',
               'BRANDES INVESTMENT FUNDS PLC': '1472',
               'Bridge Fund Management Limited': '2197',
               'Brookfield Investment Funds (UCITS) p.l.c.': '2118',
               'Brown Advisory Funds plc': '1791',
               'BTG Pactual Europe Management Company S.A.': '1295',
               'C WORLDWIDE FUND MANAGEMENT S.A.': '2056',
               'CACEIS Ireland Limited': '2081',
               'CAIAC Fund Management AG': '1591',
               'Candriam': '1217',
               'Capital International Management Company Sàrl': '1314',
               'CARMIGNAC GESTION': '1358',
               'CARMIGNAC GESTION LUXEMBOURG': '1357',
               'Carne Global Fund Managers (Ireland) Limited': '1843',
               'Carne Global Fund Managers (Luxembourg) S.A.': '2028',
               'Carne Global Fund Managers (Schweiz) AG': '2272',
               'Catella Real Estate AG': '1610',
               'CHOLET DUPONT ASSET MANAGEMENT': '2199',
               'Clartan Associés': '1767',
               'Cohen & Steers UK Limited': '2307',
               'Colchester Global Investors (Dublin) Management Limited': '2255',
               'Comgest Growth plc': '1202',
               'Comgest S.A.': '67',
               'Commerz Real Fund Management S.à r.l.': '2218',
               'Commerz Real Investmentgesellschaft mbH': '68',
               'Conventum Asset Management': '1535',
               'CORUM Butler Asset Management Limited': '2215',
               'CPR Asset Management': '1642',
               'CREDIT MUTUEL ASSET MANAGEMENT': '1756',
               'Credit Suisse Asset Management Immobilien Kapitalanlagegesellschaft mbH': '1310',
               'Creutz & Partners Global Asset Management S.A.': '1158',
               'Crown Alternative UCITS plc': '1717',
               'Danske Invest Management Company S.A.': '1407',
               'DC Developing Markets Strategies p.l.c.': '2137',
               'Degroof Petercam Asset Management SA': '2239',
               'Degroof Petercam Asset Services SA': '2023',
               'Deka Immobilien Investment GmbH': '72',
               'Deka International S.A.': '154',
               'Deka Investment GmbH': '71',
               'Deka Vermögensmanagement GmbH': '58',
               'Dimensional Fund Advisors Ltd.': '1953',
               'Dimensional Ireland Limited': '2306',
               'DJE Investment S.A.': '1266',
               'DNB Asset Management S.A.': '65',
               'DNCA Finance': '1761',
               'DNCA Finance Luxembourg': '1562',
               'Dodge & Cox Worldwide Funds plc': '1948',
               'DWS Grundbesitz GmbH': '73',
               'DWS Investment GmbH': '79',
               'DWS Investment S.A.': '69',
               'Dynasty AM S.A.': '2080',
               'East Capital Asset Management S.A.': '1586',
               'Eastspring Investments (Luxembourg) S.A.': '1951',
               'Edmond de Rothschild Asset Management (France)': '1742',
               'Edmond de Rothschild Asset Management (Luxembourg)': '1681',
               'Eleva Capital S.A.S.': '2130',
               'Ellipsis Asset Management': '2250',
               'Ennismore Fund Management Ltd': '1030',
               'Eric Sturdza Management Company S.A.': '2299',
               'Erste Asset Management GmbH': '1093',
               'ETHENEA Independent Investors S.A.': '1731',
               'Eurizon Capital S.A.': '2058',
               'European Capital Partners (Luxembourg) S.A': '2210',
               'Evli Fund Management Company Ltd': '1878',
               'Exane Asset Management': '2041',
               'Expat Asset Management EAD': '2100',
               'FCG Fonder AB': '2268',
               'Federated Hermes Investment Funds Public Limited Company': '1875',
               'Feri (Luxembourg) S.A.': '1567',
               'Fidante Partners Liquid Strategies ICAV': '2161',
               'FIL Investment Management (Luxembourg) S.A.': '83',
               'Finserve Nordic AB': '2249',
               'First Private Investment Management KAG mbH': '1278',
               'First Sentier Investors (Ireland) Limited': '1690',
               'First Trust Global Portfolios Management Limited': '2060',
               'Flossbach von Storch Invest S.A.': '1828',
               'Fondita Fund Management Company Ltd.': '2148',
               'FORT Global UCITS Funds plc': '2038',
               'Franklin Templeton International Services S.à r.l.': '130',
               'FTC FUTURES FUND SICAV': '1097',
               'Fuchs Asset Management S.A.': '2251',
               'FundLogic Alternatives p.l.c.': '1832',
               'FundPartner Solutions (Europe) S.A.': '1851',
               'FundRock Management Company S.A.': '1669',
               'GAM (Luxembourg) S.A.': '160',
               'GAM Fund Management Limited': '89',
               'GAMAX Management AG': '90',
               'Gateway Fund Services Limited': '2261',
               'Gen II Management Company (Luxembourg) SARL': '2008',
               'Generali Investments Deutschland Kapitalanlagegesellschaft mbH': '1032',
               'Generali Investments Luxembourg S.A.': '1979',
               'Generali Investments Partners S.p.A.': '1867',
               'Global Evolution Manco': '2037',
               'Global Funds Management S.A.': '2172',
               'Goldman Sachs Asset Management B.V.': '1827',
               'Goldman Sachs Asset Management Fund Services Limited': '1939',
               'Groupama Asset Management': '2113',
               'GS&P Kapitalanlagegesellschaft S. A.': '184',
               'Gutenberg Finance SAS': '2065',
               'Gutmann Kapitalanlageaktiengesellschaft m.b.H.': '1179',
               'H2O AM EUROPE': '2257',
               'HAL Fund Services Ireland Limited': '2278',
               'HANetf Management Limited': '2156',
               'HANSAINVEST Hanseatische Investment-GmbH': '100',
               'HANSAINVEST LUX S.A.': '225',
               'Hauck & Aufhäuser Fund Services S.A.': '1010',
               'Hedge Invest International Funds plc': '1972',
               'Helaba Invest Kapitalanlagegesellschaft mbH': '1352',
               'Hermes Fund Managers Ireland Limited': '2266',
               'HSBC Global Asset Management (France)': '1665',
               'HSBC Global Liquidity Funds plc': '1564',
               'HSBC Investment Funds (Luxembourg) S.A.': '1678',
               'HSBC UCITS AdvantEdge plc': '1713',
               'Hugau Gestion': '2209',
               'IFM Independent Fund Management AG': '1332',
               'IFP Investment Management S.A.': '2126',
               'iM Global Partner Asset Management S.A.': '1007',
               'Impax Asset Management Ireland Limited': '1819',
               'ING Solutions Investment Management S.A.': '2072',
               'INKA Internationale Kapitalanlagegesellschaft mbH': '179',
               'IntReal International Real Estate Kapitalanlagegesellschaft mbH': '1773',
               'Invesco Global Asset Management DAC': '1234',
               'Invesco Investment Management Limited': '2088',
               'Invesco Management S.A.': '1233',
               'INVL Asset Management UAB': '2006',
               'IPConcept (Luxemburg) S.A.': '1230',
               'IPConcept (Schweiz) AG': '1954',
               'IQ EQ Fund Management (Ireland) Limited': '2162',
               'IQAM Invest GmbH': '218',
               'IVC UCITS FUNDS plc': '1821',
               'IXI Fund Managers Ltd': '2260',
               'J. Safra Sarasin Fund Management (Luxembourg) S.A.': '125',
               'J.Chahine Capital': '1931',
               'Janus Henderson Investors Europe S.A.': '226',
               'JOHCM Funds (UK) Limited': '1528',
               'JPMorgan Asset Management (Europe) S.à r.l.': '84',
               'Jupiter Asset Management (Europe) Limited': '2152',
               'Jupiter Asset Management International S.A.': '1436',
               'Jyske Invest Fund Management A/S': '1533',
               'Kairos Partners SGR S.p.A.': '2125',
               'KanAm Grund Institutional Kapitalverwaltungsgesellschaft mbH': '1498',
               'KanAm Grund Kapitalverwaltungsgesellschaft mbH': '1239',
               'KBA Consulting Management Limited': '2061',
               'KBC Asset Management NV': '1622',
               'KBC Asset Management S.A.': '1206',
               'Kepler Liquid Strategies ICAV': '2124',
               'KEPLER-FONDS Kapitalanlagegesellschaft mbH': '1087',
               'Kredietrust Luxembourg S.A.': '1659',
               'Kroll (Luxembourg) Management Company S.à r.l.': '2031',
               'LA FINANCIERE DE L ECHIQUIER': '1458',
               'La Francaise Investment Solutions': '2049',
               'La Francaise Systematic Asset Management GmbH': '138',
               'Lazard Asset Management (Deutschland) GmbH': '104',
               'Lazard Freres Gestion SAS': '1974',
               'Lazard Fund Managers (Ireland) Limited': '1703',
               'LB(Swiss) Investment AG': '99',
               'LBBW Asset Management Investmentgesellschaft mbH': '53',
               'Lemanik Asset Management S.A.': '1406',
               'LGIM Managers (Europe) Limited': '2158',
               'LGT Capital Partners (FL) AG': '1513',
               'LGT Capital Partners (Ireland) Limited': '2079',
               'LGT Fund Management Company Ltd.': '2090',
               'Limestone Platform AS': '2301',
               'Liontrust Global Funds plc': '2134',
               'LLB Fund Services Aktiengesellschaft': '1313',
               'LLB Immo Kapitalanlagegesellschaft m.b.H.': '1850',
               'LLB Invest Kapitalanlagegesellschaft m.b.H.': '1190',
               'LLB Swiss Investment AG': '2093',
               'Lombard Odier Funds (Europe) S.A.': '1069',
               'Lord Abbett (Ireland) Ltd.': '1991',
               'LRI Capital Management S.A.': '222',
               'LRI Invest S.A.': '183',
               'Lupus alpha Investment GmbH': '1281',
               'M&G Luxembourg S.A.': '2097',
               'M&G Securities Limited': '1793',
               'Macquarie Investment Management Austria Kapitalanlage AG': '2188',
               'Man Asset Management (Ireland) Limited': '1349',
               'Mandarine Gestion SA': '1640',
               'Mandatum Fund Management S.A.': '2280',
               'MASTERINVEST Kapitalanlage GmbH': '1185',
               'MEAG MUNICH ERGO Kapitalanlagegesellschaft mbH': '97',
               'MEDIOLANUM INTERNATIONAL FUNDS LIMITED': '1272',
               'Mercer Global Investments Management Limited': '2015',
               'Metzler Asset Management GmbH': '111',
               'MFS Investment Management Company (Lux) S.à r.l.': '1047',
               'Mirabaud Asset Management (Europe) S.A.': '1872',
               'Monega Kapitalanlagegesellschaft mbH': '1078',
               'Montanaro European Smaller Companies plc': '1781',
               'Mori Capital Management Limited': '1784',
               'Moventum Asset Management S.A.': '2123',
               'MPMF Fund Management (Ireland) Limited': '2178',
               'MSIM Fund Management (Ireland) Limited': '2143',
               'MultiConcept Fund Management S.A.': '1510',
               'Muzinich & Co. (Ireland) Limited': '1345',
               'MW GESTION SA': '2205',
               'Natixis International Funds (Dublin) I plc': '1724',
               'Natixis Investment Managers International': '2105',
               'Neuberger Berman Europe Limited': '1660',
               'Nikko Asset Management Luxembourg S.A.': '2175',
               'Ninety One Luxembourg S.A.': '1602',
               'Nomura Alternative Investment Management France S.A.S.': '2297',
               'Nomura Asset Management Europe KVG mbH': '106',
               'Nomura NEXT FUNDS Ireland plc': '2074',
               'Noramco Asset Management S.A.': '1022',
               'Nordea Investment Funds S.A.': '87',
               'NS Partners Europe SA': '2110',
               'OAKS Emerging Umbrella Fund plc': '1923',
               'OBAM N.V.': '2181',
               'ODDO BHF Asset Management GmbH': '1395',
               'ODDO BHF Asset Management Lux': '1152',
               'ODDO BHF Asset Management SAS': '1725',
               'Ofi invest Asset Management': '1489',
               'ÖkoWorld Lux S.A.': '115',
               'ONE fund management S.A.': '2232',
               'ONE Funds AG': '2133',
               'Optinova Investmentaktiengesellschaft mit TGV': '1857',
               'Ossiam': '2053',
               'Paladin Asset Management InvAG m.v.K TGV': '1940',
               'Partners Group (Luxembourg) S.A.': '2182',
               'Payden Global Funds plc': '2185',
               'Pensato Capital Funds plc': '1829',
               'Perpetual Investment Services Europe Limited': '2310',
               'PGIM Investments (Ireland) Limited': '2106',
               'Pictet Asset Management (Europe) S.A.': '118',
               'PIMCO Global Advisors (Ireland) Limited': '1739',
               'PineBridge Investments Ireland Limited': '1415',
               'Polar Capital Funds plc': '1365',
               'Polen Capital Investment Funds plc': '2219',
               'Principal Global Investors (Ireland) Limited': '1020',
               'PvB Pernet von Ballmoos AG': '1808',
               'Pzena Investment Management Europe LTD': '2248',
               'Quadoro Investment GmbH': '2138',
               'Quaestio Capital Management Società di Gestione del Risparmio S.p.A.': '2279',
               'Quayside Fund Management Limited': '2108',
               'Quilter Investors Limited': '2120',
               'Quint:Essence Capital S.A.': '63',
               'R.I. Vermögensbetreuung AG': '2025',
               'Raiffeisen Kapitalanlage-Gesellschaft mbH': '1081',
               'RAM Active Investments (Luxembourg) S.A.': '1885',
               'Real I.S. AG Gesellschaft für Immobilien Assetmanagement': '2155',
               'Robeco Institutional Asset Management B.V.': '164',
               'Rothschild & Co Asset Management': '1747',
               'Rothschild & Co Investment Managers': '2154',
               'Russell Investments Ireland Limited': '1561',
               'Salus Alpha SICAV': '2020',
               'SANSO INVESTMENT SOLUTIONS': '1698',
               'Santander Asset Management Luxembourg S.A.': '1852',
               'Savills Fund Management GmbH': '60',
               'Schoellerbank Invest AG': '128',
               'Schroder Investment Management (Europe) S.A.': '127',
               'Schroder Unit Trusts Limited': '1911',
               'SEB Investment Management AB': '1559',
               'Security Kapitalanlage Aktiengesellschaft': '1187',
               'SEI Global Master Fund plc': '1423',
               'Seilern International AG': '1969',
               'SEVEN CAPITAL MANAGEMENT': '1984',
               'SG 29 Haussmann SAS': '2234',
               'SG/Russell Asset Management Limited': '1277',
               'Siemens Fonds Invest GmbH': '204',
               'Société de Gestion Prévoir': '1929',
               'Société Générale Private Wealth Management S.A.': '2233',
               'Sparinvest S.A.': '1405',
               'Sparkasse Oberösterreich Kapitalanlagegesellschaft m.b.H.': '1186',
               'SSgA SPDR ETFs Europe I plc': '1743',
               'SSgA SPDR ETFs Europe II plc': '1897',
               'State Street Fund Services (Ireland) Limited': '1840',
               'State Street Global Advisors Funds Management Limited': '2202',
               'Storebrand Asset Management AS': '2309',
               'Strategic Investment Funds UCITS plc': '1998',
               'Structured Invest S.A.': '1600',
               'Swiss Life Asset Management (France)': '1825',
               'Swiss Life Asset Managers Luxembourg': '206',
               'Swiss Life Kapitalverwaltungsgesellschaft mbH': '2059',
               'Swiss Rock Asset Management AG': '1608',
               'SWISSCANTO ASSET MANAGEMENT INTERNATIONAL S.A.': '1371',
               'Sycomore Asset Management, SA': '1930',
               'Syd Fund Management A/S': '1398',
               'Syquant Capital SAS': '1842',
               'T. Rowe Price (Luxembourg) Management S.à.r.l.': '1213',
               'Threadneedle Investment Services Limited': '2132',
               'Threadneedle Management Luxembourg S.A.': '166',
               'Three Rock Capital Management Limited': '2227',
               'Tikehau Investment Management': '2111',
               'TOBAM': '2204',
               'Triodos Investment Management B.V.': '1783',
               'Turner Funds plc': '1745',
               'TUTMAN LLP': '2009',
               'UBP Asset Management (Europe) S.A.': '209',
               'UBS Asset Management (Deutschland) GmbH': '165',
               'UBS Asset Management (Europe) S.A': '1231',
               'UBS Fund Management (Ireland) Limited': '1541',
               'UBS Fund Management (Luxembourg) S.A.': '1235',
               'UBS Real Estate Kapitalanlagegesellschaft mbH': '1413',
               'UBS Third Party Management Company S.A.': '1656',
               'Union Investment Institutional GmbH': '2066',
               'Union Investment Luxembourg S.A.': '1219',
               'Union Investment Privatfonds GmbH': '135',
               'Union Investment Real Estate GmbH': '75',
               'Universal-Investment GmbH': '137',
               'Universal-Investment Ireland': '1193',
               'Universal-Investment-Luxembourg S.A.': '1611',
               'UTI Goldfinch Funds PLC': '2189',
               'Van Lanschot Kempen Investment Management NV': '1901',
               'VanEck Asset Management B.V.': '2116',
               'VanEck Investments Limited': '1976',
               'Vanguard Group (Ireland) Limited': '1947',
               'Varenne Capital Partners': '1994',
               'Vector Asset Management S.A.': '1955',
               'Veritas Funds plc': '1816',
               'von der Heydt Invest SA': '1517',
               'Vontobel Asset Management S.A.': '139',
               'Vontobel Fonds Services AG': '1325',
               'VP Fund Solutions (Liechtenstein) AG': '1280',
               'VP Fund Solutions (Luxembourg) SA': '1727',
               'WARBURG INVEST KAPITALANLAGEGESELLSCHAFT MBH': '105',
               'Warburg-HIH Invest Real Estate': '1427',
               'Waverton Investment Funds plc': '2029',
               'Waystone Management Company (IE) Limited': '2224',
               'Waystone Management Company (Lux) S.A.': '1671',
               'Wellington Luxembourg S.à r.l.': '1796',
               'WestInvest Gesellschaft für Investmentfonds mbH': '145',
               'Winton Fund Management Ireland DAC': '1797',
               'WisdomTree Management Limited': '1971',
               'WohnSelect Kapitalverwaltungsgesellschaft mbH': '1412',
               'WWK Investment S.A.': '1124',
               'Zadig Asset Management S.A': '1779',
               'ZBI Fondsmanagement AG': '2062'}}
