"""Manifest - REST API Models (SAP-043)

Pydantic models for REST API request/response bodies. These models are
specific to the HTTP interface and translate between API format and core models.

Generated by: chora-base SAP-047 (Capability Server Template)
Customized for: Capability Registry (chora-manifest)
"""

from typing import Any, Dict, List

from pydantic import BaseModel, Field

from manifest.core import Capability


# ============================================================================
# Response Models
# ============================================================================


class CapabilityListResponse(BaseModel):
    """Response model for listing capabilities."""

    capabilities: List[Capability] = Field(
        ...,
        description="List of capability definitions"
    )
    total: int = Field(
        ...,
        ge=0,
        description="Total number of capabilities returned"
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "capabilities": [
                    {
                        "id": "github",
                        "name": "GitHub Integration",
                        "category": "integration",
                        "maturity": "stable",
                        "version": "1.0.0"
                    }
                ],
                "total": 1
            }
        }
    }


class CapabilityResponse(BaseModel):
    """Response model for single capability."""

    capability: Capability = Field(
        ...,
        description="Capability definition"
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "capability": {
                    "id": "github",
                    "name": "GitHub Integration",
                    "description": "Access GitHub repositories and issues",
                    "version": "1.0.0",
                    "docker_image": "liminalcommons/chora-github:0.1.0",
                    "category": "integration",
                    "maturity": "stable"
                }
            }
        }
    }


class SearchResponse(BaseModel):
    """Response model for search results."""

    query: str = Field(
        ...,
        description="Search query string"
    )
    capabilities: List[Capability] = Field(
        ...,
        description="Matching capabilities"
    )
    total: int = Field(
        ...,
        ge=0,
        description="Total number of matching capabilities"
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "query": "database",
                "capabilities": [],
                "total": 0
            }
        }
    }


class CountResponse(BaseModel):
    """Response model for count operations."""

    count: int = Field(
        ...,
        ge=0,
        description="Number of capabilities matching filters"
    )
    filters: Dict[str, Any] = Field(
        default_factory=dict,
        description="Applied filters"
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "count": 4,
                "filters": {
                    "category": "integration",
                    "maturity": None
                }
            }
        }
    }


class StringListResponse(BaseModel):
    """Response model for string list (categories, maturities)."""

    items: List[str] = Field(
        ...,
        description="List of string items"
    )
    total: int = Field(
        ...,
        ge=0,
        description="Total number of items"
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "items": ["integration", "database", "monitoring"],
                "total": 3
            }
        }
    }


class HealthResponse(BaseModel):
    """Response model for health check."""

    status: str = Field(
        ...,
        description="Health status (healthy, not_initialized, etc.)"
    )
    capabilities_loaded: int = Field(
        ...,
        ge=0,
        description="Number of capabilities loaded in registry"
    )
    registry_path: str = Field(
        default="default",
        description="Path to registry file"
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "status": "healthy",
                "capabilities_loaded": 4,
                "registry_path": "default"
            }
        }
    }


# ============================================================================
# Export
# ============================================================================


__all__ = [
    "CapabilityListResponse",
    "CapabilityResponse",
    "SearchResponse",
    "CountResponse",
    "StringListResponse",
    "HealthResponse",
]
