"""
系统配置模块

提供系统级配置，可被 Nuitka 编译成二进制。
"""

# 系统配置
SYSTEM_CONFIG = {
    "system": {
        "encryption": {
            "password": "water_quality_analysis_key",
            "salt": "water_quality_salt",
            "iv": "fixed_iv_16bytes",
            "iterations": 100000,
            "key_length": 32,
        },
        "output": {
            "models_dir": "output/models",
            "logs_dir": "logs",
            "predictions_dir": "output/predictions",
        },
        "logging": {
            "level": "INFO",
            "max_bytes": 10485760,
            "backup_count": 5,
            "console_output": True,
        },
    },
    "water_quality_params": [
        "Turb",
        "SS",
        "SD",
        "DO",
        "CODMn",
        "COD",
        "Chla",
        "TN",
        "TP",
        "Chroma",
        "NH3-N",
    ],
    "feature_stations": [
        "STZ1",
        "STZ2",
        "STZ3",
        "STZ4",
        "STZ5",
        "STZ6",
        "STZ7",
        "STZ8",
        "STZ9",
        "STZ10",
        "STZ11",
        "STZ12",
        "STZ13",
        "STZ14",
        "STZ15",
        "STZ16",
        "STZ17",
        "STZ18",
        "STZ19",
        "STZ20",
        "STZ21",
        "STZ22",
        "STZ23",
        "STZ24",
        "STZ25",
        "STZ26",
    ],
    "column_name_mapping": {
        "comment": "双向列名映射配置 - 标准名称版本",
        "input_mappings": {
            "turbidity": "Turb",
            "TURBIDITY": "Turb",
            "Turbidity": "Turb",
            "浊度": "Turb",
            "NTU": "Turb",
            "turb": "Turb",
            "ss": "SS",
            "悬浮物": "SS",
            "TSS": "SS",
            "总悬浮物": "SS",
            "suspended solids": "SS",
            "sd": "SD",
            "Sd": "SD",
            "透明度": "SD",
            "Secchi": "SD",
            "塞氏盘深度": "SD",
            "do": "DO",
            "溶解氧": "DO",
            "Dissolved_Oxygen": "DO",
            "dissolved oxygen": "DO",
            "codmn": "CODMn",
            "CODMN": "CODMn",
            "高锰酸盐": "CODMn",
            "高锰酸盐指数": "CODMn",
            "cod": "COD",
            "codcr": "COD",
            "CODCR": "COD",
            "CODCr": "COD",
            "化学需氧量": "COD",
            "重铬酸盐指数": "COD",
            "chemical oxygen demand": "COD",
            "chla": "Chla",
            "CHLA": "Chla",
            "CHL-A": "Chla",
            "chl": "Chla",
            "chl_a": "Chla",
            "叶绿素": "Chla",
            "叶绿素a": "Chla",
            "叶绿素A": "Chla",
            "Chlorophyll-a": "Chla",
            "chlorophyll": "Chla",
            "tn": "TN",
            "总氮": "TN",
            "Total_Nitrogen": "TN",
            "total nitrogen": "TN",
            "tp": "TP",
            "总磷": "TP",
            "Total_Phosphorus": "TP",
            "total phosphorus": "TP",
            "chroma": "Chroma",
            "CHROMA": "Chroma",
            "色度": "Chroma",
            "Color": "Chroma",
            "nh3n": "NH3-N",
            "nh3-n": "NH3-N",
            "NH3N": "NH3-N",
            "nh3_n": "NH3-N",
            "氨氮": "NH3-N",
            "Ammonia_Nitrogen": "NH3-N",
            "ammonia nitrogen": "NH3-N",
        },
        "output_mappings": {
            "Turb": "Turb",
            "SS": "SS",
            "SD": "SD",
            "DO": "DO",
            "CODMn": "CODMn",
            "COD": "COD",
            "Chla": "Chla",
            "TN": "TN",
            "TP": "TP",
            "Chroma": "Chroma",
            "NH3-N": "NH3-N",
        },
    },
    "processing": {
        "default_min_wavelength": 400,
        "default_max_wavelength": 900,
        "default_smooth_window": 11,
        "default_smooth_order": 3,
        "anomaly_threshold": 0.1,
        "interpolation_method": "cubic",
    },
    "modeling": {
        "default_min_samples": 6,
        "default_max_features": 5,
        "correlation_threshold": 0.3,
        "power_model_bounds": {"a": [1e-06, 100000], "b": [-50, 50]},
        "max_fitting_iterations": 10000,
    },
}


# 便捷访问函数
def get_config() -> dict:
    """获取系统配置"""
    return SYSTEM_CONFIG
