
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-11-17T16:08:27+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "28fc6c52930ffc17214905de3425db10b15cb6ba",
 "version": "1.0.2a5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
