# __init__.py

from pyfcach import (
    CacheStrategy,
    CacheInfo,
    CacheBase,
    ARCCache,
    OptimizedLFUCache,
    TTLCache,
    HighPerformanceCache,
    AsyncCache,
    cache,
    async_cache,
    cached_property,
    AsyncCachedProperty,
    cache_clear_all,
    get_cache_info,
    get_global_stats,
    async_cache_clear_all,
    async_get_cache_info,
    async_get_global_stats,
)

__all__ = [
    "CacheStrategy",
    "CacheInfo",
    "CacheBase",
    "ARCCache",
    "OptimizedLFUCache",
    "TTLCache",
    "HighPerformanceCache",
    "AsyncCache",
    "cache",
    "async_cache",
    "cached_property",
    "AsyncCachedProperty",
    "cache_clear_all",
    "get_cache_info",
    "get_global_stats",
    "async_cache_clear_all",
    "async_get_cache_info",
    "async_get_global_stats",
]