from pydantic import BaseModel
from typing_extensions import Annotated

class File(BaseModel):
    dir_path: str
    filename: Annotated[str, None]
    content: str
    def __init__(self, filename: str, dir_path: str, new: bool = False) -> None: ...
    def add_content(self, content: str = "") -> None: ...
    def save(self) -> None: ...
    def protect(self) -> None: ...
