"""Constants for RIFF format."""

RIFF_HEADER_SIZE = 12
RIFF_CHUNK_ID_SIZE = 4
RIFF_WAVE_FORMAT_POSITION = 8
RIFF_MIN_DATA_SIZE_FOR_ID3V2 = 10
RIFF_INFO_CHUNK_MIN_SIZE = 16
RIFF_MIN_VERSION_LENGTH = 3
RIFF_AUDIO_FORMAT_IEEE_FLOAT = 3
RIFF_FORMAT_CHUNK_MIN_SIZE = 16
