"""Type stubs for TextQL exceptions"""

import grpc

class TextQLError(Exception): ...
class AuthenticationError(TextQLError): ...
class ConnectionError(TextQLError): ...
class InvalidRequestError(TextQLError): ...
class RateLimitError(TextQLError): ...
class NotFoundError(TextQLError): ...
class ServerError(TextQLError): ...

def handle_grpc_error(error: grpc.RpcError) -> TextQLError: ...
