---
title: "Bellhop.py tutorials"
format:
  html:
    code-fold: true
jupyter: python3
---

## Tutorials

- [Introduction](intro.qmd)
    - basics of creating an environment and plotting results
- [Computation options](compute.qmd)
    - using the more general interface to define different ways of executing computations
- [Environment configuration](environ.qmd)
    - describes how to set up the simulation environment
- [Environment parameters](environ-fields.qmd)
    - comprehensive survey of environment parameters
- [Sound speed profiles](ssp.qmd)
    - defining depth-dependent SSPs and setting interpolation options
    - example using NOAA data to define a 2D sound speed profile that varies with range and depth
- [Surface properties](surface.qmd)
    - defining surface properties and range-dependent surface profiles
    - examples of a JONSWAP sea state distribution, and underwater sea ice

## Other Bellhop documentation

- [Main Bellhop documentation](https://avc-adelaide.github.io/bellhoppe/)
- [Python API documentation](https://avc-adelaide.github.io/bellhoppe/media/python/)
- [Github repository link](https://github.com/avc-adelaide/bellhoppe)
