# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openobd_protocol/Configuration/Messages/CanBus.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4openobd_protocol/Configuration/Messages/CanBus.proto\x12\nopenOBD.v1\"\xd0\x01\n\x06\x43\x61nBus\x12\x10\n\x08pin_plus\x18\x01 \x01(\r\x12\x0f\n\x07pin_min\x18\x02 \x01(\r\x12-\n\x0c\x63\x61n_protocol\x18\x03 \x01(\x0e\x32\x17.openOBD.v1.CanProtocol\x12,\n\x0c\x63\x61n_bit_rate\x18\x04 \x01(\x0e\x32\x16.openOBD.v1.CanBitRate\x12\x36\n\x0btransceiver\x18\x05 \x01(\x0e\x32\x1c.openOBD.v1.TransceiverSpeedH\x00\x88\x01\x01\x42\x0e\n\x0c_transceiver*q\n\x0b\x43\x61nProtocol\x12\x1a\n\x16\x43\x41N_PROTOCOL_UNDEFINED\x10\x00\x12\x16\n\x12\x43\x41N_PROTOCOL_ISOTP\x10\x01\x12\x15\n\x11\x43\x41N_PROTOCOL_TP20\x10\x02\x12\x17\n\x13\x43\x41N_PROTOCOL_FRAMES\x10\x03*\xad\x02\n\nCanBitRate\x12\x1a\n\x16\x43\x41N_BIT_RATE_UNDEFINED\x10\x00\x12\x15\n\x11\x43\x41N_BIT_RATE_1000\x10\x01\x12\x14\n\x10\x43\x41N_BIT_RATE_500\x10\x02\x12\x14\n\x10\x43\x41N_BIT_RATE_250\x10\x03\x12\x14\n\x10\x43\x41N_BIT_RATE_125\x10\x04\x12\x14\n\x10\x43\x41N_BIT_RATE_100\x10\x05\x12\x13\n\x0f\x43\x41N_BIT_RATE_94\x10\x06\x12\x15\n\x11\x43\x41N_BIT_RATE_83_3\x10\x07\x12\x13\n\x0f\x43\x41N_BIT_RATE_50\x10\x08\x12\x15\n\x11\x43\x41N_BIT_RATE_33_3\x10\t\x12\x13\n\x0f\x43\x41N_BIT_RATE_20\x10\n\x12\x13\n\x0f\x43\x41N_BIT_RATE_10\x10\x0b\x12\x12\n\x0e\x43\x41N_BIT_RATE_5\x10\x0c*I\n\x10TransceiverSpeed\x12\x19\n\x15TRANSCEIVER_SPEED_LOW\x10\x00\x12\x1a\n\x16TRANSCEIVER_SPEED_HIGH\x10\x01\x42/\n+com.jifeline.OpenOBD.Configuration.MessagesP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'openobd_protocol.Configuration.Messages.CanBus_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n+com.jifeline.OpenOBD.Configuration.MessagesP\001'
  _globals['_CANPROTOCOL']._serialized_start=279
  _globals['_CANPROTOCOL']._serialized_end=392
  _globals['_CANBITRATE']._serialized_start=395
  _globals['_CANBITRATE']._serialized_end=696
  _globals['_TRANSCEIVERSPEED']._serialized_start=698
  _globals['_TRANSCEIVERSPEED']._serialized_end=771
  _globals['_CANBUS']._serialized_start=69
  _globals['_CANBUS']._serialized_end=277
# @@protoc_insertion_point(module_scope)
