# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openobd_protocol/Configuration/Messages/DoipBus.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5openobd_protocol/Configuration/Messages/DoipBus.proto\x12\nopenOBD.v1\"\x80\x01\n\x07\x44oipBus\x12+\n\x0b\x64oip_option\x18\x01 \x01(\x0e\x32\x16.openOBD.v1.DoipOption\x12H\n\x1a\x64oip_network_configuration\x18\x02 \x01(\x0e\x32$.openOBD.v1.DoipNetworkConfiguration*M\n\nDoipOption\x12\x19\n\x15\x44OIP_OPTION_UNDEFINED\x10\x00\x12\x11\n\rDOIP_OPTION_1\x10\x01\x12\x11\n\rDOIP_OPTION_2\x10\x02*\xff\x02\n\x18\x44oipNetworkConfiguration\x12(\n$DOIP_NETWORK_CONFIGURATION_UNDEFINED\x10\x00\x12!\n\x1c\x44OIP_NETWORK_CONFIGURATION_1\x10\xb9\x17\x12!\n\x1c\x44OIP_NETWORK_CONFIGURATION_2\x10\xba\x17\x12!\n\x1c\x44OIP_NETWORK_CONFIGURATION_3\x10\xbb\x17\x12!\n\x1c\x44OIP_NETWORK_CONFIGURATION_4\x10\xbc\x17\x12!\n\x1c\x44OIP_NETWORK_CONFIGURATION_5\x10\xbd\x17\x12!\n\x1c\x44OIP_NETWORK_CONFIGURATION_6\x10\xbe\x17\x12!\n\x1c\x44OIP_NETWORK_CONFIGURATION_7\x10\xbf\x17\x12!\n\x1c\x44OIP_NETWORK_CONFIGURATION_8\x10\xc0\x17\x12!\n\x1c\x44OIP_NETWORK_CONFIGURATION_9\x10\xc1\x17\x42/\n+com.jifeline.OpenOBD.Configuration.MessagesP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'openobd_protocol.Configuration.Messages.DoipBus_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n+com.jifeline.OpenOBD.Configuration.MessagesP\001'
  _globals['_DOIPOPTION']._serialized_start=200
  _globals['_DOIPOPTION']._serialized_end=277
  _globals['_DOIPNETWORKCONFIGURATION']._serialized_start=280
  _globals['_DOIPNETWORKCONFIGURATION']._serialized_end=663
  _globals['_DOIPBUS']._serialized_start=70
  _globals['_DOIPBUS']._serialized_end=198
# @@protoc_insertion_point(module_scope)
