```{r}
library(tidyverse)
```

```{r}
data <- read_csv("benchmarks/results/bench_result.csv") %>%
    mutate(
        package = factor(package, levels = c("gridio", "textgrid", "parselmouth")),
        task = ifelse(task == "construct", "Task: Read TextGrid", "Task: Read TextGrid and Convert to DataFrame"),
    ) %>%
    group_by(task, package) %>%
    summarise(
        mean = mean(seconds),
        sd = sd(seconds),
    ) %>%
    ungroup() %>%
    group_by(task) %>%
    mutate(
        min_mean = min(mean)
    ) %>%
    ungroup()
```

```{r}
ggplot(data) +
    geom_bar(aes(x = mean, y = package, fill = package), stat = "identity", width = 0.4) +
    geom_errorbar(
        aes(xmin = mean - sd, xmax = mean + sd, y = package),
        width = 0.2,
        color = "black"
    ) +
    geom_text(aes(x = mean, y = package, label = sprintf("%.3f\n(%.1fx)", mean, mean / min_mean)), hjust = -0.5, size = 4) +
    scale_fill_brewer(palette = "Set2") +
    facet_wrap(~task, scales = "free_x", nrow = 2) +
    theme_minimal(base_size = 16) +
    theme(legend.position = "top", panel.grid.major.y = element_blank()) +
    scale_x_continuous(transform = "sqrt", limits = c(0, 250)) +
    coord_cartesian(clip = "off") +
    labs(y = "", x = "Time Taken (seconds)")
ggsave("benchmarks/results/benchmark_plot.png", width = 10, height = 6, dpi = 300)
```

