# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.3.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.


import collections

from sys import version_info as _version_info
if _version_info < (3, 7, 0):
    raise RuntimeError("Python 3.7 or later required")

from . import _ITKCommonPython


from . import _SubdivisionQuadEdgeMeshFilterPython



from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _itkQuadEdgeMeshSubdivisionCriterionPython
else:
    import _itkQuadEdgeMeshSubdivisionCriterionPython

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


if _swig_python_version_info[0:2] >= (3, 3):
    import collections.abc
else:
    import collections

import itk.ITKCommonBasePython
import itk.itkMatrixPython
import itk.itkCovariantVectorPython
import itk.itkVectorPython
import itk.vnl_vector_refPython
import itk.stdcomplexPython
import itk.pyBasePython
import itk.vnl_vectorPython
import itk.vnl_matrixPython
import itk.itkFixedArrayPython
import itk.vnl_matrix_fixedPython
import itk.itkPointPython
import itk.itkQuadEdgeMeshBasePython
import itk.itkVectorContainerPython
import itk.itkOffsetPython
import itk.itkSizePython
import itk.itkContinuousIndexPython
import itk.itkIndexPython
import itk.itkArrayPython
import itk.itkQuadEdgeMeshLineCellPython
import itk.itkQuadEdgeCellTraitsInfoPython
import itk.itkQuadEdgeMeshPointPython
import itk.itkGeometricalQuadEdgePython
import itk.itkQuadEdgePython
import itk.itkImagePython
import itk.itkImageRegionPython
import itk.itkRGBPixelPython
import itk.itkRGBAPixelPython
import itk.itkSymmetricSecondRankTensorPython
import itk.itkMapContainerPython
class itkQuadEdgeMeshSubdivisionCriterionLinearTriangleD2(itk.ITKCommonBasePython.itkObject):
    r"""Proxy of C++ itkQuadEdgeMeshSubdivisionCriterionLinearTriangleD2 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr

    def Compute(self, mesh, edgeList):
        r"""
        Compute(self, mesh, edgeList)

        Parameters
        ----------
        mesh: itkQuadEdgeMeshD2 *
        edgeList: std::list< unsigned long,std::allocator< unsigned long > > &

        """
        return _itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionLinearTriangleD2_Compute(self, mesh, edgeList)
    __swig_destroy__ = _itkQuadEdgeMeshSubdivisionCriterionPython.delete_itkQuadEdgeMeshSubdivisionCriterionLinearTriangleD2

    @staticmethod
    def cast(obj):
        r"""
        cast(obj) -> itkQuadEdgeMeshSubdivisionCriterionLinearTriangleD2

        Parameters
        ----------
        obj: itkLightObject *

        """
        return _itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionLinearTriangleD2_cast(obj)

# Register itkQuadEdgeMeshSubdivisionCriterionLinearTriangleD2 in _itkQuadEdgeMeshSubdivisionCriterionPython:
_itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionLinearTriangleD2_swigregister(itkQuadEdgeMeshSubdivisionCriterionLinearTriangleD2)
class itkQuadEdgeMeshSubdivisionCriterionLinearTriangleD3(itk.ITKCommonBasePython.itkObject):
    r"""Proxy of C++ itkQuadEdgeMeshSubdivisionCriterionLinearTriangleD3 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr

    def Compute(self, mesh, edgeList):
        r"""
        Compute(self, mesh, edgeList)

        Parameters
        ----------
        mesh: itkQuadEdgeMeshD3 *
        edgeList: std::list< unsigned long,std::allocator< unsigned long > > &

        """
        return _itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionLinearTriangleD3_Compute(self, mesh, edgeList)
    __swig_destroy__ = _itkQuadEdgeMeshSubdivisionCriterionPython.delete_itkQuadEdgeMeshSubdivisionCriterionLinearTriangleD3

    @staticmethod
    def cast(obj):
        r"""
        cast(obj) -> itkQuadEdgeMeshSubdivisionCriterionLinearTriangleD3

        Parameters
        ----------
        obj: itkLightObject *

        """
        return _itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionLinearTriangleD3_cast(obj)

# Register itkQuadEdgeMeshSubdivisionCriterionLinearTriangleD3 in _itkQuadEdgeMeshSubdivisionCriterionPython:
_itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionLinearTriangleD3_swigregister(itkQuadEdgeMeshSubdivisionCriterionLinearTriangleD3)
class itkQuadEdgeMeshSubdivisionCriterionLinearTriangleD4(itk.ITKCommonBasePython.itkObject):
    r"""Proxy of C++ itkQuadEdgeMeshSubdivisionCriterionLinearTriangleD4 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr

    def Compute(self, mesh, edgeList):
        r"""
        Compute(self, mesh, edgeList)

        Parameters
        ----------
        mesh: itkQuadEdgeMeshD4 *
        edgeList: std::list< unsigned long,std::allocator< unsigned long > > &

        """
        return _itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionLinearTriangleD4_Compute(self, mesh, edgeList)
    __swig_destroy__ = _itkQuadEdgeMeshSubdivisionCriterionPython.delete_itkQuadEdgeMeshSubdivisionCriterionLinearTriangleD4

    @staticmethod
    def cast(obj):
        r"""
        cast(obj) -> itkQuadEdgeMeshSubdivisionCriterionLinearTriangleD4

        Parameters
        ----------
        obj: itkLightObject *

        """
        return _itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionLinearTriangleD4_cast(obj)

# Register itkQuadEdgeMeshSubdivisionCriterionLinearTriangleD4 in _itkQuadEdgeMeshSubdivisionCriterionPython:
_itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionLinearTriangleD4_swigregister(itkQuadEdgeMeshSubdivisionCriterionLinearTriangleD4)
class itkQuadEdgeMeshSubdivisionCriterionLinearTriangleEdgeD2(itk.ITKCommonBasePython.itkObject):
    r"""Proxy of C++ itkQuadEdgeMeshSubdivisionCriterionLinearTriangleEdgeD2 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr

    def Compute(self, mesh, edgeList):
        r"""
        Compute(self, mesh, edgeList)

        Parameters
        ----------
        mesh: itkQuadEdgeMeshD2 *
        edgeList: std::list< itkGeometricalQuadEdgeULULBBF *,std::allocator< itkGeometricalQuadEdgeULULBBF * > > &

        """
        return _itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionLinearTriangleEdgeD2_Compute(self, mesh, edgeList)
    __swig_destroy__ = _itkQuadEdgeMeshSubdivisionCriterionPython.delete_itkQuadEdgeMeshSubdivisionCriterionLinearTriangleEdgeD2

    @staticmethod
    def cast(obj):
        r"""
        cast(obj) -> itkQuadEdgeMeshSubdivisionCriterionLinearTriangleEdgeD2

        Parameters
        ----------
        obj: itkLightObject *

        """
        return _itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionLinearTriangleEdgeD2_cast(obj)

# Register itkQuadEdgeMeshSubdivisionCriterionLinearTriangleEdgeD2 in _itkQuadEdgeMeshSubdivisionCriterionPython:
_itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionLinearTriangleEdgeD2_swigregister(itkQuadEdgeMeshSubdivisionCriterionLinearTriangleEdgeD2)
class itkQuadEdgeMeshSubdivisionCriterionLinearTriangleEdgeD3(itk.ITKCommonBasePython.itkObject):
    r"""Proxy of C++ itkQuadEdgeMeshSubdivisionCriterionLinearTriangleEdgeD3 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr

    def Compute(self, mesh, edgeList):
        r"""
        Compute(self, mesh, edgeList)

        Parameters
        ----------
        mesh: itkQuadEdgeMeshD3 *
        edgeList: std::list< itkGeometricalQuadEdgeULULBBF *,std::allocator< itkGeometricalQuadEdgeULULBBF * > > &

        """
        return _itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionLinearTriangleEdgeD3_Compute(self, mesh, edgeList)
    __swig_destroy__ = _itkQuadEdgeMeshSubdivisionCriterionPython.delete_itkQuadEdgeMeshSubdivisionCriterionLinearTriangleEdgeD3

    @staticmethod
    def cast(obj):
        r"""
        cast(obj) -> itkQuadEdgeMeshSubdivisionCriterionLinearTriangleEdgeD3

        Parameters
        ----------
        obj: itkLightObject *

        """
        return _itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionLinearTriangleEdgeD3_cast(obj)

# Register itkQuadEdgeMeshSubdivisionCriterionLinearTriangleEdgeD3 in _itkQuadEdgeMeshSubdivisionCriterionPython:
_itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionLinearTriangleEdgeD3_swigregister(itkQuadEdgeMeshSubdivisionCriterionLinearTriangleEdgeD3)
class itkQuadEdgeMeshSubdivisionCriterionLinearTriangleEdgeD4(itk.ITKCommonBasePython.itkObject):
    r"""Proxy of C++ itkQuadEdgeMeshSubdivisionCriterionLinearTriangleEdgeD4 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr

    def Compute(self, mesh, edgeList):
        r"""
        Compute(self, mesh, edgeList)

        Parameters
        ----------
        mesh: itkQuadEdgeMeshD4 *
        edgeList: std::list< itkGeometricalQuadEdgeULULBBF *,std::allocator< itkGeometricalQuadEdgeULULBBF * > > &

        """
        return _itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionLinearTriangleEdgeD4_Compute(self, mesh, edgeList)
    __swig_destroy__ = _itkQuadEdgeMeshSubdivisionCriterionPython.delete_itkQuadEdgeMeshSubdivisionCriterionLinearTriangleEdgeD4

    @staticmethod
    def cast(obj):
        r"""
        cast(obj) -> itkQuadEdgeMeshSubdivisionCriterionLinearTriangleEdgeD4

        Parameters
        ----------
        obj: itkLightObject *

        """
        return _itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionLinearTriangleEdgeD4_cast(obj)

# Register itkQuadEdgeMeshSubdivisionCriterionLinearTriangleEdgeD4 in _itkQuadEdgeMeshSubdivisionCriterionPython:
_itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionLinearTriangleEdgeD4_swigregister(itkQuadEdgeMeshSubdivisionCriterionLinearTriangleEdgeD4)
class itkQuadEdgeMeshSubdivisionCriterionLoopTriangleD2(itk.ITKCommonBasePython.itkObject):
    r"""Proxy of C++ itkQuadEdgeMeshSubdivisionCriterionLoopTriangleD2 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr

    def Compute(self, mesh, edgeList):
        r"""
        Compute(self, mesh, edgeList)

        Parameters
        ----------
        mesh: itkQuadEdgeMeshD2 *
        edgeList: std::list< unsigned long,std::allocator< unsigned long > > &

        """
        return _itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionLoopTriangleD2_Compute(self, mesh, edgeList)
    __swig_destroy__ = _itkQuadEdgeMeshSubdivisionCriterionPython.delete_itkQuadEdgeMeshSubdivisionCriterionLoopTriangleD2

    @staticmethod
    def cast(obj):
        r"""
        cast(obj) -> itkQuadEdgeMeshSubdivisionCriterionLoopTriangleD2

        Parameters
        ----------
        obj: itkLightObject *

        """
        return _itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionLoopTriangleD2_cast(obj)

# Register itkQuadEdgeMeshSubdivisionCriterionLoopTriangleD2 in _itkQuadEdgeMeshSubdivisionCriterionPython:
_itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionLoopTriangleD2_swigregister(itkQuadEdgeMeshSubdivisionCriterionLoopTriangleD2)
class itkQuadEdgeMeshSubdivisionCriterionLoopTriangleD3(itk.ITKCommonBasePython.itkObject):
    r"""Proxy of C++ itkQuadEdgeMeshSubdivisionCriterionLoopTriangleD3 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr

    def Compute(self, mesh, edgeList):
        r"""
        Compute(self, mesh, edgeList)

        Parameters
        ----------
        mesh: itkQuadEdgeMeshD3 *
        edgeList: std::list< unsigned long,std::allocator< unsigned long > > &

        """
        return _itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionLoopTriangleD3_Compute(self, mesh, edgeList)
    __swig_destroy__ = _itkQuadEdgeMeshSubdivisionCriterionPython.delete_itkQuadEdgeMeshSubdivisionCriterionLoopTriangleD3

    @staticmethod
    def cast(obj):
        r"""
        cast(obj) -> itkQuadEdgeMeshSubdivisionCriterionLoopTriangleD3

        Parameters
        ----------
        obj: itkLightObject *

        """
        return _itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionLoopTriangleD3_cast(obj)

# Register itkQuadEdgeMeshSubdivisionCriterionLoopTriangleD3 in _itkQuadEdgeMeshSubdivisionCriterionPython:
_itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionLoopTriangleD3_swigregister(itkQuadEdgeMeshSubdivisionCriterionLoopTriangleD3)
class itkQuadEdgeMeshSubdivisionCriterionLoopTriangleD4(itk.ITKCommonBasePython.itkObject):
    r"""Proxy of C++ itkQuadEdgeMeshSubdivisionCriterionLoopTriangleD4 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr

    def Compute(self, mesh, edgeList):
        r"""
        Compute(self, mesh, edgeList)

        Parameters
        ----------
        mesh: itkQuadEdgeMeshD4 *
        edgeList: std::list< unsigned long,std::allocator< unsigned long > > &

        """
        return _itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionLoopTriangleD4_Compute(self, mesh, edgeList)
    __swig_destroy__ = _itkQuadEdgeMeshSubdivisionCriterionPython.delete_itkQuadEdgeMeshSubdivisionCriterionLoopTriangleD4

    @staticmethod
    def cast(obj):
        r"""
        cast(obj) -> itkQuadEdgeMeshSubdivisionCriterionLoopTriangleD4

        Parameters
        ----------
        obj: itkLightObject *

        """
        return _itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionLoopTriangleD4_cast(obj)

# Register itkQuadEdgeMeshSubdivisionCriterionLoopTriangleD4 in _itkQuadEdgeMeshSubdivisionCriterionPython:
_itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionLoopTriangleD4_swigregister(itkQuadEdgeMeshSubdivisionCriterionLoopTriangleD4)
class itkQuadEdgeMeshSubdivisionCriterionLoopTriangleEdgeD2(itk.ITKCommonBasePython.itkObject):
    r"""Proxy of C++ itkQuadEdgeMeshSubdivisionCriterionLoopTriangleEdgeD2 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr

    def Compute(self, mesh, edgeList):
        r"""
        Compute(self, mesh, edgeList)

        Parameters
        ----------
        mesh: itkQuadEdgeMeshD2 *
        edgeList: std::list< itkGeometricalQuadEdgeULULBBF *,std::allocator< itkGeometricalQuadEdgeULULBBF * > > &

        """
        return _itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionLoopTriangleEdgeD2_Compute(self, mesh, edgeList)
    __swig_destroy__ = _itkQuadEdgeMeshSubdivisionCriterionPython.delete_itkQuadEdgeMeshSubdivisionCriterionLoopTriangleEdgeD2

    @staticmethod
    def cast(obj):
        r"""
        cast(obj) -> itkQuadEdgeMeshSubdivisionCriterionLoopTriangleEdgeD2

        Parameters
        ----------
        obj: itkLightObject *

        """
        return _itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionLoopTriangleEdgeD2_cast(obj)

# Register itkQuadEdgeMeshSubdivisionCriterionLoopTriangleEdgeD2 in _itkQuadEdgeMeshSubdivisionCriterionPython:
_itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionLoopTriangleEdgeD2_swigregister(itkQuadEdgeMeshSubdivisionCriterionLoopTriangleEdgeD2)
class itkQuadEdgeMeshSubdivisionCriterionLoopTriangleEdgeD3(itk.ITKCommonBasePython.itkObject):
    r"""Proxy of C++ itkQuadEdgeMeshSubdivisionCriterionLoopTriangleEdgeD3 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr

    def Compute(self, mesh, edgeList):
        r"""
        Compute(self, mesh, edgeList)

        Parameters
        ----------
        mesh: itkQuadEdgeMeshD3 *
        edgeList: std::list< itkGeometricalQuadEdgeULULBBF *,std::allocator< itkGeometricalQuadEdgeULULBBF * > > &

        """
        return _itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionLoopTriangleEdgeD3_Compute(self, mesh, edgeList)
    __swig_destroy__ = _itkQuadEdgeMeshSubdivisionCriterionPython.delete_itkQuadEdgeMeshSubdivisionCriterionLoopTriangleEdgeD3

    @staticmethod
    def cast(obj):
        r"""
        cast(obj) -> itkQuadEdgeMeshSubdivisionCriterionLoopTriangleEdgeD3

        Parameters
        ----------
        obj: itkLightObject *

        """
        return _itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionLoopTriangleEdgeD3_cast(obj)

# Register itkQuadEdgeMeshSubdivisionCriterionLoopTriangleEdgeD3 in _itkQuadEdgeMeshSubdivisionCriterionPython:
_itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionLoopTriangleEdgeD3_swigregister(itkQuadEdgeMeshSubdivisionCriterionLoopTriangleEdgeD3)
class itkQuadEdgeMeshSubdivisionCriterionLoopTriangleEdgeD4(itk.ITKCommonBasePython.itkObject):
    r"""Proxy of C++ itkQuadEdgeMeshSubdivisionCriterionLoopTriangleEdgeD4 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr

    def Compute(self, mesh, edgeList):
        r"""
        Compute(self, mesh, edgeList)

        Parameters
        ----------
        mesh: itkQuadEdgeMeshD4 *
        edgeList: std::list< itkGeometricalQuadEdgeULULBBF *,std::allocator< itkGeometricalQuadEdgeULULBBF * > > &

        """
        return _itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionLoopTriangleEdgeD4_Compute(self, mesh, edgeList)
    __swig_destroy__ = _itkQuadEdgeMeshSubdivisionCriterionPython.delete_itkQuadEdgeMeshSubdivisionCriterionLoopTriangleEdgeD4

    @staticmethod
    def cast(obj):
        r"""
        cast(obj) -> itkQuadEdgeMeshSubdivisionCriterionLoopTriangleEdgeD4

        Parameters
        ----------
        obj: itkLightObject *

        """
        return _itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionLoopTriangleEdgeD4_cast(obj)

# Register itkQuadEdgeMeshSubdivisionCriterionLoopTriangleEdgeD4 in _itkQuadEdgeMeshSubdivisionCriterionPython:
_itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionLoopTriangleEdgeD4_swigregister(itkQuadEdgeMeshSubdivisionCriterionLoopTriangleEdgeD4)
class itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleD2(itk.ITKCommonBasePython.itkObject):
    r"""Proxy of C++ itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleD2 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr

    def Compute(self, mesh, edgeList):
        r"""
        Compute(self, mesh, edgeList)

        Parameters
        ----------
        mesh: itkQuadEdgeMeshD2 *
        edgeList: std::list< unsigned long,std::allocator< unsigned long > > &

        """
        return _itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleD2_Compute(self, mesh, edgeList)
    __swig_destroy__ = _itkQuadEdgeMeshSubdivisionCriterionPython.delete_itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleD2

    @staticmethod
    def cast(obj):
        r"""
        cast(obj) -> itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleD2

        Parameters
        ----------
        obj: itkLightObject *

        """
        return _itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleD2_cast(obj)

# Register itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleD2 in _itkQuadEdgeMeshSubdivisionCriterionPython:
_itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleD2_swigregister(itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleD2)
class itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleD3(itk.ITKCommonBasePython.itkObject):
    r"""Proxy of C++ itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleD3 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr

    def Compute(self, mesh, edgeList):
        r"""
        Compute(self, mesh, edgeList)

        Parameters
        ----------
        mesh: itkQuadEdgeMeshD3 *
        edgeList: std::list< unsigned long,std::allocator< unsigned long > > &

        """
        return _itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleD3_Compute(self, mesh, edgeList)
    __swig_destroy__ = _itkQuadEdgeMeshSubdivisionCriterionPython.delete_itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleD3

    @staticmethod
    def cast(obj):
        r"""
        cast(obj) -> itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleD3

        Parameters
        ----------
        obj: itkLightObject *

        """
        return _itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleD3_cast(obj)

# Register itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleD3 in _itkQuadEdgeMeshSubdivisionCriterionPython:
_itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleD3_swigregister(itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleD3)
class itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleD4(itk.ITKCommonBasePython.itkObject):
    r"""Proxy of C++ itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleD4 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr

    def Compute(self, mesh, edgeList):
        r"""
        Compute(self, mesh, edgeList)

        Parameters
        ----------
        mesh: itkQuadEdgeMeshD4 *
        edgeList: std::list< unsigned long,std::allocator< unsigned long > > &

        """
        return _itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleD4_Compute(self, mesh, edgeList)
    __swig_destroy__ = _itkQuadEdgeMeshSubdivisionCriterionPython.delete_itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleD4

    @staticmethod
    def cast(obj):
        r"""
        cast(obj) -> itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleD4

        Parameters
        ----------
        obj: itkLightObject *

        """
        return _itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleD4_cast(obj)

# Register itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleD4 in _itkQuadEdgeMeshSubdivisionCriterionPython:
_itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleD4_swigregister(itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleD4)
class itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleEdgeD2(itk.ITKCommonBasePython.itkObject):
    r"""Proxy of C++ itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleEdgeD2 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr

    def Compute(self, mesh, edgeList):
        r"""
        Compute(self, mesh, edgeList)

        Parameters
        ----------
        mesh: itkQuadEdgeMeshD2 *
        edgeList: std::list< itkGeometricalQuadEdgeULULBBF *,std::allocator< itkGeometricalQuadEdgeULULBBF * > > &

        """
        return _itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleEdgeD2_Compute(self, mesh, edgeList)
    __swig_destroy__ = _itkQuadEdgeMeshSubdivisionCriterionPython.delete_itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleEdgeD2

    @staticmethod
    def cast(obj):
        r"""
        cast(obj) -> itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleEdgeD2

        Parameters
        ----------
        obj: itkLightObject *

        """
        return _itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleEdgeD2_cast(obj)

# Register itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleEdgeD2 in _itkQuadEdgeMeshSubdivisionCriterionPython:
_itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleEdgeD2_swigregister(itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleEdgeD2)
class itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleEdgeD3(itk.ITKCommonBasePython.itkObject):
    r"""Proxy of C++ itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleEdgeD3 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr

    def Compute(self, mesh, edgeList):
        r"""
        Compute(self, mesh, edgeList)

        Parameters
        ----------
        mesh: itkQuadEdgeMeshD3 *
        edgeList: std::list< itkGeometricalQuadEdgeULULBBF *,std::allocator< itkGeometricalQuadEdgeULULBBF * > > &

        """
        return _itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleEdgeD3_Compute(self, mesh, edgeList)
    __swig_destroy__ = _itkQuadEdgeMeshSubdivisionCriterionPython.delete_itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleEdgeD3

    @staticmethod
    def cast(obj):
        r"""
        cast(obj) -> itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleEdgeD3

        Parameters
        ----------
        obj: itkLightObject *

        """
        return _itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleEdgeD3_cast(obj)

# Register itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleEdgeD3 in _itkQuadEdgeMeshSubdivisionCriterionPython:
_itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleEdgeD3_swigregister(itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleEdgeD3)
class itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleEdgeD4(itk.ITKCommonBasePython.itkObject):
    r"""Proxy of C++ itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleEdgeD4 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr

    def Compute(self, mesh, edgeList):
        r"""
        Compute(self, mesh, edgeList)

        Parameters
        ----------
        mesh: itkQuadEdgeMeshD4 *
        edgeList: std::list< itkGeometricalQuadEdgeULULBBF *,std::allocator< itkGeometricalQuadEdgeULULBBF * > > &

        """
        return _itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleEdgeD4_Compute(self, mesh, edgeList)
    __swig_destroy__ = _itkQuadEdgeMeshSubdivisionCriterionPython.delete_itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleEdgeD4

    @staticmethod
    def cast(obj):
        r"""
        cast(obj) -> itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleEdgeD4

        Parameters
        ----------
        obj: itkLightObject *

        """
        return _itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleEdgeD4_cast(obj)

# Register itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleEdgeD4 in _itkQuadEdgeMeshSubdivisionCriterionPython:
_itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleEdgeD4_swigregister(itkQuadEdgeMeshSubdivisionCriterionModifiedButterflyTriangleEdgeD4)
class itkQuadEdgeMeshSubdivisionCriterionSquareThreeTriangleD2(itk.ITKCommonBasePython.itkObject):
    r"""Proxy of C++ itkQuadEdgeMeshSubdivisionCriterionSquareThreeTriangleD2 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr

    def Compute(self, mesh, edgeList):
        r"""
        Compute(self, mesh, edgeList)

        Parameters
        ----------
        mesh: itkQuadEdgeMeshD2 *
        edgeList: std::list< unsigned long,std::allocator< unsigned long > > &

        """
        return _itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionSquareThreeTriangleD2_Compute(self, mesh, edgeList)
    __swig_destroy__ = _itkQuadEdgeMeshSubdivisionCriterionPython.delete_itkQuadEdgeMeshSubdivisionCriterionSquareThreeTriangleD2

    @staticmethod
    def cast(obj):
        r"""
        cast(obj) -> itkQuadEdgeMeshSubdivisionCriterionSquareThreeTriangleD2

        Parameters
        ----------
        obj: itkLightObject *

        """
        return _itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionSquareThreeTriangleD2_cast(obj)

# Register itkQuadEdgeMeshSubdivisionCriterionSquareThreeTriangleD2 in _itkQuadEdgeMeshSubdivisionCriterionPython:
_itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionSquareThreeTriangleD2_swigregister(itkQuadEdgeMeshSubdivisionCriterionSquareThreeTriangleD2)
class itkQuadEdgeMeshSubdivisionCriterionSquareThreeTriangleD3(itk.ITKCommonBasePython.itkObject):
    r"""Proxy of C++ itkQuadEdgeMeshSubdivisionCriterionSquareThreeTriangleD3 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr

    def Compute(self, mesh, edgeList):
        r"""
        Compute(self, mesh, edgeList)

        Parameters
        ----------
        mesh: itkQuadEdgeMeshD3 *
        edgeList: std::list< unsigned long,std::allocator< unsigned long > > &

        """
        return _itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionSquareThreeTriangleD3_Compute(self, mesh, edgeList)
    __swig_destroy__ = _itkQuadEdgeMeshSubdivisionCriterionPython.delete_itkQuadEdgeMeshSubdivisionCriterionSquareThreeTriangleD3

    @staticmethod
    def cast(obj):
        r"""
        cast(obj) -> itkQuadEdgeMeshSubdivisionCriterionSquareThreeTriangleD3

        Parameters
        ----------
        obj: itkLightObject *

        """
        return _itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionSquareThreeTriangleD3_cast(obj)

# Register itkQuadEdgeMeshSubdivisionCriterionSquareThreeTriangleD3 in _itkQuadEdgeMeshSubdivisionCriterionPython:
_itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionSquareThreeTriangleD3_swigregister(itkQuadEdgeMeshSubdivisionCriterionSquareThreeTriangleD3)
class itkQuadEdgeMeshSubdivisionCriterionSquareThreeTriangleD4(itk.ITKCommonBasePython.itkObject):
    r"""Proxy of C++ itkQuadEdgeMeshSubdivisionCriterionSquareThreeTriangleD4 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr

    def Compute(self, mesh, edgeList):
        r"""
        Compute(self, mesh, edgeList)

        Parameters
        ----------
        mesh: itkQuadEdgeMeshD4 *
        edgeList: std::list< unsigned long,std::allocator< unsigned long > > &

        """
        return _itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionSquareThreeTriangleD4_Compute(self, mesh, edgeList)
    __swig_destroy__ = _itkQuadEdgeMeshSubdivisionCriterionPython.delete_itkQuadEdgeMeshSubdivisionCriterionSquareThreeTriangleD4

    @staticmethod
    def cast(obj):
        r"""
        cast(obj) -> itkQuadEdgeMeshSubdivisionCriterionSquareThreeTriangleD4

        Parameters
        ----------
        obj: itkLightObject *

        """
        return _itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionSquareThreeTriangleD4_cast(obj)

# Register itkQuadEdgeMeshSubdivisionCriterionSquareThreeTriangleD4 in _itkQuadEdgeMeshSubdivisionCriterionPython:
_itkQuadEdgeMeshSubdivisionCriterionPython.itkQuadEdgeMeshSubdivisionCriterionSquareThreeTriangleD4_swigregister(itkQuadEdgeMeshSubdivisionCriterionSquareThreeTriangleD4)

