import os


action: str = os.environ.get("GITHUB_ACTION", "")
action_ref: str = os.environ.get("GITHUB_ACTION_REF", "")
action_repository: str = os.environ.get("GITHUB_ACTION_REPOSITORY", "")
actions: str = os.environ.get("GITHUB_ACTIONS", "")
actor: str = os.environ.get("GITHUB_ACTOR", "")
actor_id: str = os.environ.get("GITHUB_ACTOR_ID", "")
api_url: str = os.environ.get("GITHUB_API_URL", "")
base_ref: str = os.environ.get("GITHUB_BASE_REF", "")
env: str = os.environ.get("GITHUB_ENV", "")
event_name: str = os.environ.get("GITHUB_EVENT_NAME", "")
event_path: str = os.environ.get("GITHUB_EVENT_PATH", "")
graphql_url: str = os.environ.get("GITHUB_GRAPHQL_URL", "")
head_ref: str = os.environ.get("GITHUB_HEAD_REF", "")
job: str = os.environ.get("GITHUB_JOB", "")
output: str = os.environ.get("GITHUB_OUTPUT", "")
path: str = os.environ.get("GITHUB_PATH", "")
ref: str = os.environ.get("GITHUB_REF", "")
ref_name: str = os.environ.get("GITHUB_REF_NAME", "")
ref_protected: str = os.environ.get("GITHUB_REF_PROTECTED", "")
ref_type: str = os.environ.get("GITHUB_REF_TYPE", "")
repository: str = os.environ.get("GITHUB_REPOSITORY", "")
repository_id: str = os.environ.get("GITHUB_REPOSITORY_ID", "")
repository_owner: str = os.environ.get("GITHUB_REPOSITORY_OWNER", "")
repository_owner_id: str = os.environ.get("GITHUB_REPOSITORY_OWNER_ID", "")
retention_days: str = os.environ.get("GITHUB_RETENTION_DAYS", "")
run_attempt: str = os.environ.get("GITHUB_RUN_ATTEMPT", "")
run_id: str = os.environ.get("GITHUB_RUN_ID", "")
run_number: str = os.environ.get("GITHUB_RUN_NUMBER", "")
server_url: str = os.environ.get("GITHUB_SERVER_URL", "")
sha: str = os.environ.get("GITHUB_SHA", "")
step_summary: str = os.environ.get("GITHUB_STEP_SUMMARY", "")
triggering_actor: str = os.environ.get("GITHUB_TRIGGERING_ACTOR", "")
workflow: str = os.environ.get("GITHUB_WORKFLOW", "")
workflow_ref: str = os.environ.get("GITHUB_WORKFLOW_REF", "")
workflow_sha: str = os.environ.get("GITHUB_WORKFLOW_SHA", "")
workspace: str = os.environ.get("GITHUB_WORKSPACE", "")

runner_arch: str = os.environ.get("RUNNER_ARCH", "")
runner_debug: str = os.environ.get("RUNNER_DEBUG", "")
runner_environment: str = os.environ.get("RUNNER_ENVIRONMENT", "")
runner_name: str = os.environ.get("RUNNER_NAME", "")
runner_os: str = os.environ.get("RUNNER_OS", "")
runner_temp: str = os.environ.get("RUNNER_TEMP", "")
runner_tool_cache: str = os.environ.get("RUNNER_TOOL_CACHE", "")


repository_name: str = os.environ.get("GITHUB_REPOSITORY", "/").split("/")[1]
