# coding: utf-8

"""
    ai/h2o/mlops/batch/v1/job.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from _h2o_mlops_client.batch.configuration import Configuration


class V1Sink(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'spec': 'str',
        'config': 'str',
        'location': 'str',
        'mime_type': 'str'
    }

    attribute_map = {
        'spec': 'spec',
        'config': 'config',
        'location': 'location',
        'mime_type': 'mimeType'
    }

    def __init__(self, spec=None, config=None, location=None, mime_type=None, local_vars_configuration=None):  # noqa: E501
        """V1Sink - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._spec = None
        self._config = None
        self._location = None
        self._mime_type = None
        self.discriminator = None

        self.spec = spec
        self.config = config
        self.location = location
        if mime_type is not None:
            self.mime_type = mime_type

    @property
    def spec(self):
        """Gets the spec of this V1Sink.  # noqa: E501

        Required. Reference to the SinkSpec resource that defines the sink type and capabilities (e.g., file system, database, cloud storage). Cannot be changed after the sink is created.  # noqa: E501

        :return: The spec of this V1Sink.  # noqa: E501
        :rtype: str
        """
        return self._spec

    @spec.setter
    def spec(self, spec):
        """Sets the spec of this V1Sink.

        Required. Reference to the SinkSpec resource that defines the sink type and capabilities (e.g., file system, database, cloud storage). Cannot be changed after the sink is created.  # noqa: E501

        :param spec: The spec of this V1Sink.  # noqa: E501
        :type spec: str
        """
        if self.local_vars_configuration.client_side_validation and spec is None:  # noqa: E501
            raise ValueError("Invalid value for `spec`, must not be `None`")  # noqa: E501

        self._spec = spec

    @property
    def config(self):
        """Gets the config of this V1Sink.  # noqa: E501

        Required. Configuration parameters specific to the sink type, such as connection strings, authentication details, or format specifications. Cannot be modified after the sink is created.  # noqa: E501

        :return: The config of this V1Sink.  # noqa: E501
        :rtype: str
        """
        return self._config

    @config.setter
    def config(self, config):
        """Sets the config of this V1Sink.

        Required. Configuration parameters specific to the sink type, such as connection strings, authentication details, or format specifications. Cannot be modified after the sink is created.  # noqa: E501

        :param config: The config of this V1Sink.  # noqa: E501
        :type config: str
        """
        if self.local_vars_configuration.client_side_validation and config is None:  # noqa: E501
            raise ValueError("Invalid value for `config`, must not be `None`")  # noqa: E501

        self._config = config

    @property
    def location(self):
        """Gets the location of this V1Sink.  # noqa: E501

        Required. The target location or path where data will be written, such as a file path, database table name, or cloud storage URI. Cannot be changed after the sink is created.  # noqa: E501

        :return: The location of this V1Sink.  # noqa: E501
        :rtype: str
        """
        return self._location

    @location.setter
    def location(self, location):
        """Sets the location of this V1Sink.

        Required. The target location or path where data will be written, such as a file path, database table name, or cloud storage URI. Cannot be changed after the sink is created.  # noqa: E501

        :param location: The location of this V1Sink.  # noqa: E501
        :type location: str
        """
        if self.local_vars_configuration.client_side_validation and location is None:  # noqa: E501
            raise ValueError("Invalid value for `location`, must not be `None`")  # noqa: E501

        self._location = location

    @property
    def mime_type(self):
        """Gets the mime_type of this V1Sink.  # noqa: E501

        Specifies the mime type for file-based sinks. This value determines the format used when writing data to the output files. Common mime types include: - text/csv: For CSV (Comma-Separated Values) format, used for structured tabular data. - application/jsonl: For JSON Lines (newline-delimited JSON) format, where each line is a separate JSON object. - application/json: For standard JSON format, used for structured data in a hierarchical or nested structure.  Specifying the correct mime type is essential to ensure data is output in the desired format. If not specified, the system may apply a default format that may not meet expectations.  # noqa: E501

        :return: The mime_type of this V1Sink.  # noqa: E501
        :rtype: str
        """
        return self._mime_type

    @mime_type.setter
    def mime_type(self, mime_type):
        """Sets the mime_type of this V1Sink.

        Specifies the mime type for file-based sinks. This value determines the format used when writing data to the output files. Common mime types include: - text/csv: For CSV (Comma-Separated Values) format, used for structured tabular data. - application/jsonl: For JSON Lines (newline-delimited JSON) format, where each line is a separate JSON object. - application/json: For standard JSON format, used for structured data in a hierarchical or nested structure.  Specifying the correct mime type is essential to ensure data is output in the desired format. If not specified, the system may apply a default format that may not meet expectations.  # noqa: E501

        :param mime_type: The mime_type of this V1Sink.  # noqa: E501
        :type mime_type: str
        """

        self._mime_type = mime_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1Sink):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V1Sink):
            return True

        return self.to_dict() != other.to_dict()
