# Auto-generated from responses_api.py
# Model: InputFileContentParam

# generated by datamodel-codegen:
#   filename:  filtered_openapi.yaml
#   timestamp: 2025-10-18T15:02:20+00:00


from typing import Annotated, Literal, Optional

from pydantic import BaseModel, Field


class InputFileContentParam(BaseModel):
    type: Literal["InputFileContentParam"] = Field(
        ..., description="The type of the input item. Always `input_file`."
    )
    file_id: Optional[str] = None
    filename: Optional[str] = None
    file_data: Optional[Annotated[str, Field(max_length=33554432)]] = None
    file_url: Optional[str] = None
