"""Type stubs for airpine_builder - enables full IDE autocomplete."""

from typing import Any

class RawJS(str):
    """Raw JavaScript expression marker."""
    ...

class _AlpineAttr:
    """Alpine directive builder with chainable modifiers."""
    
    prefix: str
    base: str
    mods: tuple[str, ...]
    
    def __call__(self, value: Any) -> dict[str, str]: ...
    def mod(self, *modifiers: str) -> _AlpineAttr: ...
    
    # Time-based modifiers
    def debounce(self, ms: int | None = ...) -> _AlpineAttr: ...
    def throttle(self, ms: int | None = ...) -> _AlpineAttr: ...
    
    # Event modifiers
    @property
    def prevent(self) -> _AlpineAttr: ...
    @property
    def stop(self) -> _AlpineAttr: ...
    @property
    def once(self) -> _AlpineAttr: ...
    @property
    def self(self) -> _AlpineAttr: ...
    @property
    def window(self) -> _AlpineAttr: ...
    @property
    def document(self) -> _AlpineAttr: ...
    @property
    def outside(self) -> _AlpineAttr: ...
    @property
    def away(self) -> _AlpineAttr: ...
    @property
    def passive(self) -> _AlpineAttr: ...
    @property
    def capture(self) -> _AlpineAttr: ...
    
    # Keyboard modifiers
    @property
    def enter(self) -> _AlpineAttr: ...
    @property
    def escape(self) -> _AlpineAttr: ...
    @property
    def space(self) -> _AlpineAttr: ...
    @property
    def tab(self) -> _AlpineAttr: ...
    @property
    def up(self) -> _AlpineAttr: ...
    @property
    def down(self) -> _AlpineAttr: ...
    @property
    def left(self) -> _AlpineAttr: ...
    @property
    def right(self) -> _AlpineAttr: ...
    @property
    def shift(self) -> _AlpineAttr: ...
    @property
    def ctrl(self) -> _AlpineAttr: ...
    @property
    def alt(self) -> _AlpineAttr: ...
    @property
    def meta(self) -> _AlpineAttr: ...
    @property
    def cmd(self) -> _AlpineAttr: ...
    @property
    def backspace(self) -> _AlpineAttr: ...
    @property
    def delete(self) -> _AlpineAttr: ...
    @property
    def home(self) -> _AlpineAttr: ...
    @property
    def end(self) -> _AlpineAttr: ...
    @property
    def page_up(self) -> _AlpineAttr: ...
    @property
    def page_down(self) -> _AlpineAttr: ...
    
    def key(self, name: str) -> _AlpineAttr: ...

class _EventNamespace:
    """Event handlers (@click, @submit, etc.)."""
    
    # DOM Events
    @property
    def click(self) -> _AlpineAttr: ...
    @property
    def dblclick(self) -> _AlpineAttr: ...
    @property
    def input(self) -> _AlpineAttr: ...
    @property
    def change(self) -> _AlpineAttr: ...
    @property
    def submit(self) -> _AlpineAttr: ...
    @property
    def keydown(self) -> _AlpineAttr: ...
    @property
    def keyup(self) -> _AlpineAttr: ...
    @property
    def keypress(self) -> _AlpineAttr: ...
    @property
    def focus(self) -> _AlpineAttr: ...
    @property
    def blur(self) -> _AlpineAttr: ...
    @property
    def mouseenter(self) -> _AlpineAttr: ...
    @property
    def mouseleave(self) -> _AlpineAttr: ...
    @property
    def mouseover(self) -> _AlpineAttr: ...
    @property
    def mouseout(self) -> _AlpineAttr: ...
    @property
    def scroll(self) -> _AlpineAttr: ...
    @property
    def resize(self) -> _AlpineAttr: ...
    @property
    def load(self) -> _AlpineAttr: ...
    
    def __getattr__(self, name: str) -> _AlpineAttr: ...
    def __getitem__(self, event_name: str) -> _AlpineAttr: ...

class _BindNamespace:
    """Attribute binding (x-bind:class, x-bind:style, etc.)."""
    
    @property
    def class_(self) -> _AlpineAttr: ...
    @property
    def style(self) -> _AlpineAttr: ...
    @property
    def href(self) -> _AlpineAttr: ...
    @property
    def src(self) -> _AlpineAttr: ...
    @property
    def value(self) -> _AlpineAttr: ...
    @property
    def disabled(self) -> _AlpineAttr: ...
    @property
    def checked(self) -> _AlpineAttr: ...
    @property
    def selected(self) -> _AlpineAttr: ...
    @property
    def readonly(self) -> _AlpineAttr: ...
    
    def __getattr__(self, name: str) -> _AlpineAttr: ...
    def __getitem__(self, attr_name: str) -> _AlpineAttr: ...

class _ModelNamespace:
    """Two-way binding (x-model)."""
    
    def __call__(self, expr: str) -> dict[str, str]: ...
    
    @property
    def number(self) -> _AlpineAttr: ...
    @property
    def lazy(self) -> _AlpineAttr: ...
    @property
    def trim(self) -> _AlpineAttr: ...
    @property
    def boolean(self) -> _AlpineAttr: ...
    @property
    def fill(self) -> _AlpineAttr: ...
    
    def debounce(self, ms: int | None = ...) -> _AlpineAttr: ...
    def throttle(self, ms: int | None = ...) -> _AlpineAttr: ...

class _TransitionNamespace:
    """Transitions (x-transition)."""
    
    def __call__(self, expr: str = ...) -> dict[str, str]: ...
    
    @property
    def enter(self) -> _AlpineAttr: ...
    @property
    def enter_start(self) -> _AlpineAttr: ...
    @property
    def enter_end(self) -> _AlpineAttr: ...
    @property
    def leave(self) -> _AlpineAttr: ...
    @property
    def leave_start(self) -> _AlpineAttr: ...
    @property
    def leave_end(self) -> _AlpineAttr: ...

class _DirectiveNamespace:
    """Alpine directives (x-data, x-show, etc.) in official Alpine.js order."""
    
    # Official directives in order
    def data(self, expr: str | dict[str, Any]) -> dict[str, str]: ...
    def init(self, expr: str) -> dict[str, str]: ...
    def show(self, expr: str) -> dict[str, str]: ...
    
    @property
    def bind(self) -> _BindNamespace: ...
    @property
    def on(self) -> _EventNamespace: ...
    
    def text(self, expr: str) -> dict[str, str]: ...
    def html(self, expr: str) -> dict[str, str]: ...
    
    @property
    def model(self) -> _ModelNamespace: ...
    
    def modelable(self, expr: str) -> dict[str, str]: ...
    def for_(self, expr: str) -> dict[str, str]: ...
    
    @property
    def transition(self) -> _TransitionNamespace: ...
    
    def effect(self, expr: str) -> dict[str, str]: ...
    def ignore(self) -> dict[str, str]: ...
    def ref(self, name: str) -> dict[str, str]: ...
    def cloak(self) -> dict[str, str]: ...
    def teleport(self, target: str) -> dict[str, str]: ...
    def if_(self, expr: str) -> dict[str, str]: ...
    def id(self, expr: str | list[str]) -> dict[str, str]: ...
    def key(self, expr: str) -> dict[str, str]: ...

class AlpineBuilder:
    """Main Alpine builder with event and directive namespaces."""
    
    at: _EventNamespace
    x: _DirectiveNamespace
    
    @staticmethod
    def merge(*dicts: dict[str, str]) -> dict[str, str]: ...

Alpine: AlpineBuilder
