use rusttype::Font;
use std::sync::LazyLock;

pub const FONTS: LazyLock<[Font; 59]> = LazyLock::new(|| {
    [
        // core noto fonts
        Font::try_from_bytes(include_bytes!("../../fonts/DejaVuSans.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../../fonts/NotoSansDisplay-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../../fonts/NotoSansSC-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../../fonts/NotoSans-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../../fonts/NotoSansMath-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../../fonts/NotoEmoji-Regular.ttf")).unwrap(),
        // extra noto fonts
        Font::try_from_bytes(include_bytes!("../../fonts/NotoSansKR-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../../fonts/NotoSansArmenian-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../../fonts/NotoSansJP-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../../fonts/NotoSansAvestan-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../../fonts/NotoSansBengali-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!(
            "../../fonts/NotoSansBengaliUI-Regular.ttf"
        ))
        .unwrap(),
        Font::try_from_bytes(include_bytes!("../../fonts/NotoSansBrahmi-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../../fonts/NotoSansCarian-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../../fonts/NotoSansCherokee-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../../fonts/NotoSansCoptic-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../../fonts/NotoSansDeseret-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!(
            "../../fonts/NotoSansDevanagari-Regular.ttf"
        ))
        .unwrap(),
        Font::try_from_bytes(include_bytes!(
            "../../fonts/NotoSansDevanagariUI-Regular.ttf"
        ))
        .unwrap(),
        Font::try_from_bytes(include_bytes!(
            "../../fonts/NotoSansEgyptianHieroglyphs-Regular.ttf"
        ))
        .unwrap(),
        Font::try_from_bytes(include_bytes!("../../fonts/NotoSansEthiopic-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../../fonts/NotoSansGeorgian-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!(
            "../../fonts/NotoSansGlagolitic-Regular.ttf"
        ))
        .unwrap(),
        Font::try_from_bytes(include_bytes!("../../fonts/NotoSansGujarati-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!(
            "../../fonts/NotoSansGujaratiUI-Regular.ttf"
        ))
        .unwrap(),
        Font::try_from_bytes(include_bytes!("../../fonts/NotoSansGurmukhi-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../../fonts/NotoSansHebrew-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!(
            "../../fonts/NotoSansImperialAramaic-Regular.ttf"
        ))
        .unwrap(),
        Font::try_from_bytes(include_bytes!("../../fonts/NotoSansKayahLi-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../../fonts/NotoSansKaithi-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../../fonts/NotoSansKannada-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!(
            "../../fonts/NotoSansKannadaUI-Regular.ttf"
        ))
        .unwrap(),
        Font::try_from_bytes(include_bytes!(
            "../../fonts/NotoSansKharoshthi-Regular.ttf"
        ))
        .unwrap(),
        Font::try_from_bytes(include_bytes!("../../fonts/NotoSansKhmer-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../../fonts/NotoSansKhmerUI-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../../fonts/NotoSansLao-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../../fonts/NotoSansLaoUI-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../../fonts/NotoSansLycian-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../../fonts/NotoSansLydian-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!(
            "../../fonts/NotoSansMalayalam-Regular.ttf"
        ))
        .unwrap(),
        Font::try_from_bytes(include_bytes!(
            "../../fonts/NotoSansMalayalamUI-Regular.ttf"
        ))
        .unwrap(),
        Font::try_from_bytes(include_bytes!("../../fonts/NotoSansMono-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../../fonts/NotoSansNKo-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!(
            "../../fonts/NotoSansOldSouthArabian-Regular.ttf"
        ))
        .unwrap(),
        Font::try_from_bytes(include_bytes!(
            "../../fonts/NotoSansOldTurkic-Regular.ttf"
        ))
        .unwrap(),
        Font::try_from_bytes(include_bytes!("../../fonts/NotoSansOsmanya-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!(
            "../../fonts/NotoSansPhoenician-Regular.ttf"
        ))
        .unwrap(),
        Font::try_from_bytes(include_bytes!("../../fonts/NotoSansShavian-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../../fonts/NotoSansSinhala-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../../fonts/NotoSansSymbols-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../../fonts/NotoSansTamil-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../../fonts/NotoSansTamilUI-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../../fonts/NotoSansTelugu-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../../fonts/NotoSansTeluguUI-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../../fonts/NotoSansThaana-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../../fonts/NotoSansThai-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../../fonts/NotoSansThaiUI-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../../fonts/NotoSansUgaritic-Regular.ttf")).unwrap(),
        Font::try_from_bytes(include_bytes!("../../fonts/NotoSansVai-Regular.ttf")).unwrap(),
    ]
});
