from contextlib import contextmanager
from dataclasses import dataclass
from typing import Iterator

__all__ = ["MathFeatureFlags", "get_flags", "context_flags"]

@dataclass(frozen=True)
class MathFeatureFlags:
    enable_math_validation: bool = ...
    enable_math_dynamics: bool = ...
    log_performance: bool = ...
    math_backend: str = ...

def get_flags() -> MathFeatureFlags: ...
@contextmanager
def context_flags(**overrides: bool) -> Iterator[MathFeatureFlags]: ...
