# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .create_phone_numbers_request import CreatePhoneNumbersRequest
    from .create_phone_numbers_response import CreatePhoneNumbersResponse
    from .delete_phone_numbers_response import DeletePhoneNumbersResponse
    from .get_phone_numbers_response import GetPhoneNumbersResponse
    from .list_phone_numbers_response_item import ListPhoneNumbersResponseItem
    from .phone_number_controller_find_all_paginated_request_sort_order import (
        PhoneNumberControllerFindAllPaginatedRequestSortOrder,
    )
    from .update_phone_numbers_request_body import UpdatePhoneNumbersRequestBody
    from .update_phone_numbers_response import UpdatePhoneNumbersResponse
_dynamic_imports: typing.Dict[str, str] = {
    "CreatePhoneNumbersRequest": ".create_phone_numbers_request",
    "CreatePhoneNumbersResponse": ".create_phone_numbers_response",
    "DeletePhoneNumbersResponse": ".delete_phone_numbers_response",
    "GetPhoneNumbersResponse": ".get_phone_numbers_response",
    "ListPhoneNumbersResponseItem": ".list_phone_numbers_response_item",
    "PhoneNumberControllerFindAllPaginatedRequestSortOrder": ".phone_number_controller_find_all_paginated_request_sort_order",
    "UpdatePhoneNumbersRequestBody": ".update_phone_numbers_request_body",
    "UpdatePhoneNumbersResponse": ".update_phone_numbers_response",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CreatePhoneNumbersRequest",
    "CreatePhoneNumbersResponse",
    "DeletePhoneNumbersResponse",
    "GetPhoneNumbersResponse",
    "ListPhoneNumbersResponseItem",
    "PhoneNumberControllerFindAllPaginatedRequestSortOrder",
    "UpdatePhoneNumbersRequestBody",
    "UpdatePhoneNumbersResponse",
]
