from .admissionregistration_v1_service_reference import (
    AdmissionregistrationV1ServiceReference,
)
from .admissionregistration_v1_webhook_client_config import (
    AdmissionregistrationV1WebhookClientConfig,
)
from .apiextensions_v1_service_reference import ApiextensionsV1ServiceReference
from .apiextensions_v1_webhook_client_config import ApiextensionsV1WebhookClientConfig
from .apiregistration_v1_service_reference import ApiregistrationV1ServiceReference
from .v1_object_meta import V1ObjectMeta
from .v1_token_request_status import V1TokenRequestStatus
from .authentication_v1_token_request import AuthenticationV1TokenRequest
from .core_v1_endpoint_port import CoreV1EndpointPort
from .v1_object_reference import V1ObjectReference
from .core_v1_event_series import CoreV1EventSeries
from .v1_event_source import V1EventSource
from .core_v1_event import CoreV1Event
from .v1_list_meta import V1ListMeta
from .core_v1_event_list import CoreV1EventList
from .core_v1_resource_claim import CoreV1ResourceClaim
from .discovery_v1_endpoint_port import DiscoveryV1EndpointPort
from .events_v1_event_series import EventsV1EventSeries
from .events_v1_event import EventsV1Event
from .events_v1_event_list import EventsV1EventList
from .v1_group_subject import V1GroupSubject
from .v1_service_account_subject import V1ServiceAccountSubject
from .v1_user_subject import V1UserSubject
from .flowcontrol_v1_subject import FlowcontrolV1Subject
from .rbac_v1_subject import RbacV1Subject
from .v1_device_allocation_result import V1DeviceAllocationResult
from .v1_node_selector import V1NodeSelector
from .v1_allocation_result import V1AllocationResult
from .v1_resource_claim_status import V1ResourceClaimStatus
from .resource_v1_resource_claim import ResourceV1ResourceClaim
from .storage_v1_token_request import StorageV1TokenRequest
from .v1_group_version_for_discovery import V1GroupVersionForDiscovery
from .v1_api_group import V1APIGroup
from .v1_api_group_list import V1APIGroupList
from .v1_api_resource import V1APIResource
from .v1_api_resource_list import V1APIResourceList
from .v1_api_service_spec import V1APIServiceSpec
from .v1_api_service_status import V1APIServiceStatus
from .v1_api_service import V1APIService
from .v1_api_service_condition import V1APIServiceCondition
from .v1_api_service_list import V1APIServiceList
from .v1_api_versions import V1APIVersions
from .v1_aws_elastic_block_store_volume_source import V1AWSElasticBlockStoreVolumeSource
from .v1_node_affinity import V1NodeAffinity
from .v1_pod_affinity import V1PodAffinity
from .v1_pod_anti_affinity import V1PodAntiAffinity
from .v1_affinity import V1Affinity
from .v1_aggregation_rule import V1AggregationRule
from .v1_network_device_data import V1NetworkDeviceData
from .v1_allocated_device_status import V1AllocatedDeviceStatus
from .v1_app_armor_profile import V1AppArmorProfile
from .v1_attached_volume import V1AttachedVolume
from .v1_audit_annotation import V1AuditAnnotation
from .v1_azure_disk_volume_source import V1AzureDiskVolumeSource
from .v1_azure_file_persistent_volume_source import V1AzureFilePersistentVolumeSource
from .v1_azure_file_volume_source import V1AzureFileVolumeSource
from .v1_binding import V1Binding
from .v1_bound_object_reference import V1BoundObjectReference
from .v1_cel_device_selector import V1CELDeviceSelector
from .v1_csi_driver import V1CSIDriver
from .v1_csi_driver_list import V1CSIDriverList
from .v1_csi_driver_spec import V1CSIDriverSpec
from .v1_csi_node import V1CSINode
from .v1_volume_node_resources import V1VolumeNodeResources
from .v1_csi_node_driver import V1CSINodeDriver
from .v1_csi_node_list import V1CSINodeList
from .v1_csi_node_spec import V1CSINodeSpec
from .v1_secret_reference import V1SecretReference
from .v1_csi_persistent_volume_source import V1CSIPersistentVolumeSource
from .v1_label_selector import V1LabelSelector
from .v1_csi_storage_capacity import V1CSIStorageCapacity
from .v1_csi_storage_capacity_list import V1CSIStorageCapacityList
from .v1_local_object_reference import V1LocalObjectReference
from .v1_csi_volume_source import V1CSIVolumeSource
from .v1_capabilities import V1Capabilities
from .v1_capacity_request_policy_range import V1CapacityRequestPolicyRange
from .v1_capacity_request_policy import V1CapacityRequestPolicy
from .v1_capacity_requirements import V1CapacityRequirements
from .v1_ceph_fs_persistent_volume_source import V1CephFSPersistentVolumeSource
from .v1_ceph_fs_volume_source import V1CephFSVolumeSource
from .v1_certificate_signing_request_status import V1CertificateSigningRequestStatus
from .v1_certificate_signing_request import V1CertificateSigningRequest
from .v1_certificate_signing_request_condition import (
    V1CertificateSigningRequestCondition,
)
from .v1_certificate_signing_request_list import V1CertificateSigningRequestList
from .v1_certificate_signing_request_spec import V1CertificateSigningRequestSpec
from .v1_cinder_persistent_volume_source import V1CinderPersistentVolumeSource
from .v1_cinder_volume_source import V1CinderVolumeSource
from .v1_client_ip_config import V1ClientIPConfig
from .v1_cluster_role import V1ClusterRole
from .v1_cluster_role_binding import V1ClusterRoleBinding
from .v1_cluster_role_binding_list import V1ClusterRoleBindingList
from .v1_cluster_role_list import V1ClusterRoleList
from .v1_cluster_trust_bundle_projection import V1ClusterTrustBundleProjection
from .v1_component_condition import V1ComponentCondition
from .v1_component_status import V1ComponentStatus
from .v1_component_status_list import V1ComponentStatusList
from .v1_condition import V1Condition
from .v1_config_map import V1ConfigMap
from .v1_config_map_env_source import V1ConfigMapEnvSource
from .v1_config_map_key_selector import V1ConfigMapKeySelector
from .v1_config_map_list import V1ConfigMapList
from .v1_config_map_node_config_source import V1ConfigMapNodeConfigSource
from .v1_config_map_projection import V1ConfigMapProjection
from .v1_config_map_volume_source import V1ConfigMapVolumeSource
from .v1_exec_action import V1ExecAction
from .v1_http_get_action import V1HTTPGetAction
from .v1_sleep_action import V1SleepAction
from .v1_tcp_socket_action import V1TCPSocketAction
from .v1_lifecycle_handler import V1LifecycleHandler
from .v1_lifecycle import V1Lifecycle
from .v1_grpc_action import V1GRPCAction
from .v1_probe import V1Probe
from .v1_resource_requirements import V1ResourceRequirements
from .v1_se_linux_options import V1SELinuxOptions
from .v1_seccomp_profile import V1SeccompProfile
from .v1_windows_security_context_options import V1WindowsSecurityContextOptions
from .v1_security_context import V1SecurityContext
from .v1_container import V1Container
from .v1_container_extended_resource_request import V1ContainerExtendedResourceRequest
from .v1_container_image import V1ContainerImage
from .v1_container_port import V1ContainerPort
from .v1_container_resize_policy import V1ContainerResizePolicy
from .v1_container_restart_rule_on_exit_codes import V1ContainerRestartRuleOnExitCodes
from .v1_container_restart_rule import V1ContainerRestartRule
from .v1_container_state_running import V1ContainerStateRunning
from .v1_container_state_terminated import V1ContainerStateTerminated
from .v1_container_state_waiting import V1ContainerStateWaiting
from .v1_container_state import V1ContainerState
from .v1_linux_container_user import V1LinuxContainerUser
from .v1_container_user import V1ContainerUser
from .v1_container_status import V1ContainerStatus
from .v1_controller_revision import V1ControllerRevision
from .v1_controller_revision_list import V1ControllerRevisionList
from .v1_counter import V1Counter
from .v1_counter_set import V1CounterSet
from .v1_cron_job_spec import V1CronJobSpec
from .v1_cron_job_status import V1CronJobStatus
from .v1_cron_job import V1CronJob
from .v1_cron_job_list import V1CronJobList
from .v1_cross_version_object_reference import V1CrossVersionObjectReference
from .v1_custom_resource_column_definition import V1CustomResourceColumnDefinition
from .v1_webhook_conversion import V1WebhookConversion
from .v1_custom_resource_conversion import V1CustomResourceConversion
from .v1_custom_resource_definition_names import V1CustomResourceDefinitionNames
from .v1_custom_resource_definition_status import V1CustomResourceDefinitionStatus
from .v1_custom_resource_definition import V1CustomResourceDefinition
from .v1_custom_resource_definition_condition import V1CustomResourceDefinitionCondition
from .v1_custom_resource_definition_list import V1CustomResourceDefinitionList
from .v1_custom_resource_definition_spec import V1CustomResourceDefinitionSpec
from .v1_external_documentation import V1ExternalDocumentation
from .v1_json_schema_props import V1JSONSchemaProps
from .v1_custom_resource_validation import V1CustomResourceValidation
from .v1_custom_resource_subresource_scale import V1CustomResourceSubresourceScale
from .v1_custom_resource_subresources import V1CustomResourceSubresources
from .v1_custom_resource_definition_version import V1CustomResourceDefinitionVersion
from .v1_daemon_endpoint import V1DaemonEndpoint
from .v1_rolling_update_daemon_set import V1RollingUpdateDaemonSet
from .v1_daemon_set_update_strategy import V1DaemonSetUpdateStrategy
from .v1_daemon_set_spec import V1DaemonSetSpec
from .v1_daemon_set_status import V1DaemonSetStatus
from .v1_daemon_set import V1DaemonSet
from .v1_daemon_set_condition import V1DaemonSetCondition
from .v1_daemon_set_list import V1DaemonSetList
from .v1_preconditions import V1Preconditions
from .v1_delete_options import V1DeleteOptions
from .v1_rolling_update_deployment import V1RollingUpdateDeployment
from .v1_deployment_strategy import V1DeploymentStrategy
from .v1_deployment_spec import V1DeploymentSpec
from .v1_deployment_status import V1DeploymentStatus
from .v1_deployment import V1Deployment
from .v1_deployment_condition import V1DeploymentCondition
from .v1_deployment_list import V1DeploymentList
from .v1_device import V1Device
from .v1_opaque_device_configuration import V1OpaqueDeviceConfiguration
from .v1_device_allocation_configuration import V1DeviceAllocationConfiguration
from .v1_device_attribute import V1DeviceAttribute
from .v1_device_capacity import V1DeviceCapacity
from .v1_device_claim import V1DeviceClaim
from .v1_device_claim_configuration import V1DeviceClaimConfiguration
from .v1_device_class import V1DeviceClass
from .v1_device_class_configuration import V1DeviceClassConfiguration
from .v1_device_class_list import V1DeviceClassList
from .v1_device_class_spec import V1DeviceClassSpec
from .v1_device_constraint import V1DeviceConstraint
from .v1_device_counter_consumption import V1DeviceCounterConsumption
from .v1_exact_device_request import V1ExactDeviceRequest
from .v1_device_request import V1DeviceRequest
from .v1_device_request_allocation_result import V1DeviceRequestAllocationResult
from .v1_device_selector import V1DeviceSelector
from .v1_device_sub_request import V1DeviceSubRequest
from .v1_device_taint import V1DeviceTaint
from .v1_device_toleration import V1DeviceToleration
from .v1_downward_api_projection import V1DownwardAPIProjection
from .v1_object_field_selector import V1ObjectFieldSelector
from .v1_resource_field_selector import V1ResourceFieldSelector
from .v1_downward_api_volume_file import V1DownwardAPIVolumeFile
from .v1_downward_api_volume_source import V1DownwardAPIVolumeSource
from .v1_empty_dir_volume_source import V1EmptyDirVolumeSource
from .v1_endpoint_conditions import V1EndpointConditions
from .v1_endpoint_hints import V1EndpointHints
from .v1_endpoint import V1Endpoint
from .v1_endpoint_address import V1EndpointAddress
from .v1_endpoint_slice import V1EndpointSlice
from .v1_endpoint_slice_list import V1EndpointSliceList
from .v1_endpoint_subset import V1EndpointSubset
from .v1_endpoints import V1Endpoints
from .v1_endpoints_list import V1EndpointsList
from .v1_secret_env_source import V1SecretEnvSource
from .v1_env_from_source import V1EnvFromSource
from .v1_file_key_selector import V1FileKeySelector
from .v1_secret_key_selector import V1SecretKeySelector
from .v1_env_var_source import V1EnvVarSource
from .v1_env_var import V1EnvVar
from .v1_ephemeral_container import V1EphemeralContainer
from .v1_persistent_volume_claim_template import V1PersistentVolumeClaimTemplate
from .v1_ephemeral_volume_source import V1EphemeralVolumeSource
from .v1_eviction import V1Eviction
from .v1_exempt_priority_level_configuration import V1ExemptPriorityLevelConfiguration
from .v1_expression_warning import V1ExpressionWarning
from .v1_fc_volume_source import V1FCVolumeSource
from .v1_field_selector_attributes import V1FieldSelectorAttributes
from .v1_field_selector_requirement import V1FieldSelectorRequirement
from .v1_flex_persistent_volume_source import V1FlexPersistentVolumeSource
from .v1_flex_volume_source import V1FlexVolumeSource
from .v1_flocker_volume_source import V1FlockerVolumeSource
from .v1_flow_distinguisher_method import V1FlowDistinguisherMethod
from .v1_flow_schema_spec import V1FlowSchemaSpec
from .v1_flow_schema_status import V1FlowSchemaStatus
from .v1_flow_schema import V1FlowSchema
from .v1_flow_schema_condition import V1FlowSchemaCondition
from .v1_flow_schema_list import V1FlowSchemaList
from .v1_for_node import V1ForNode
from .v1_for_zone import V1ForZone
from .v1_gce_persistent_disk_volume_source import V1GCEPersistentDiskVolumeSource
from .v1_git_repo_volume_source import V1GitRepoVolumeSource
from .v1_glusterfs_persistent_volume_source import V1GlusterfsPersistentVolumeSource
from .v1_glusterfs_volume_source import V1GlusterfsVolumeSource
from .v1_http_header import V1HTTPHeader
from .v1_http_ingress_path import V1HTTPIngressPath
from .v1_http_ingress_rule_value import V1HTTPIngressRuleValue
from .v1_horizontal_pod_autoscaler_spec import V1HorizontalPodAutoscalerSpec
from .v1_horizontal_pod_autoscaler_status import V1HorizontalPodAutoscalerStatus
from .v1_horizontal_pod_autoscaler import V1HorizontalPodAutoscaler
from .v1_horizontal_pod_autoscaler_list import V1HorizontalPodAutoscalerList
from .v1_host_alias import V1HostAlias
from .v1_host_ip import V1HostIP
from .v1_host_path_volume_source import V1HostPathVolumeSource
from .v1_ip_address_spec import V1IPAddressSpec
from .v1_ip_address import V1IPAddress
from .v1_ip_address_list import V1IPAddressList
from .v1_ip_block import V1IPBlock
from .v1_iscsi_persistent_volume_source import V1ISCSIPersistentVolumeSource
from .v1_iscsi_volume_source import V1ISCSIVolumeSource
from .v1_image_volume_source import V1ImageVolumeSource
from .v1_typed_local_object_reference import V1TypedLocalObjectReference
from .v1_service_backend_port import V1ServiceBackendPort
from .v1_ingress_service_backend import V1IngressServiceBackend
from .v1_ingress_backend import V1IngressBackend
from .v1_ingress_spec import V1IngressSpec
from .v1_ingress_load_balancer_status import V1IngressLoadBalancerStatus
from .v1_ingress_status import V1IngressStatus
from .v1_ingress import V1Ingress
from .v1_ingress_class_parameters_reference import V1IngressClassParametersReference
from .v1_ingress_class_spec import V1IngressClassSpec
from .v1_ingress_class import V1IngressClass
from .v1_ingress_class_list import V1IngressClassList
from .v1_ingress_list import V1IngressList
from .v1_ingress_load_balancer_ingress import V1IngressLoadBalancerIngress
from .v1_ingress_port_status import V1IngressPortStatus
from .v1_ingress_rule import V1IngressRule
from .v1_ingress_tls import V1IngressTLS
from .v1_pod_failure_policy import V1PodFailurePolicy
from .v1_success_policy import V1SuccessPolicy
from .v1_job_spec import V1JobSpec
from .v1_uncounted_terminated_pods import V1UncountedTerminatedPods
from .v1_job_status import V1JobStatus
from .v1_job import V1Job
from .v1_job_condition import V1JobCondition
from .v1_job_list import V1JobList
from .v1_job_template_spec import V1JobTemplateSpec
from .v1_key_to_path import V1KeyToPath
from .v1_label_selector_attributes import V1LabelSelectorAttributes
from .v1_label_selector_requirement import V1LabelSelectorRequirement
from .v1_lease_spec import V1LeaseSpec
from .v1_lease import V1Lease
from .v1_lease_list import V1LeaseList
from .v1_limit_range_spec import V1LimitRangeSpec
from .v1_limit_range import V1LimitRange
from .v1_limit_range_item import V1LimitRangeItem
from .v1_limit_range_list import V1LimitRangeList
from .v1_queuing_configuration import V1QueuingConfiguration
from .v1_limit_response import V1LimitResponse
from .v1_limited_priority_level_configuration import V1LimitedPriorityLevelConfiguration
from .v1_load_balancer_ingress import V1LoadBalancerIngress
from .v1_load_balancer_status import V1LoadBalancerStatus
from .v1_subject_access_review_status import V1SubjectAccessReviewStatus
from .v1_local_subject_access_review import V1LocalSubjectAccessReview
from .v1_local_volume_source import V1LocalVolumeSource
from .v1_managed_fields_entry import V1ManagedFieldsEntry
from .v1_match_condition import V1MatchCondition
from .v1_match_resources import V1MatchResources
from .v1_modify_volume_status import V1ModifyVolumeStatus
from .v1_mutating_webhook import V1MutatingWebhook
from .v1_mutating_webhook_configuration import V1MutatingWebhookConfiguration
from .v1_mutating_webhook_configuration_list import V1MutatingWebhookConfigurationList
from .v1_nfs_volume_source import V1NFSVolumeSource
from .v1_named_rule_with_operations import V1NamedRuleWithOperations
from .v1_namespace_spec import V1NamespaceSpec
from .v1_namespace_status import V1NamespaceStatus
from .v1_namespace import V1Namespace
from .v1_namespace_condition import V1NamespaceCondition
from .v1_namespace_list import V1NamespaceList
from .v1_network_policy_spec import V1NetworkPolicySpec
from .v1_network_policy import V1NetworkPolicy
from .v1_network_policy_egress_rule import V1NetworkPolicyEgressRule
from .v1_network_policy_ingress_rule import V1NetworkPolicyIngressRule
from .v1_network_policy_list import V1NetworkPolicyList
from .v1_network_policy_peer import V1NetworkPolicyPeer
from .v1_network_policy_port import V1NetworkPolicyPort
from .v1_node_config_source import V1NodeConfigSource
from .v1_node_spec import V1NodeSpec
from .v1_node_config_status import V1NodeConfigStatus
from .v1_node_daemon_endpoints import V1NodeDaemonEndpoints
from .v1_node_features import V1NodeFeatures
from .v1_node_swap_status import V1NodeSwapStatus
from .v1_node_system_info import V1NodeSystemInfo
from .v1_node_status import V1NodeStatus
from .v1_node import V1Node
from .v1_node_address import V1NodeAddress
from .v1_node_condition import V1NodeCondition
from .v1_node_list import V1NodeList
from .v1_node_runtime_handler_features import V1NodeRuntimeHandlerFeatures
from .v1_node_runtime_handler import V1NodeRuntimeHandler
from .v1_node_selector_requirement import V1NodeSelectorRequirement
from .v1_node_selector_term import V1NodeSelectorTerm
from .v1_non_resource_attributes import V1NonResourceAttributes
from .v1_non_resource_policy_rule import V1NonResourcePolicyRule
from .v1_non_resource_rule import V1NonResourceRule
from .v1_overhead import V1Overhead
from .v1_owner_reference import V1OwnerReference
from .v1_param_kind import V1ParamKind
from .v1_param_ref import V1ParamRef
from .v1_parent_reference import V1ParentReference
from .v1_volume_node_affinity import V1VolumeNodeAffinity
from .v1_photon_persistent_disk_volume_source import V1PhotonPersistentDiskVolumeSource
from .v1_portworx_volume_source import V1PortworxVolumeSource
from .v1_quobyte_volume_source import V1QuobyteVolumeSource
from .v1_rbd_persistent_volume_source import V1RBDPersistentVolumeSource
from .v1_scale_io_persistent_volume_source import V1ScaleIOPersistentVolumeSource
from .v1_storage_os_persistent_volume_source import V1StorageOSPersistentVolumeSource
from .v1_vsphere_virtual_disk_volume_source import V1VsphereVirtualDiskVolumeSource
from .v1_persistent_volume_spec import V1PersistentVolumeSpec
from .v1_persistent_volume_status import V1PersistentVolumeStatus
from .v1_persistent_volume import V1PersistentVolume
from .v1_typed_object_reference import V1TypedObjectReference
from .v1_volume_resource_requirements import V1VolumeResourceRequirements
from .v1_persistent_volume_claim_spec import V1PersistentVolumeClaimSpec
from .v1_persistent_volume_claim_status import V1PersistentVolumeClaimStatus
from .v1_persistent_volume_claim import V1PersistentVolumeClaim
from .v1_persistent_volume_claim_condition import V1PersistentVolumeClaimCondition
from .v1_persistent_volume_claim_list import V1PersistentVolumeClaimList
from .v1_persistent_volume_claim_volume_source import (
    V1PersistentVolumeClaimVolumeSource,
)
from .v1_persistent_volume_list import V1PersistentVolumeList
from .v1_pod_dns_config import V1PodDNSConfig
from .v1_pod_os import V1PodOS
from .v1_pod_security_context import V1PodSecurityContext
from .v1_pod_spec import V1PodSpec
from .v1_pod_extended_resource_claim_status import V1PodExtendedResourceClaimStatus
from .v1_pod_status import V1PodStatus
from .v1_pod import V1Pod
from .v1_pod_affinity_term import V1PodAffinityTerm
from .v1_pod_certificate_projection import V1PodCertificateProjection
from .v1_pod_condition import V1PodCondition
from .v1_pod_dns_config_option import V1PodDNSConfigOption
from .v1_pod_disruption_budget_spec import V1PodDisruptionBudgetSpec
from .v1_pod_disruption_budget_status import V1PodDisruptionBudgetStatus
from .v1_pod_disruption_budget import V1PodDisruptionBudget
from .v1_pod_disruption_budget_list import V1PodDisruptionBudgetList
from .v1_pod_failure_policy_on_exit_codes_requirement import (
    V1PodFailurePolicyOnExitCodesRequirement,
)
from .v1_pod_failure_policy_on_pod_conditions_pattern import (
    V1PodFailurePolicyOnPodConditionsPattern,
)
from .v1_pod_failure_policy_rule import V1PodFailurePolicyRule
from .v1_pod_ip import V1PodIP
from .v1_pod_list import V1PodList
from .v1_pod_readiness_gate import V1PodReadinessGate
from .v1_pod_resource_claim import V1PodResourceClaim
from .v1_pod_resource_claim_status import V1PodResourceClaimStatus
from .v1_pod_scheduling_gate import V1PodSchedulingGate
from .v1_pod_template_spec import V1PodTemplateSpec
from .v1_pod_template import V1PodTemplate
from .v1_pod_template_list import V1PodTemplateList
from .v1_policy_rule import V1PolicyRule
from .v1_policy_rules_with_subjects import V1PolicyRulesWithSubjects
from .v1_port_status import V1PortStatus
from .v1_preferred_scheduling_term import V1PreferredSchedulingTerm
from .v1_priority_class import V1PriorityClass
from .v1_priority_class_list import V1PriorityClassList
from .v1_priority_level_configuration_spec import V1PriorityLevelConfigurationSpec
from .v1_priority_level_configuration_status import V1PriorityLevelConfigurationStatus
from .v1_priority_level_configuration import V1PriorityLevelConfiguration
from .v1_priority_level_configuration_condition import (
    V1PriorityLevelConfigurationCondition,
)
from .v1_priority_level_configuration_list import V1PriorityLevelConfigurationList
from .v1_priority_level_configuration_reference import (
    V1PriorityLevelConfigurationReference,
)
from .v1_projected_volume_source import V1ProjectedVolumeSource
from .v1_rbd_volume_source import V1RBDVolumeSource
from .v1_replica_set_spec import V1ReplicaSetSpec
from .v1_replica_set_status import V1ReplicaSetStatus
from .v1_replica_set import V1ReplicaSet
from .v1_replica_set_condition import V1ReplicaSetCondition
from .v1_replica_set_list import V1ReplicaSetList
from .v1_replication_controller_spec import V1ReplicationControllerSpec
from .v1_replication_controller_status import V1ReplicationControllerStatus
from .v1_replication_controller import V1ReplicationController
from .v1_replication_controller_condition import V1ReplicationControllerCondition
from .v1_replication_controller_list import V1ReplicationControllerList
from .v1_resource_attributes import V1ResourceAttributes
from .v1_resource_claim_consumer_reference import V1ResourceClaimConsumerReference
from .v1_resource_claim_list import V1ResourceClaimList
from .v1_resource_claim_spec import V1ResourceClaimSpec
from .v1_resource_claim_template import V1ResourceClaimTemplate
from .v1_resource_claim_template_list import V1ResourceClaimTemplateList
from .v1_resource_claim_template_spec import V1ResourceClaimTemplateSpec
from .v1_resource_health import V1ResourceHealth
from .v1_resource_policy_rule import V1ResourcePolicyRule
from .v1_resource_pool import V1ResourcePool
from .v1_scope_selector import V1ScopeSelector
from .v1_resource_quota_spec import V1ResourceQuotaSpec
from .v1_resource_quota_status import V1ResourceQuotaStatus
from .v1_resource_quota import V1ResourceQuota
from .v1_resource_quota_list import V1ResourceQuotaList
from .v1_resource_rule import V1ResourceRule
from .v1_resource_slice import V1ResourceSlice
from .v1_resource_slice_list import V1ResourceSliceList
from .v1_resource_slice_spec import V1ResourceSliceSpec
from .v1_resource_status import V1ResourceStatus
from .v1_role import V1Role
from .v1_role_binding import V1RoleBinding
from .v1_role_binding_list import V1RoleBindingList
from .v1_role_list import V1RoleList
from .v1_role_ref import V1RoleRef
from .v1_rolling_update_stateful_set_strategy import V1RollingUpdateStatefulSetStrategy
from .v1_rule_with_operations import V1RuleWithOperations
from .v1_scheduling import V1Scheduling
from .v1_runtime_class import V1RuntimeClass
from .v1_runtime_class_list import V1RuntimeClassList
from .v1_scale_spec import V1ScaleSpec
from .v1_scale_status import V1ScaleStatus
from .v1_scale import V1Scale
from .v1_scale_io_volume_source import V1ScaleIOVolumeSource
from .v1_scoped_resource_selector_requirement import V1ScopedResourceSelectorRequirement
from .v1_secret import V1Secret
from .v1_secret_list import V1SecretList
from .v1_secret_projection import V1SecretProjection
from .v1_secret_volume_source import V1SecretVolumeSource
from .v1_selectable_field import V1SelectableField
from .v1_self_subject_access_review import V1SelfSubjectAccessReview
from .v1_self_subject_access_review_spec import V1SelfSubjectAccessReviewSpec
from .v1_user_info import V1UserInfo
from .v1_self_subject_review_status import V1SelfSubjectReviewStatus
from .v1_self_subject_review import V1SelfSubjectReview
from .v1_subject_rules_review_status import V1SubjectRulesReviewStatus
from .v1_self_subject_rules_review import V1SelfSubjectRulesReview
from .v1_self_subject_rules_review_spec import V1SelfSubjectRulesReviewSpec
from .v1_server_address_by_client_cidr import V1ServerAddressByClientCIDR
from .v1_session_affinity_config import V1SessionAffinityConfig
from .v1_service_spec import V1ServiceSpec
from .v1_service_status import V1ServiceStatus
from .v1_service import V1Service
from .v1_service_account import V1ServiceAccount
from .v1_service_account_list import V1ServiceAccountList
from .v1_service_account_token_projection import V1ServiceAccountTokenProjection
from .v1_service_cidr_spec import V1ServiceCIDRSpec
from .v1_service_cidr_status import V1ServiceCIDRStatus
from .v1_service_cidr import V1ServiceCIDR
from .v1_service_cidr_list import V1ServiceCIDRList
from .v1_service_list import V1ServiceList
from .v1_service_port import V1ServicePort
from .v1_stateful_set_ordinals import V1StatefulSetOrdinals
from .v1_stateful_set_persistent_volume_claim_retention_policy import (
    V1StatefulSetPersistentVolumeClaimRetentionPolicy,
)
from .v1_stateful_set_update_strategy import V1StatefulSetUpdateStrategy
from .v1_stateful_set_spec import V1StatefulSetSpec
from .v1_stateful_set_status import V1StatefulSetStatus
from .v1_stateful_set import V1StatefulSet
from .v1_stateful_set_condition import V1StatefulSetCondition
from .v1_stateful_set_list import V1StatefulSetList
from .v1_status_details import V1StatusDetails
from .v1_status import V1Status
from .v1_status_cause import V1StatusCause
from .v1_storage_class import V1StorageClass
from .v1_storage_class_list import V1StorageClassList
from .v1_storage_os_volume_source import V1StorageOSVolumeSource
from .v1_subject_access_review import V1SubjectAccessReview
from .v1_subject_access_review_spec import V1SubjectAccessReviewSpec
from .v1_success_policy_rule import V1SuccessPolicyRule
from .v1_sysctl import V1Sysctl
from .v1_taint import V1Taint
from .v1_token_request_spec import V1TokenRequestSpec
from .v1_token_review_status import V1TokenReviewStatus
from .v1_token_review import V1TokenReview
from .v1_token_review_spec import V1TokenReviewSpec
from .v1_toleration import V1Toleration
from .v1_topology_selector_label_requirement import V1TopologySelectorLabelRequirement
from .v1_topology_selector_term import V1TopologySelectorTerm
from .v1_topology_spread_constraint import V1TopologySpreadConstraint
from .v1_type_checking import V1TypeChecking
from .v1_validating_admission_policy_spec import V1ValidatingAdmissionPolicySpec
from .v1_validating_admission_policy_status import V1ValidatingAdmissionPolicyStatus
from .v1_validating_admission_policy import V1ValidatingAdmissionPolicy
from .v1_validating_admission_policy_binding_spec import (
    V1ValidatingAdmissionPolicyBindingSpec,
)
from .v1_validating_admission_policy_binding import V1ValidatingAdmissionPolicyBinding
from .v1_validating_admission_policy_binding_list import (
    V1ValidatingAdmissionPolicyBindingList,
)
from .v1_validating_admission_policy_list import V1ValidatingAdmissionPolicyList
from .v1_validating_webhook import V1ValidatingWebhook
from .v1_validating_webhook_configuration import V1ValidatingWebhookConfiguration
from .v1_validating_webhook_configuration_list import (
    V1ValidatingWebhookConfigurationList,
)
from .v1_validation import V1Validation
from .v1_validation_rule import V1ValidationRule
from .v1_variable import V1Variable
from .v1_volume import V1Volume
from .v1_volume_error import V1VolumeError
from .v1_volume_attachment_status import V1VolumeAttachmentStatus
from .v1_volume_attachment import V1VolumeAttachment
from .v1_volume_attachment_list import V1VolumeAttachmentList
from .v1_volume_attachment_source import V1VolumeAttachmentSource
from .v1_volume_attachment_spec import V1VolumeAttachmentSpec
from .v1_volume_attributes_class import V1VolumeAttributesClass
from .v1_volume_attributes_class_list import V1VolumeAttributesClassList
from .v1_volume_device import V1VolumeDevice
from .v1_volume_mount import V1VolumeMount
from .v1_volume_mount_status import V1VolumeMountStatus
from .v1_volume_projection import V1VolumeProjection
from .v1_watch_event import V1WatchEvent
from .v1_weighted_pod_affinity_term import V1WeightedPodAffinityTerm
from .v1alpha1_apply_configuration import V1alpha1ApplyConfiguration
from .v1alpha1_cluster_trust_bundle import V1alpha1ClusterTrustBundle
from .v1alpha1_cluster_trust_bundle_list import V1alpha1ClusterTrustBundleList
from .v1alpha1_cluster_trust_bundle_spec import V1alpha1ClusterTrustBundleSpec
from .v1alpha1_group_version_resource import V1alpha1GroupVersionResource
from .v1alpha1_json_patch import V1alpha1JSONPatch
from .v1alpha1_match_condition import V1alpha1MatchCondition
from .v1alpha1_match_resources import V1alpha1MatchResources
from .v1alpha1_migration_condition import V1alpha1MigrationCondition
from .v1alpha1_param_kind import V1alpha1ParamKind
from .v1alpha1_mutating_admission_policy_spec import V1alpha1MutatingAdmissionPolicySpec
from .v1alpha1_mutating_admission_policy import V1alpha1MutatingAdmissionPolicy
from .v1alpha1_param_ref import V1alpha1ParamRef
from .v1alpha1_mutating_admission_policy_binding_spec import (
    V1alpha1MutatingAdmissionPolicyBindingSpec,
)
from .v1alpha1_mutating_admission_policy_binding import (
    V1alpha1MutatingAdmissionPolicyBinding,
)
from .v1alpha1_mutating_admission_policy_binding_list import (
    V1alpha1MutatingAdmissionPolicyBindingList,
)
from .v1alpha1_mutating_admission_policy_list import V1alpha1MutatingAdmissionPolicyList
from .v1alpha1_mutation import V1alpha1Mutation
from .v1alpha1_named_rule_with_operations import V1alpha1NamedRuleWithOperations
from .v1alpha1_pod_certificate_request_status import V1alpha1PodCertificateRequestStatus
from .v1alpha1_pod_certificate_request import V1alpha1PodCertificateRequest
from .v1alpha1_pod_certificate_request_list import V1alpha1PodCertificateRequestList
from .v1alpha1_pod_certificate_request_spec import V1alpha1PodCertificateRequestSpec
from .v1alpha1_server_storage_version import V1alpha1ServerStorageVersion
from .v1alpha1_storage_version import V1alpha1StorageVersion
from .v1alpha1_storage_version_condition import V1alpha1StorageVersionCondition
from .v1alpha1_storage_version_list import V1alpha1StorageVersionList
from .v1alpha1_storage_version_migration_spec import V1alpha1StorageVersionMigrationSpec
from .v1alpha1_storage_version_migration_status import (
    V1alpha1StorageVersionMigrationStatus,
)
from .v1alpha1_storage_version_migration import V1alpha1StorageVersionMigration
from .v1alpha1_storage_version_migration_list import V1alpha1StorageVersionMigrationList
from .v1alpha1_storage_version_status import V1alpha1StorageVersionStatus
from .v1alpha1_variable import V1alpha1Variable
from .v1alpha1_volume_attributes_class import V1alpha1VolumeAttributesClass
from .v1alpha1_volume_attributes_class_list import V1alpha1VolumeAttributesClassList
from .v1alpha2_lease_candidate_spec import V1alpha2LeaseCandidateSpec
from .v1alpha2_lease_candidate import V1alpha2LeaseCandidate
from .v1alpha2_lease_candidate_list import V1alpha2LeaseCandidateList
from .v1alpha3_cel_device_selector import V1alpha3CELDeviceSelector
from .v1alpha3_device_selector import V1alpha3DeviceSelector
from .v1alpha3_device_taint import V1alpha3DeviceTaint
from .v1alpha3_device_taint_rule import V1alpha3DeviceTaintRule
from .v1alpha3_device_taint_rule_list import V1alpha3DeviceTaintRuleList
from .v1alpha3_device_taint_selector import V1alpha3DeviceTaintSelector
from .v1alpha3_device_taint_rule_spec import V1alpha3DeviceTaintRuleSpec
from .v1beta1_network_device_data import V1beta1NetworkDeviceData
from .v1beta1_allocated_device_status import V1beta1AllocatedDeviceStatus
from .v1beta1_device_allocation_result import V1beta1DeviceAllocationResult
from .v1beta1_allocation_result import V1beta1AllocationResult
from .v1beta1_apply_configuration import V1beta1ApplyConfiguration
from .v1beta1_basic_device import V1beta1BasicDevice
from .v1beta1_cel_device_selector import V1beta1CELDeviceSelector
from .v1beta1_capacity_request_policy_range import V1beta1CapacityRequestPolicyRange
from .v1beta1_capacity_request_policy import V1beta1CapacityRequestPolicy
from .v1beta1_capacity_requirements import V1beta1CapacityRequirements
from .v1beta1_cluster_trust_bundle import V1beta1ClusterTrustBundle
from .v1beta1_cluster_trust_bundle_list import V1beta1ClusterTrustBundleList
from .v1beta1_cluster_trust_bundle_spec import V1beta1ClusterTrustBundleSpec
from .v1beta1_counter import V1beta1Counter
from .v1beta1_counter_set import V1beta1CounterSet
from .v1beta1_device import V1beta1Device
from .v1beta1_opaque_device_configuration import V1beta1OpaqueDeviceConfiguration
from .v1beta1_device_allocation_configuration import (
    V1beta1DeviceAllocationConfiguration,
)
from .v1beta1_device_attribute import V1beta1DeviceAttribute
from .v1beta1_device_capacity import V1beta1DeviceCapacity
from .v1beta1_device_claim import V1beta1DeviceClaim
from .v1beta1_device_claim_configuration import V1beta1DeviceClaimConfiguration
from .v1beta1_device_class import V1beta1DeviceClass
from .v1beta1_device_class_configuration import V1beta1DeviceClassConfiguration
from .v1beta1_device_class_list import V1beta1DeviceClassList
from .v1beta1_device_class_spec import V1beta1DeviceClassSpec
from .v1beta1_device_constraint import V1beta1DeviceConstraint
from .v1beta1_device_counter_consumption import V1beta1DeviceCounterConsumption
from .v1beta1_device_request import V1beta1DeviceRequest
from .v1beta1_device_request_allocation_result import (
    V1beta1DeviceRequestAllocationResult,
)
from .v1beta1_device_selector import V1beta1DeviceSelector
from .v1beta1_device_sub_request import V1beta1DeviceSubRequest
from .v1beta1_device_taint import V1beta1DeviceTaint
from .v1beta1_device_toleration import V1beta1DeviceToleration
from .v1beta1_ip_address_spec import V1beta1IPAddressSpec
from .v1beta1_ip_address import V1beta1IPAddress
from .v1beta1_ip_address_list import V1beta1IPAddressList
from .v1beta1_json_patch import V1beta1JSONPatch
from .v1beta1_lease_candidate_spec import V1beta1LeaseCandidateSpec
from .v1beta1_lease_candidate import V1beta1LeaseCandidate
from .v1beta1_lease_candidate_list import V1beta1LeaseCandidateList
from .v1beta1_match_condition import V1beta1MatchCondition
from .v1beta1_match_resources import V1beta1MatchResources
from .v1beta1_param_kind import V1beta1ParamKind
from .v1beta1_mutating_admission_policy_spec import V1beta1MutatingAdmissionPolicySpec
from .v1beta1_mutating_admission_policy import V1beta1MutatingAdmissionPolicy
from .v1beta1_param_ref import V1beta1ParamRef
from .v1beta1_mutating_admission_policy_binding_spec import (
    V1beta1MutatingAdmissionPolicyBindingSpec,
)
from .v1beta1_mutating_admission_policy_binding import (
    V1beta1MutatingAdmissionPolicyBinding,
)
from .v1beta1_mutating_admission_policy_binding_list import (
    V1beta1MutatingAdmissionPolicyBindingList,
)
from .v1beta1_mutating_admission_policy_list import V1beta1MutatingAdmissionPolicyList
from .v1beta1_mutation import V1beta1Mutation
from .v1beta1_named_rule_with_operations import V1beta1NamedRuleWithOperations
from .v1beta1_parent_reference import V1beta1ParentReference
from .v1beta1_resource_claim_status import V1beta1ResourceClaimStatus
from .v1beta1_resource_claim import V1beta1ResourceClaim
from .v1beta1_resource_claim_consumer_reference import (
    V1beta1ResourceClaimConsumerReference,
)
from .v1beta1_resource_claim_list import V1beta1ResourceClaimList
from .v1beta1_resource_claim_spec import V1beta1ResourceClaimSpec
from .v1beta1_resource_claim_template import V1beta1ResourceClaimTemplate
from .v1beta1_resource_claim_template_list import V1beta1ResourceClaimTemplateList
from .v1beta1_resource_claim_template_spec import V1beta1ResourceClaimTemplateSpec
from .v1beta1_resource_pool import V1beta1ResourcePool
from .v1beta1_resource_slice import V1beta1ResourceSlice
from .v1beta1_resource_slice_list import V1beta1ResourceSliceList
from .v1beta1_resource_slice_spec import V1beta1ResourceSliceSpec
from .v1beta1_service_cidr_spec import V1beta1ServiceCIDRSpec
from .v1beta1_service_cidr_status import V1beta1ServiceCIDRStatus
from .v1beta1_service_cidr import V1beta1ServiceCIDR
from .v1beta1_service_cidr_list import V1beta1ServiceCIDRList
from .v1beta1_variable import V1beta1Variable
from .v1beta1_volume_attributes_class import V1beta1VolumeAttributesClass
from .v1beta1_volume_attributes_class_list import V1beta1VolumeAttributesClassList
from .v1beta2_network_device_data import V1beta2NetworkDeviceData
from .v1beta2_allocated_device_status import V1beta2AllocatedDeviceStatus
from .v1beta2_device_allocation_result import V1beta2DeviceAllocationResult
from .v1beta2_allocation_result import V1beta2AllocationResult
from .v1beta2_cel_device_selector import V1beta2CELDeviceSelector
from .v1beta2_capacity_request_policy_range import V1beta2CapacityRequestPolicyRange
from .v1beta2_capacity_request_policy import V1beta2CapacityRequestPolicy
from .v1beta2_capacity_requirements import V1beta2CapacityRequirements
from .v1beta2_counter import V1beta2Counter
from .v1beta2_counter_set import V1beta2CounterSet
from .v1beta2_device import V1beta2Device
from .v1beta2_opaque_device_configuration import V1beta2OpaqueDeviceConfiguration
from .v1beta2_device_allocation_configuration import (
    V1beta2DeviceAllocationConfiguration,
)
from .v1beta2_device_attribute import V1beta2DeviceAttribute
from .v1beta2_device_capacity import V1beta2DeviceCapacity
from .v1beta2_device_claim import V1beta2DeviceClaim
from .v1beta2_device_claim_configuration import V1beta2DeviceClaimConfiguration
from .v1beta2_device_class import V1beta2DeviceClass
from .v1beta2_device_class_configuration import V1beta2DeviceClassConfiguration
from .v1beta2_device_class_list import V1beta2DeviceClassList
from .v1beta2_device_class_spec import V1beta2DeviceClassSpec
from .v1beta2_device_constraint import V1beta2DeviceConstraint
from .v1beta2_device_counter_consumption import V1beta2DeviceCounterConsumption
from .v1beta2_exact_device_request import V1beta2ExactDeviceRequest
from .v1beta2_device_request import V1beta2DeviceRequest
from .v1beta2_device_request_allocation_result import (
    V1beta2DeviceRequestAllocationResult,
)
from .v1beta2_device_selector import V1beta2DeviceSelector
from .v1beta2_device_sub_request import V1beta2DeviceSubRequest
from .v1beta2_device_taint import V1beta2DeviceTaint
from .v1beta2_device_toleration import V1beta2DeviceToleration
from .v1beta2_resource_claim_status import V1beta2ResourceClaimStatus
from .v1beta2_resource_claim import V1beta2ResourceClaim
from .v1beta2_resource_claim_consumer_reference import (
    V1beta2ResourceClaimConsumerReference,
)
from .v1beta2_resource_claim_list import V1beta2ResourceClaimList
from .v1beta2_resource_claim_spec import V1beta2ResourceClaimSpec
from .v1beta2_resource_claim_template import V1beta2ResourceClaimTemplate
from .v1beta2_resource_claim_template_list import V1beta2ResourceClaimTemplateList
from .v1beta2_resource_claim_template_spec import V1beta2ResourceClaimTemplateSpec
from .v1beta2_resource_pool import V1beta2ResourcePool
from .v1beta2_resource_slice import V1beta2ResourceSlice
from .v1beta2_resource_slice_list import V1beta2ResourceSliceList
from .v1beta2_resource_slice_spec import V1beta2ResourceSliceSpec
from .v2_container_resource_metric_source import V2ContainerResourceMetricSource
from .v2_container_resource_metric_status import V2ContainerResourceMetricStatus
from .v2_cross_version_object_reference import V2CrossVersionObjectReference
from .v2_external_metric_source import V2ExternalMetricSource
from .v2_external_metric_status import V2ExternalMetricStatus
from .v2_hpa_scaling_policy import V2HPAScalingPolicy
from .v2_hpa_scaling_rules import V2HPAScalingRules
from .v2_horizontal_pod_autoscaler_behavior import V2HorizontalPodAutoscalerBehavior
from .v2_horizontal_pod_autoscaler_spec import V2HorizontalPodAutoscalerSpec
from .v2_horizontal_pod_autoscaler_status import V2HorizontalPodAutoscalerStatus
from .v2_horizontal_pod_autoscaler import V2HorizontalPodAutoscaler
from .v2_horizontal_pod_autoscaler_condition import V2HorizontalPodAutoscalerCondition
from .v2_horizontal_pod_autoscaler_list import V2HorizontalPodAutoscalerList
from .v2_metric_identifier import V2MetricIdentifier
from .v2_object_metric_source import V2ObjectMetricSource
from .v2_pods_metric_source import V2PodsMetricSource
from .v2_resource_metric_source import V2ResourceMetricSource
from .v2_metric_spec import V2MetricSpec
from .v2_object_metric_status import V2ObjectMetricStatus
from .v2_pods_metric_status import V2PodsMetricStatus
from .v2_resource_metric_status import V2ResourceMetricStatus
from .v2_metric_status import V2MetricStatus
from .v2_metric_target import V2MetricTarget
from .v2_metric_value_status import V2MetricValueStatus
from .version_info import VersionInfo
from .base import ListModel, ResourceModel

__all__ = (
    "AdmissionregistrationV1ServiceReference",
    "AdmissionregistrationV1WebhookClientConfig",
    "ApiextensionsV1ServiceReference",
    "ApiextensionsV1WebhookClientConfig",
    "ApiregistrationV1ServiceReference",
    "AuthenticationV1TokenRequest",
    "CoreV1EndpointPort",
    "CoreV1Event",
    "CoreV1EventList",
    "CoreV1EventSeries",
    "CoreV1ResourceClaim",
    "DiscoveryV1EndpointPort",
    "EventsV1Event",
    "EventsV1EventList",
    "EventsV1EventSeries",
    "FlowcontrolV1Subject",
    "ListModel",
    "RbacV1Subject",
    "ResourceModel",
    "ResourceV1ResourceClaim",
    "StorageV1TokenRequest",
    "V1APIGroup",
    "V1APIGroupList",
    "V1APIResource",
    "V1APIResourceList",
    "V1APIService",
    "V1APIServiceCondition",
    "V1APIServiceList",
    "V1APIServiceSpec",
    "V1APIServiceStatus",
    "V1APIVersions",
    "V1AWSElasticBlockStoreVolumeSource",
    "V1Affinity",
    "V1AggregationRule",
    "V1AllocatedDeviceStatus",
    "V1AllocationResult",
    "V1AppArmorProfile",
    "V1AttachedVolume",
    "V1AuditAnnotation",
    "V1AzureDiskVolumeSource",
    "V1AzureFilePersistentVolumeSource",
    "V1AzureFileVolumeSource",
    "V1Binding",
    "V1BoundObjectReference",
    "V1CELDeviceSelector",
    "V1CSIDriver",
    "V1CSIDriverList",
    "V1CSIDriverSpec",
    "V1CSINode",
    "V1CSINodeDriver",
    "V1CSINodeList",
    "V1CSINodeSpec",
    "V1CSIPersistentVolumeSource",
    "V1CSIStorageCapacity",
    "V1CSIStorageCapacityList",
    "V1CSIVolumeSource",
    "V1Capabilities",
    "V1CapacityRequestPolicy",
    "V1CapacityRequestPolicyRange",
    "V1CapacityRequirements",
    "V1CephFSPersistentVolumeSource",
    "V1CephFSVolumeSource",
    "V1CertificateSigningRequest",
    "V1CertificateSigningRequestCondition",
    "V1CertificateSigningRequestList",
    "V1CertificateSigningRequestSpec",
    "V1CertificateSigningRequestStatus",
    "V1CinderPersistentVolumeSource",
    "V1CinderVolumeSource",
    "V1ClientIPConfig",
    "V1ClusterRole",
    "V1ClusterRoleBinding",
    "V1ClusterRoleBindingList",
    "V1ClusterRoleList",
    "V1ClusterTrustBundleProjection",
    "V1ComponentCondition",
    "V1ComponentStatus",
    "V1ComponentStatusList",
    "V1Condition",
    "V1ConfigMap",
    "V1ConfigMapEnvSource",
    "V1ConfigMapKeySelector",
    "V1ConfigMapList",
    "V1ConfigMapNodeConfigSource",
    "V1ConfigMapProjection",
    "V1ConfigMapVolumeSource",
    "V1Container",
    "V1ContainerExtendedResourceRequest",
    "V1ContainerImage",
    "V1ContainerPort",
    "V1ContainerResizePolicy",
    "V1ContainerRestartRule",
    "V1ContainerRestartRuleOnExitCodes",
    "V1ContainerState",
    "V1ContainerStateRunning",
    "V1ContainerStateTerminated",
    "V1ContainerStateWaiting",
    "V1ContainerStatus",
    "V1ContainerUser",
    "V1ControllerRevision",
    "V1ControllerRevisionList",
    "V1Counter",
    "V1CounterSet",
    "V1CronJob",
    "V1CronJobList",
    "V1CronJobSpec",
    "V1CronJobStatus",
    "V1CrossVersionObjectReference",
    "V1CustomResourceColumnDefinition",
    "V1CustomResourceConversion",
    "V1CustomResourceDefinition",
    "V1CustomResourceDefinitionCondition",
    "V1CustomResourceDefinitionList",
    "V1CustomResourceDefinitionNames",
    "V1CustomResourceDefinitionSpec",
    "V1CustomResourceDefinitionStatus",
    "V1CustomResourceDefinitionVersion",
    "V1CustomResourceSubresourceScale",
    "V1CustomResourceSubresources",
    "V1CustomResourceValidation",
    "V1DaemonEndpoint",
    "V1DaemonSet",
    "V1DaemonSetCondition",
    "V1DaemonSetList",
    "V1DaemonSetSpec",
    "V1DaemonSetStatus",
    "V1DaemonSetUpdateStrategy",
    "V1DeleteOptions",
    "V1Deployment",
    "V1DeploymentCondition",
    "V1DeploymentList",
    "V1DeploymentSpec",
    "V1DeploymentStatus",
    "V1DeploymentStrategy",
    "V1Device",
    "V1DeviceAllocationConfiguration",
    "V1DeviceAllocationResult",
    "V1DeviceAttribute",
    "V1DeviceCapacity",
    "V1DeviceClaim",
    "V1DeviceClaimConfiguration",
    "V1DeviceClass",
    "V1DeviceClassConfiguration",
    "V1DeviceClassList",
    "V1DeviceClassSpec",
    "V1DeviceConstraint",
    "V1DeviceCounterConsumption",
    "V1DeviceRequest",
    "V1DeviceRequestAllocationResult",
    "V1DeviceSelector",
    "V1DeviceSubRequest",
    "V1DeviceTaint",
    "V1DeviceToleration",
    "V1DownwardAPIProjection",
    "V1DownwardAPIVolumeFile",
    "V1DownwardAPIVolumeSource",
    "V1EmptyDirVolumeSource",
    "V1Endpoint",
    "V1EndpointAddress",
    "V1EndpointConditions",
    "V1EndpointHints",
    "V1EndpointSlice",
    "V1EndpointSliceList",
    "V1EndpointSubset",
    "V1Endpoints",
    "V1EndpointsList",
    "V1EnvFromSource",
    "V1EnvVar",
    "V1EnvVarSource",
    "V1EphemeralContainer",
    "V1EphemeralVolumeSource",
    "V1EventSource",
    "V1Eviction",
    "V1ExactDeviceRequest",
    "V1ExecAction",
    "V1ExemptPriorityLevelConfiguration",
    "V1ExpressionWarning",
    "V1ExternalDocumentation",
    "V1FCVolumeSource",
    "V1FieldSelectorAttributes",
    "V1FieldSelectorRequirement",
    "V1FileKeySelector",
    "V1FlexPersistentVolumeSource",
    "V1FlexVolumeSource",
    "V1FlockerVolumeSource",
    "V1FlowDistinguisherMethod",
    "V1FlowSchema",
    "V1FlowSchemaCondition",
    "V1FlowSchemaList",
    "V1FlowSchemaSpec",
    "V1FlowSchemaStatus",
    "V1ForNode",
    "V1ForZone",
    "V1GCEPersistentDiskVolumeSource",
    "V1GRPCAction",
    "V1GitRepoVolumeSource",
    "V1GlusterfsPersistentVolumeSource",
    "V1GlusterfsVolumeSource",
    "V1GroupSubject",
    "V1GroupVersionForDiscovery",
    "V1HTTPGetAction",
    "V1HTTPHeader",
    "V1HTTPIngressPath",
    "V1HTTPIngressRuleValue",
    "V1HorizontalPodAutoscaler",
    "V1HorizontalPodAutoscalerList",
    "V1HorizontalPodAutoscalerSpec",
    "V1HorizontalPodAutoscalerStatus",
    "V1HostAlias",
    "V1HostIP",
    "V1HostPathVolumeSource",
    "V1IPAddress",
    "V1IPAddressList",
    "V1IPAddressSpec",
    "V1IPBlock",
    "V1ISCSIPersistentVolumeSource",
    "V1ISCSIVolumeSource",
    "V1ImageVolumeSource",
    "V1Ingress",
    "V1IngressBackend",
    "V1IngressClass",
    "V1IngressClassList",
    "V1IngressClassParametersReference",
    "V1IngressClassSpec",
    "V1IngressList",
    "V1IngressLoadBalancerIngress",
    "V1IngressLoadBalancerStatus",
    "V1IngressPortStatus",
    "V1IngressRule",
    "V1IngressServiceBackend",
    "V1IngressSpec",
    "V1IngressStatus",
    "V1IngressTLS",
    "V1JSONSchemaProps",
    "V1Job",
    "V1JobCondition",
    "V1JobList",
    "V1JobSpec",
    "V1JobStatus",
    "V1JobTemplateSpec",
    "V1KeyToPath",
    "V1LabelSelector",
    "V1LabelSelectorAttributes",
    "V1LabelSelectorRequirement",
    "V1Lease",
    "V1LeaseList",
    "V1LeaseSpec",
    "V1Lifecycle",
    "V1LifecycleHandler",
    "V1LimitRange",
    "V1LimitRangeItem",
    "V1LimitRangeList",
    "V1LimitRangeSpec",
    "V1LimitResponse",
    "V1LimitedPriorityLevelConfiguration",
    "V1LinuxContainerUser",
    "V1ListMeta",
    "V1LoadBalancerIngress",
    "V1LoadBalancerStatus",
    "V1LocalObjectReference",
    "V1LocalSubjectAccessReview",
    "V1LocalVolumeSource",
    "V1ManagedFieldsEntry",
    "V1MatchCondition",
    "V1MatchResources",
    "V1ModifyVolumeStatus",
    "V1MutatingWebhook",
    "V1MutatingWebhookConfiguration",
    "V1MutatingWebhookConfigurationList",
    "V1NFSVolumeSource",
    "V1NamedRuleWithOperations",
    "V1Namespace",
    "V1NamespaceCondition",
    "V1NamespaceList",
    "V1NamespaceSpec",
    "V1NamespaceStatus",
    "V1NetworkDeviceData",
    "V1NetworkPolicy",
    "V1NetworkPolicyEgressRule",
    "V1NetworkPolicyIngressRule",
    "V1NetworkPolicyList",
    "V1NetworkPolicyPeer",
    "V1NetworkPolicyPort",
    "V1NetworkPolicySpec",
    "V1Node",
    "V1NodeAddress",
    "V1NodeAffinity",
    "V1NodeCondition",
    "V1NodeConfigSource",
    "V1NodeConfigStatus",
    "V1NodeDaemonEndpoints",
    "V1NodeFeatures",
    "V1NodeList",
    "V1NodeRuntimeHandler",
    "V1NodeRuntimeHandlerFeatures",
    "V1NodeSelector",
    "V1NodeSelectorRequirement",
    "V1NodeSelectorTerm",
    "V1NodeSpec",
    "V1NodeStatus",
    "V1NodeSwapStatus",
    "V1NodeSystemInfo",
    "V1NonResourceAttributes",
    "V1NonResourcePolicyRule",
    "V1NonResourceRule",
    "V1ObjectFieldSelector",
    "V1ObjectMeta",
    "V1ObjectReference",
    "V1OpaqueDeviceConfiguration",
    "V1Overhead",
    "V1OwnerReference",
    "V1ParamKind",
    "V1ParamRef",
    "V1ParentReference",
    "V1PersistentVolume",
    "V1PersistentVolumeClaim",
    "V1PersistentVolumeClaimCondition",
    "V1PersistentVolumeClaimList",
    "V1PersistentVolumeClaimSpec",
    "V1PersistentVolumeClaimStatus",
    "V1PersistentVolumeClaimTemplate",
    "V1PersistentVolumeClaimVolumeSource",
    "V1PersistentVolumeList",
    "V1PersistentVolumeSpec",
    "V1PersistentVolumeStatus",
    "V1PhotonPersistentDiskVolumeSource",
    "V1Pod",
    "V1PodAffinity",
    "V1PodAffinityTerm",
    "V1PodAntiAffinity",
    "V1PodCertificateProjection",
    "V1PodCondition",
    "V1PodDNSConfig",
    "V1PodDNSConfigOption",
    "V1PodDisruptionBudget",
    "V1PodDisruptionBudgetList",
    "V1PodDisruptionBudgetSpec",
    "V1PodDisruptionBudgetStatus",
    "V1PodExtendedResourceClaimStatus",
    "V1PodFailurePolicy",
    "V1PodFailurePolicyOnExitCodesRequirement",
    "V1PodFailurePolicyOnPodConditionsPattern",
    "V1PodFailurePolicyRule",
    "V1PodIP",
    "V1PodList",
    "V1PodOS",
    "V1PodReadinessGate",
    "V1PodResourceClaim",
    "V1PodResourceClaimStatus",
    "V1PodSchedulingGate",
    "V1PodSecurityContext",
    "V1PodSpec",
    "V1PodStatus",
    "V1PodTemplate",
    "V1PodTemplateList",
    "V1PodTemplateSpec",
    "V1PolicyRule",
    "V1PolicyRulesWithSubjects",
    "V1PortStatus",
    "V1PortworxVolumeSource",
    "V1Preconditions",
    "V1PreferredSchedulingTerm",
    "V1PriorityClass",
    "V1PriorityClassList",
    "V1PriorityLevelConfiguration",
    "V1PriorityLevelConfigurationCondition",
    "V1PriorityLevelConfigurationList",
    "V1PriorityLevelConfigurationReference",
    "V1PriorityLevelConfigurationSpec",
    "V1PriorityLevelConfigurationStatus",
    "V1Probe",
    "V1ProjectedVolumeSource",
    "V1QueuingConfiguration",
    "V1QuobyteVolumeSource",
    "V1RBDPersistentVolumeSource",
    "V1RBDVolumeSource",
    "V1ReplicaSet",
    "V1ReplicaSetCondition",
    "V1ReplicaSetList",
    "V1ReplicaSetSpec",
    "V1ReplicaSetStatus",
    "V1ReplicationController",
    "V1ReplicationControllerCondition",
    "V1ReplicationControllerList",
    "V1ReplicationControllerSpec",
    "V1ReplicationControllerStatus",
    "V1ResourceAttributes",
    "V1ResourceClaimConsumerReference",
    "V1ResourceClaimList",
    "V1ResourceClaimSpec",
    "V1ResourceClaimStatus",
    "V1ResourceClaimTemplate",
    "V1ResourceClaimTemplateList",
    "V1ResourceClaimTemplateSpec",
    "V1ResourceFieldSelector",
    "V1ResourceHealth",
    "V1ResourcePolicyRule",
    "V1ResourcePool",
    "V1ResourceQuota",
    "V1ResourceQuotaList",
    "V1ResourceQuotaSpec",
    "V1ResourceQuotaStatus",
    "V1ResourceRequirements",
    "V1ResourceRule",
    "V1ResourceSlice",
    "V1ResourceSliceList",
    "V1ResourceSliceSpec",
    "V1ResourceStatus",
    "V1Role",
    "V1RoleBinding",
    "V1RoleBindingList",
    "V1RoleList",
    "V1RoleRef",
    "V1RollingUpdateDaemonSet",
    "V1RollingUpdateDeployment",
    "V1RollingUpdateStatefulSetStrategy",
    "V1RuleWithOperations",
    "V1RuntimeClass",
    "V1RuntimeClassList",
    "V1SELinuxOptions",
    "V1Scale",
    "V1ScaleIOPersistentVolumeSource",
    "V1ScaleIOVolumeSource",
    "V1ScaleSpec",
    "V1ScaleStatus",
    "V1Scheduling",
    "V1ScopeSelector",
    "V1ScopedResourceSelectorRequirement",
    "V1SeccompProfile",
    "V1Secret",
    "V1SecretEnvSource",
    "V1SecretKeySelector",
    "V1SecretList",
    "V1SecretProjection",
    "V1SecretReference",
    "V1SecretVolumeSource",
    "V1SecurityContext",
    "V1SelectableField",
    "V1SelfSubjectAccessReview",
    "V1SelfSubjectAccessReviewSpec",
    "V1SelfSubjectReview",
    "V1SelfSubjectReviewStatus",
    "V1SelfSubjectRulesReview",
    "V1SelfSubjectRulesReviewSpec",
    "V1ServerAddressByClientCIDR",
    "V1Service",
    "V1ServiceAccount",
    "V1ServiceAccountList",
    "V1ServiceAccountSubject",
    "V1ServiceAccountTokenProjection",
    "V1ServiceBackendPort",
    "V1ServiceCIDR",
    "V1ServiceCIDRList",
    "V1ServiceCIDRSpec",
    "V1ServiceCIDRStatus",
    "V1ServiceList",
    "V1ServicePort",
    "V1ServiceSpec",
    "V1ServiceStatus",
    "V1SessionAffinityConfig",
    "V1SleepAction",
    "V1StatefulSet",
    "V1StatefulSetCondition",
    "V1StatefulSetList",
    "V1StatefulSetOrdinals",
    "V1StatefulSetPersistentVolumeClaimRetentionPolicy",
    "V1StatefulSetSpec",
    "V1StatefulSetStatus",
    "V1StatefulSetUpdateStrategy",
    "V1Status",
    "V1StatusCause",
    "V1StatusDetails",
    "V1StorageClass",
    "V1StorageClassList",
    "V1StorageOSPersistentVolumeSource",
    "V1StorageOSVolumeSource",
    "V1SubjectAccessReview",
    "V1SubjectAccessReviewSpec",
    "V1SubjectAccessReviewStatus",
    "V1SubjectRulesReviewStatus",
    "V1SuccessPolicy",
    "V1SuccessPolicyRule",
    "V1Sysctl",
    "V1TCPSocketAction",
    "V1Taint",
    "V1TokenRequestSpec",
    "V1TokenRequestStatus",
    "V1TokenReview",
    "V1TokenReviewSpec",
    "V1TokenReviewStatus",
    "V1Toleration",
    "V1TopologySelectorLabelRequirement",
    "V1TopologySelectorTerm",
    "V1TopologySpreadConstraint",
    "V1TypeChecking",
    "V1TypedLocalObjectReference",
    "V1TypedObjectReference",
    "V1UncountedTerminatedPods",
    "V1UserInfo",
    "V1UserSubject",
    "V1ValidatingAdmissionPolicy",
    "V1ValidatingAdmissionPolicyBinding",
    "V1ValidatingAdmissionPolicyBindingList",
    "V1ValidatingAdmissionPolicyBindingSpec",
    "V1ValidatingAdmissionPolicyList",
    "V1ValidatingAdmissionPolicySpec",
    "V1ValidatingAdmissionPolicyStatus",
    "V1ValidatingWebhook",
    "V1ValidatingWebhookConfiguration",
    "V1ValidatingWebhookConfigurationList",
    "V1Validation",
    "V1ValidationRule",
    "V1Variable",
    "V1Volume",
    "V1VolumeAttachment",
    "V1VolumeAttachmentList",
    "V1VolumeAttachmentSource",
    "V1VolumeAttachmentSpec",
    "V1VolumeAttachmentStatus",
    "V1VolumeAttributesClass",
    "V1VolumeAttributesClassList",
    "V1VolumeDevice",
    "V1VolumeError",
    "V1VolumeMount",
    "V1VolumeMountStatus",
    "V1VolumeNodeAffinity",
    "V1VolumeNodeResources",
    "V1VolumeProjection",
    "V1VolumeResourceRequirements",
    "V1VsphereVirtualDiskVolumeSource",
    "V1WatchEvent",
    "V1WebhookConversion",
    "V1WeightedPodAffinityTerm",
    "V1WindowsSecurityContextOptions",
    "V1alpha1ApplyConfiguration",
    "V1alpha1ClusterTrustBundle",
    "V1alpha1ClusterTrustBundleList",
    "V1alpha1ClusterTrustBundleSpec",
    "V1alpha1GroupVersionResource",
    "V1alpha1JSONPatch",
    "V1alpha1MatchCondition",
    "V1alpha1MatchResources",
    "V1alpha1MigrationCondition",
    "V1alpha1MutatingAdmissionPolicy",
    "V1alpha1MutatingAdmissionPolicyBinding",
    "V1alpha1MutatingAdmissionPolicyBindingList",
    "V1alpha1MutatingAdmissionPolicyBindingSpec",
    "V1alpha1MutatingAdmissionPolicyList",
    "V1alpha1MutatingAdmissionPolicySpec",
    "V1alpha1Mutation",
    "V1alpha1NamedRuleWithOperations",
    "V1alpha1ParamKind",
    "V1alpha1ParamRef",
    "V1alpha1PodCertificateRequest",
    "V1alpha1PodCertificateRequestList",
    "V1alpha1PodCertificateRequestSpec",
    "V1alpha1PodCertificateRequestStatus",
    "V1alpha1ServerStorageVersion",
    "V1alpha1StorageVersion",
    "V1alpha1StorageVersionCondition",
    "V1alpha1StorageVersionList",
    "V1alpha1StorageVersionMigration",
    "V1alpha1StorageVersionMigrationList",
    "V1alpha1StorageVersionMigrationSpec",
    "V1alpha1StorageVersionMigrationStatus",
    "V1alpha1StorageVersionStatus",
    "V1alpha1Variable",
    "V1alpha1VolumeAttributesClass",
    "V1alpha1VolumeAttributesClassList",
    "V1alpha2LeaseCandidate",
    "V1alpha2LeaseCandidateList",
    "V1alpha2LeaseCandidateSpec",
    "V1alpha3CELDeviceSelector",
    "V1alpha3DeviceSelector",
    "V1alpha3DeviceTaint",
    "V1alpha3DeviceTaintRule",
    "V1alpha3DeviceTaintRuleList",
    "V1alpha3DeviceTaintRuleSpec",
    "V1alpha3DeviceTaintSelector",
    "V1beta1AllocatedDeviceStatus",
    "V1beta1AllocationResult",
    "V1beta1ApplyConfiguration",
    "V1beta1BasicDevice",
    "V1beta1CELDeviceSelector",
    "V1beta1CapacityRequestPolicy",
    "V1beta1CapacityRequestPolicyRange",
    "V1beta1CapacityRequirements",
    "V1beta1ClusterTrustBundle",
    "V1beta1ClusterTrustBundleList",
    "V1beta1ClusterTrustBundleSpec",
    "V1beta1Counter",
    "V1beta1CounterSet",
    "V1beta1Device",
    "V1beta1DeviceAllocationConfiguration",
    "V1beta1DeviceAllocationResult",
    "V1beta1DeviceAttribute",
    "V1beta1DeviceCapacity",
    "V1beta1DeviceClaim",
    "V1beta1DeviceClaimConfiguration",
    "V1beta1DeviceClass",
    "V1beta1DeviceClassConfiguration",
    "V1beta1DeviceClassList",
    "V1beta1DeviceClassSpec",
    "V1beta1DeviceConstraint",
    "V1beta1DeviceCounterConsumption",
    "V1beta1DeviceRequest",
    "V1beta1DeviceRequestAllocationResult",
    "V1beta1DeviceSelector",
    "V1beta1DeviceSubRequest",
    "V1beta1DeviceTaint",
    "V1beta1DeviceToleration",
    "V1beta1IPAddress",
    "V1beta1IPAddressList",
    "V1beta1IPAddressSpec",
    "V1beta1JSONPatch",
    "V1beta1LeaseCandidate",
    "V1beta1LeaseCandidateList",
    "V1beta1LeaseCandidateSpec",
    "V1beta1MatchCondition",
    "V1beta1MatchResources",
    "V1beta1MutatingAdmissionPolicy",
    "V1beta1MutatingAdmissionPolicyBinding",
    "V1beta1MutatingAdmissionPolicyBindingList",
    "V1beta1MutatingAdmissionPolicyBindingSpec",
    "V1beta1MutatingAdmissionPolicyList",
    "V1beta1MutatingAdmissionPolicySpec",
    "V1beta1Mutation",
    "V1beta1NamedRuleWithOperations",
    "V1beta1NetworkDeviceData",
    "V1beta1OpaqueDeviceConfiguration",
    "V1beta1ParamKind",
    "V1beta1ParamRef",
    "V1beta1ParentReference",
    "V1beta1ResourceClaim",
    "V1beta1ResourceClaimConsumerReference",
    "V1beta1ResourceClaimList",
    "V1beta1ResourceClaimSpec",
    "V1beta1ResourceClaimStatus",
    "V1beta1ResourceClaimTemplate",
    "V1beta1ResourceClaimTemplateList",
    "V1beta1ResourceClaimTemplateSpec",
    "V1beta1ResourcePool",
    "V1beta1ResourceSlice",
    "V1beta1ResourceSliceList",
    "V1beta1ResourceSliceSpec",
    "V1beta1ServiceCIDR",
    "V1beta1ServiceCIDRList",
    "V1beta1ServiceCIDRSpec",
    "V1beta1ServiceCIDRStatus",
    "V1beta1Variable",
    "V1beta1VolumeAttributesClass",
    "V1beta1VolumeAttributesClassList",
    "V1beta2AllocatedDeviceStatus",
    "V1beta2AllocationResult",
    "V1beta2CELDeviceSelector",
    "V1beta2CapacityRequestPolicy",
    "V1beta2CapacityRequestPolicyRange",
    "V1beta2CapacityRequirements",
    "V1beta2Counter",
    "V1beta2CounterSet",
    "V1beta2Device",
    "V1beta2DeviceAllocationConfiguration",
    "V1beta2DeviceAllocationResult",
    "V1beta2DeviceAttribute",
    "V1beta2DeviceCapacity",
    "V1beta2DeviceClaim",
    "V1beta2DeviceClaimConfiguration",
    "V1beta2DeviceClass",
    "V1beta2DeviceClassConfiguration",
    "V1beta2DeviceClassList",
    "V1beta2DeviceClassSpec",
    "V1beta2DeviceConstraint",
    "V1beta2DeviceCounterConsumption",
    "V1beta2DeviceRequest",
    "V1beta2DeviceRequestAllocationResult",
    "V1beta2DeviceSelector",
    "V1beta2DeviceSubRequest",
    "V1beta2DeviceTaint",
    "V1beta2DeviceToleration",
    "V1beta2ExactDeviceRequest",
    "V1beta2NetworkDeviceData",
    "V1beta2OpaqueDeviceConfiguration",
    "V1beta2ResourceClaim",
    "V1beta2ResourceClaimConsumerReference",
    "V1beta2ResourceClaimList",
    "V1beta2ResourceClaimSpec",
    "V1beta2ResourceClaimStatus",
    "V1beta2ResourceClaimTemplate",
    "V1beta2ResourceClaimTemplateList",
    "V1beta2ResourceClaimTemplateSpec",
    "V1beta2ResourcePool",
    "V1beta2ResourceSlice",
    "V1beta2ResourceSliceList",
    "V1beta2ResourceSliceSpec",
    "V2ContainerResourceMetricSource",
    "V2ContainerResourceMetricStatus",
    "V2CrossVersionObjectReference",
    "V2ExternalMetricSource",
    "V2ExternalMetricStatus",
    "V2HPAScalingPolicy",
    "V2HPAScalingRules",
    "V2HorizontalPodAutoscaler",
    "V2HorizontalPodAutoscalerBehavior",
    "V2HorizontalPodAutoscalerCondition",
    "V2HorizontalPodAutoscalerList",
    "V2HorizontalPodAutoscalerSpec",
    "V2HorizontalPodAutoscalerStatus",
    "V2MetricIdentifier",
    "V2MetricSpec",
    "V2MetricStatus",
    "V2MetricTarget",
    "V2MetricValueStatus",
    "V2ObjectMetricSource",
    "V2ObjectMetricStatus",
    "V2PodsMetricSource",
    "V2PodsMetricStatus",
    "V2ResourceMetricSource",
    "V2ResourceMetricStatus",
    "VersionInfo",
)
