from ._settings import CRUD_FILE_ROOT as CRUD_FILE_ROOT
from fastapi import Request as Request, UploadFile as UploadFile

def crud_savefile(file: UploadFile = ...): ...
def crud_original_filename(stored_filename: str) -> str: ...
async def get_form_data(request: Request): ...
