# generated by datamodel-codegen:
#   filename:  pacing.json
#   timestamp: 2025-11-15T22:03:55+00:00

from __future__ import annotations

from enum import Enum


class Pacing(Enum):
    even = "even"
    asap = "asap"
    front_loaded = "front_loaded"
