import logging

logger = logging.getLogger()

columns_and_types = {
    "time_series_start_year": "int16",
    "PERMUTATION_NUMBER": "int32",
    "der_variable_name": "string",
    "rate_specific_domain": "bool",
    "estimate": "float",
    "estimate_unweighted": "float",
    "estimate_type": "string",
    "estimate_type_num": "int8",
    "estimate_type_detail_percentage": "string",
    "estimate_type_detail_rate": "string",
    "estimate_standard_error": "float",
    "estimate_upper_bound": "float",
    "estimate_lower_bound": "float",
    "relative_standard_error": "float",
    "estimate_prb": "float",
    "estimate_bias": "float",
    "estimate_rmse": "float",
    "relative_rmse": "float",
    "suppression_flag_indicator": "bool",
    "der_elig_suppression": "bool",
    "agency_counts": "float",
    "der_rrmse_30": "string",
    "der_rrmse_gt_30_se_estimate_0_2_cond": "bool",
    "der_rrmse_gt_30_se_estimate_0_2_cond_top": "float",
    "der_perm_group_unsuppression_flag": "bool",
    "der_perm_group_suppression_flag": "bool",
    "population_estimate": "float",
    "PRB_ACTUAL": "float",
    "CORRELATION_WITH_PRIOR_YEAR": "float",
    "PROP_ELIG_ORIS_NONZERO_COUNT": "float",
    "estimate_copula": "float"
}

data_dict = {
    "indicator_name": "string",
    "estimate": "float64",
    "estimate_unweighted": "float64",
    "estimate_geographic_location": "string",
    "estimate_type": "string",
    "estimate_type_num": "Int64",
    "estimate_type_detail_percentage": "string",
    "estimate_type_detail_rate": "string",
    "estimate_domain_1": "string",
    "estimate_domain_2": "string",
    "estimate_standard_error": "float64",
    "estimate_upper_bound": "float64",
    "estimate_lower_bound": "float64",
    "relative_standard_error": "float64",
    "analysis_weight_name": "string",
    "estimate_prb": "float64",
    "estimate_bias": "float64",
    "estimate_rmse": "float64",
    "relative_rmse": "float64",
    "suppression_flag_indicator": "float64",
    "der_elig_suppression": "boolean",
    "pop_cov": "float64",
    "agency_counts": "float64",
    "der_rrmse_30": "float64",
    "der_rrmse_gt_30_se_estimate_0_2_cond": "float64",
    "der_rrmse_gt_30_se_estimate_0_2_cond_top": "float64",
    "der_perm_group_unsuppression_flag": "boolean",
    "der_perm_group_suppression_flag": "boolean",
    "population_estimate": "float64",
    "time_series_start_year": "string",
    "full_table": "string",
    "der_variable_name": "string",
    "PERMUTATION_NUMBER": "Int64",
    "PRB_ACTUAL": "float64",
    "POPTOTAL_ORIG_UNIV_ELIG_PERM_AGENCY_MISSING_OVER_10_PERCENT": "boolean",
    "POPTOTAL_ORIG_ELIG_PERM_AGENCY_MISSING_PRINCIPAL_CITY": "boolean",
    "CORRELATION_WITH_PRIOR_YEAR": "float64",
    "PROP_ELIG_ORIS_NONZERO_COUNT": "float64",
    "estimate_copula": "float64"
}
