def padronizar_logradouros(valor: str) -> str: ...
def padronizar_numeros(valor: str) -> str: ...
def padronizar_complementos(valor: str) -> str: ...
def padronizar_bairros(valor: str) -> str: ...
def padronizar_municipios(valor: str) -> str: ...
def padronizar_estados_para_nome(valor: str) -> str: ...
def padronizar_tipo_logradouro(valor: str) -> str: ...
def padronizar_cep_leniente(valor: str) -> str: ...
