from pydantic import BaseModel

class Key(BaseModel):
    prefix: str
    rand_uuid: str
    def __init__(self, prefix: str = "") -> None: ...
    def get_value(self) -> str: ...
    def get_hash(self) -> str: ...
