# Auto-generated from responses_api.py
# Model: OutputItem

# generated by datamodel-codegen:
#   filename:  filtered_openapi.yaml
#   timestamp: 2025-10-18T15:02:20+00:00


from typing import Annotated, Any, TypeVar, Union

from pydantic import Field


# Model dependencies
from .code_interpreter_tool_call import CodeInterpreterToolCall
from .computer_tool_call import ComputerToolCall
from .custom_tool_call import CustomToolCall
from .file_search_tool_call import FileSearchToolCall
from .function_tool_call import FunctionToolCall
from .image_gen_tool_call import ImageGenToolCall
from .local_shell_tool_call import LocalShellToolCall
from .mcp_approval_request import MCPApprovalRequest
from .mcp_list_tools import MCPListTools
from .mcp_tool_call import MCPToolCall
from .output_message import OutputMessage
from .reasoning_item import ReasoningItem
from .web_search_tool_call import WebSearchToolCall


TextFormatT = TypeVar("TextFormatT")

# Using Any for OutputMessage generic parameter since OutputItem is an Annotated type alias
OutputItem = Annotated[
    Union[
        OutputMessage[Any],
        FileSearchToolCall,
        FunctionToolCall,
        WebSearchToolCall,
        ComputerToolCall,
        ReasoningItem,
        ImageGenToolCall,
        CodeInterpreterToolCall,
        LocalShellToolCall,
        MCPToolCall,
        MCPListTools,
        MCPApprovalRequest,
        CustomToolCall,
    ],
    Field(discriminator="type"),
]
