# Auto-generated from responses_api.py
# Model: Type131

# generated by datamodel-codegen:
#   filename:  filtered_openapi.yaml
#   timestamp: 2025-10-18T15:02:20+00:00


from enum import Enum


class Type131(Enum):
    web_search = "web_search"
    web_search_2025_08_26 = "web_search_2025_08_26"
