# Auto-generated from responses_api.py
# Model: ReasoningEffort1

# generated by datamodel-codegen:
#   filename:  filtered_openapi.yaml
#   timestamp: 2025-10-18T15:02:20+00:00


from enum import Enum


class ReasoningEffort1(Enum):
    minimal = "minimal"
    low = "low"
    medium = "medium"
    high = "high"
