# Auto-generated from responses_api.py
# Model: Status2

# generated by datamodel-codegen:
#   filename:  filtered_openapi.yaml
#   timestamp: 2025-10-18T15:02:20+00:00


from enum import Enum


class Status2(Enum):
    in_progress = "in_progress"
    searching = "searching"
    completed = "completed"
    incomplete = "incomplete"
    failed = "failed"
