# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.3.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.


import collections

from sys import version_info as _version_info
if _version_info < (3, 7, 0):
    raise RuntimeError("Python 3.7 or later required")

from . import _ITKCommonPython


from . import _SubdivisionQuadEdgeMeshFilterPython



from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterPython
else:
    import _itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterPython

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


if _swig_python_version_info[0:2] >= (3, 3):
    import collections.abc
else:
    import collections

import itk.itkQuadEdgeMeshPointPython
import itk.itkGeometricalQuadEdgePython
import itk.itkQuadEdgePython
import itk.pyBasePython
import itk.itkPointPython
import itk.vnl_vectorPython
import itk.vnl_matrixPython
import itk.stdcomplexPython
import itk.vnl_vector_refPython
import itk.itkFixedArrayPython
import itk.itkVectorPython
import itk.itkQuadEdgeMeshLineCellPython
import itk.itkQuadEdgeCellTraitsInfoPython
import itk.ITKCommonBasePython
import itk.itkMatrixPython
import itk.itkCovariantVectorPython
import itk.vnl_matrix_fixedPython
import itk.itkArrayPython
import itk.itkTriangleCellSubdivisionQuadEdgeMeshFilterPython
import itk.itkSubdivisionQuadEdgeMeshFilterPython
import itk.itkQuadEdgeMeshToQuadEdgeMeshFilterPython
import itk.itkQuadEdgeMeshBasePython
import itk.itkImagePython
import itk.itkIndexPython
import itk.itkOffsetPython
import itk.itkSizePython
import itk.itkImageRegionPython
import itk.itkSymmetricSecondRankTensorPython
import itk.itkRGBAPixelPython
import itk.itkRGBPixelPython
import itk.itkMapContainerPython
import itk.itkVectorContainerPython
import itk.itkContinuousIndexPython

def itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD2_New():
    return itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD2.New()

class itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD2(itk.itkTriangleCellSubdivisionQuadEdgeMeshFilterPython.itkTriangleCellSubdivisionQuadEdgeMeshFilterQEMD2):
    r"""Proxy of C++ itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD2 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    @staticmethod
    def __New_orig__():
        r"""__New_orig__() -> itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD2_Pointer"""
        return _itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterPython.itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD2___New_orig__()

    def Clone(self):
        r"""Clone(self) -> itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD2_Pointer"""
        return _itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterPython.itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD2_Clone(self)
    __swig_destroy__ = _itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterPython.delete_itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD2

    @staticmethod
    def cast(obj):
        r"""
        cast(obj) -> itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD2

        Parameters
        ----------
        obj: itkLightObject *

        """
        return _itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterPython.itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD2_cast(obj)

    def New(*args, **kargs):
        """New() -> itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD2

        Create a new object of the class itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD2.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD2.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD2.__New_orig__()
        from itk.support import template_class
        template_class.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD2 in _itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterPython:
_itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterPython.itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD2_swigregister(itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD2)

def itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD3_New():
    return itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD3.New()

class itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD3(itk.itkTriangleCellSubdivisionQuadEdgeMeshFilterPython.itkTriangleCellSubdivisionQuadEdgeMeshFilterQEMD3):
    r"""Proxy of C++ itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD3 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    @staticmethod
    def __New_orig__():
        r"""__New_orig__() -> itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD3_Pointer"""
        return _itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterPython.itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD3___New_orig__()

    def Clone(self):
        r"""Clone(self) -> itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD3_Pointer"""
        return _itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterPython.itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD3_Clone(self)
    __swig_destroy__ = _itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterPython.delete_itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD3

    @staticmethod
    def cast(obj):
        r"""
        cast(obj) -> itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD3

        Parameters
        ----------
        obj: itkLightObject *

        """
        return _itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterPython.itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD3_cast(obj)

    def New(*args, **kargs):
        """New() -> itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD3

        Create a new object of the class itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD3.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD3.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD3.__New_orig__()
        from itk.support import template_class
        template_class.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD3 in _itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterPython:
_itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterPython.itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD3_swigregister(itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD3)

def itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD4_New():
    return itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD4.New()

class itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD4(itk.itkTriangleCellSubdivisionQuadEdgeMeshFilterPython.itkTriangleCellSubdivisionQuadEdgeMeshFilterQEMD4):
    r"""Proxy of C++ itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD4 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    @staticmethod
    def __New_orig__():
        r"""__New_orig__() -> itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD4_Pointer"""
        return _itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterPython.itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD4___New_orig__()

    def Clone(self):
        r"""Clone(self) -> itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD4_Pointer"""
        return _itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterPython.itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD4_Clone(self)
    __swig_destroy__ = _itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterPython.delete_itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD4

    @staticmethod
    def cast(obj):
        r"""
        cast(obj) -> itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD4

        Parameters
        ----------
        obj: itkLightObject *

        """
        return _itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterPython.itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD4_cast(obj)

    def New(*args, **kargs):
        """New() -> itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD4

        Create a new object of the class itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD4 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD4.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD4.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD4.__New_orig__()
        from itk.support import template_class
        template_class.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD4 in _itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterPython:
_itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterPython.itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD4_swigregister(itkLoopTriangleCellSubdivisionQuadEdgeMeshFilterQEMD4)

from itk.support import helpers
import itk.support.types as itkt
from typing import Sequence, Tuple, Union

@helpers.accept_array_like_xarray_torch
def loop_triangle_cell_subdivision_quad_edge_mesh_filter(*args: itkt.Mesh,  cells_to_be_subdivided=..., output: itkt.QuadEdgeMesh=...,**kwargs)-> itkt.MeshSourceReturn:
    """Functional interface for LoopTriangleCellSubdivisionQuadEdgeMeshFilter"""
    import itk

    kwarg_typehints = { 'cells_to_be_subdivided':cells_to_be_subdivided,'output':output }
    specified_kwarg_typehints = { k:v for (k,v) in kwarg_typehints.items() if kwarg_typehints[k] is not ... }
    kwargs.update(specified_kwarg_typehints)


    instance = itk.LoopTriangleCellSubdivisionQuadEdgeMeshFilter.New(*args, **kwargs)

    return instance.__internal_call__()

def loop_triangle_cell_subdivision_quad_edge_mesh_filter_init_docstring():
    import itk
    from itk.support import template_class

    filter_class = itk.SubdivisionQuadEdgeMeshFilter.LoopTriangleCellSubdivisionQuadEdgeMeshFilter
    loop_triangle_cell_subdivision_quad_edge_mesh_filter.process_object = filter_class
    is_template = isinstance(filter_class, template_class.itkTemplate)
    if is_template:
        filter_object = filter_class.values()[0]
    else:
        filter_object = filter_class

    loop_triangle_cell_subdivision_quad_edge_mesh_filter.__doc__ = filter_object.__doc__



