# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from agentic_mesh_protocol.cost.v1 import cost_pb2 as agentic__mesh__protocol_dot_cost_dot_v1_dot_cost__pb2


class CostServiceStub(object):
    """CostService provides operations for tracking and querying operational costs.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddCost = channel.unary_unary(
                '/agentic_mesh_protocol.cost.v1.CostService/AddCost',
                request_serializer=agentic__mesh__protocol_dot_cost_dot_v1_dot_cost__pb2.AddCostRequest.SerializeToString,
                response_deserializer=agentic__mesh__protocol_dot_cost_dot_v1_dot_cost__pb2.AddCostResponse.FromString,
                _registered_method=True)
        self.GetCost = channel.unary_unary(
                '/agentic_mesh_protocol.cost.v1.CostService/GetCost',
                request_serializer=agentic__mesh__protocol_dot_cost_dot_v1_dot_cost__pb2.GetCostRequest.SerializeToString,
                response_deserializer=agentic__mesh__protocol_dot_cost_dot_v1_dot_cost__pb2.GetCostResponse.FromString,
                _registered_method=True)
        self.GetCosts = channel.unary_unary(
                '/agentic_mesh_protocol.cost.v1.CostService/GetCosts',
                request_serializer=agentic__mesh__protocol_dot_cost_dot_v1_dot_cost__pb2.GetCostsRequest.SerializeToString,
                response_deserializer=agentic__mesh__protocol_dot_cost_dot_v1_dot_cost__pb2.GetCostsResponse.FromString,
                _registered_method=True)


class CostServiceServicer(object):
    """CostService provides operations for tracking and querying operational costs.
    """

    def AddCost(self, request, context):
        """AddCost records a new cost entry for a mission.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCost(self, request, context):
        """GetCost retrieves cost entries by name within a mission.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCosts(self, request, context):
        """GetCosts retrieves multiple cost entries with optional filtering and pagination.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CostServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddCost': grpc.unary_unary_rpc_method_handler(
                    servicer.AddCost,
                    request_deserializer=agentic__mesh__protocol_dot_cost_dot_v1_dot_cost__pb2.AddCostRequest.FromString,
                    response_serializer=agentic__mesh__protocol_dot_cost_dot_v1_dot_cost__pb2.AddCostResponse.SerializeToString,
            ),
            'GetCost': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCost,
                    request_deserializer=agentic__mesh__protocol_dot_cost_dot_v1_dot_cost__pb2.GetCostRequest.FromString,
                    response_serializer=agentic__mesh__protocol_dot_cost_dot_v1_dot_cost__pb2.GetCostResponse.SerializeToString,
            ),
            'GetCosts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCosts,
                    request_deserializer=agentic__mesh__protocol_dot_cost_dot_v1_dot_cost__pb2.GetCostsRequest.FromString,
                    response_serializer=agentic__mesh__protocol_dot_cost_dot_v1_dot_cost__pb2.GetCostsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agentic_mesh_protocol.cost.v1.CostService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agentic_mesh_protocol.cost.v1.CostService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CostService(object):
    """CostService provides operations for tracking and querying operational costs.
    """

    @staticmethod
    def AddCost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentic_mesh_protocol.cost.v1.CostService/AddCost',
            agentic__mesh__protocol_dot_cost_dot_v1_dot_cost__pb2.AddCostRequest.SerializeToString,
            agentic__mesh__protocol_dot_cost_dot_v1_dot_cost__pb2.AddCostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentic_mesh_protocol.cost.v1.CostService/GetCost',
            agentic__mesh__protocol_dot_cost_dot_v1_dot_cost__pb2.GetCostRequest.SerializeToString,
            agentic__mesh__protocol_dot_cost_dot_v1_dot_cost__pb2.GetCostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCosts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentic_mesh_protocol.cost.v1.CostService/GetCosts',
            agentic__mesh__protocol_dot_cost_dot_v1_dot_cost__pb2.GetCostsRequest.SerializeToString,
            agentic__mesh__protocol_dot_cost_dot_v1_dot_cost__pb2.GetCostsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
