from enum import Enum


class AssetsPublicControllerListAssetsAssetProvider(str, Enum):
    AGENT = "AGENT"
    AWS = "AWS"
    AWS_GOV_CLOUD = "AWS_GOV_CLOUD"
    AWS_ORG_UNITS = "AWS_ORG_UNITS"
    AZURE = "AZURE"
    CSV_IDP = "CSV_IDP"
    DRATA = "DRATA"
    DRATA_DEV = "DRATA_DEV"
    GCP = "GCP"
    GOOGLE = "GOOGLE"
    HEXNODE_UEM = "HEXNODE_UEM"
    INTUNE = "INTUNE"
    INTUNE_GCC_HIGH = "INTUNE_GCC_HIGH"
    JAMF = "JAMF"
    JUMPCLOUD = "JUMPCLOUD"
    KANDJI = "KANDJI"
    KOLIDE = "KOLIDE"
    MERGEDEV_CYBERARK = "MERGEDEV_CYBERARK"
    MERGEDEV_JUMPCLOUD = "MERGEDEV_JUMPCLOUD"
    MERGEDEV_ONELOGIN = "MERGEDEV_ONELOGIN"
    MERGEDEV_PINGONE = "MERGEDEV_PINGONE"
    MICROSOFT_365 = "MICROSOFT_365"
    MICROSOFT_365_GCC_HIGH = "MICROSOFT_365_GCC_HIGH"
    OKTA_IDENTITY = "OKTA_IDENTITY"
    RIPPLING = "RIPPLING"
    WORKSPACE_ONE = "WORKSPACE_ONE"

    def __str__(self) -> str:
        return str(self.value)
