from enum import Enum


class GRCPublicControllerGetControlsCobitItem(str, Enum):
    COBIT_ALIGN_PLAN_AND_ORGANIZE = "COBIT_ALIGN_PLAN_AND_ORGANIZE"
    COBIT_BUILD_ACQUIRE_AND_IMPLEMENT = "COBIT_BUILD_ACQUIRE_AND_IMPLEMENT"
    COBIT_DELIVER_SERVICE_AND_SUPPORT = "COBIT_DELIVER_SERVICE_AND_SUPPORT"
    COBIT_EVALUATE_DIRECT_AND_MONITOR = "COBIT_EVALUATE_DIRECT_AND_MONITOR"
    COBIT_MONITOR_EVALUATE_AND_ASSESS = "COBIT_MONITOR_EVALUATE_AND_ASSESS"

    def __str__(self) -> str:
        return str(self.value)
