from enum import Enum


class GRCPublicControllerGetControlsAssessmentFactorsItem(str, Enum):
    FFIEC_CONNECTIONS = "FFIEC_CONNECTIONS"
    FFIEC_CORRECTIVE_CONTROLS = "FFIEC_CORRECTIVE_CONTROLS"
    FFIEC_DETECTION_RESPONSE_AND_MITIGATION = "FFIEC_DETECTION_RESPONSE_AND_MITIGATION"
    FFIEC_DETECTIVE_CONTROLS = "FFIEC_DETECTIVE_CONTROLS"
    FFIEC_ESCALATION_AND_REPORTING = "FFIEC_ESCALATION_AND_REPORTING"
    FFIEC_GOVERNANCE = "FFIEC_GOVERNANCE"
    FFIEC_INCIDENT_RESILIENCE_PLANNING_AND_STRATEGY = "FFIEC_INCIDENT_RESILIENCE_PLANNING_AND_STRATEGY"
    FFIEC_INFORMATION_SHARING = "FFIEC_INFORMATION_SHARING"
    FFIEC_MONITORING_AND_ANALYZING = "FFIEC_MONITORING_AND_ANALYZING"
    FFIEC_PREVENTATIVE_CONTROLS = "FFIEC_PREVENTATIVE_CONTROLS"
    FFIEC_RELATIONSHIP_MANAGEMENT = "FFIEC_RELATIONSHIP_MANAGEMENT"
    FFIEC_RESOURCES = "FFIEC_RESOURCES"
    FFIEC_RISK_MANAGEMENT = "FFIEC_RISK_MANAGEMENT"
    FFIEC_THREAT_INTELLIGENCE = "FFIEC_THREAT_INTELLIGENCE"
    FFIEC_TRAINING_AND_CULTURE = "FFIEC_TRAINING_AND_CULTURE"

    def __str__(self) -> str:
        return str(self.value)
