from enum import Enum


class GRCPublicControllerGetControlsDomainsItem(str, Enum):
    FFIEC_CYBERSECURITY_CONTROLS = "FFIEC_CYBERSECURITY_CONTROLS"
    FFIEC_CYBER_INCIDENT_MANAGEMENT_AND_RESILIENCE = "FFIEC_CYBER_INCIDENT_MANAGEMENT_AND_RESILIENCE"
    FFIEC_CYBER_RISK_MANAGEMENT_AND_OVERSIGHT = "FFIEC_CYBER_RISK_MANAGEMENT_AND_OVERSIGHT"
    FFIEC_EXTERNAL_DEPENDENCY_MANAGEMENT = "FFIEC_EXTERNAL_DEPENDENCY_MANAGEMENT"
    FFIEC_THREAT_INTELLIGENCE_AND_COLLABORATION = "FFIEC_THREAT_INTELLIGENCE_AND_COLLABORATION"

    def __str__(self) -> str:
        return str(self.value)
