from enum import Enum


class PersonnelPublicControllerListPersonnelSort(str, Enum):
    ACCEPTED_POLICIES = "ACCEPTED_POLICIES"
    AGENT_INSTALLED = "AGENT_INSTALLED"
    ANTIVIRUS = "ANTIVIRUS"
    APPS_COUNT = "APPS_COUNT"
    AUTO_UPDATES = "AUTO_UPDATES"
    BG_CHECK = "BG_CHECK"
    EMPLOYMENT_STATUS = "EMPLOYMENT_STATUS"
    FULL_COMPLIANCE = "FULL_COMPLIANCE"
    HDD_ENCRYPTION = "HDD_ENCRYPTION"
    HIPAA_TRAINING = "HIPAA_TRAINING"
    IDENTITY_MFA = "IDENTITY_MFA"
    LOCK_SCREEN = "LOCK_SCREEN"
    NAME = "NAME"
    NIST_AI_TRAINING = "NIST_AI_TRAINING"
    OFFBOARDING = "OFFBOARDING"
    OS_VERSION = "OS_VERSION"
    PASSWORD_MANAGER = "PASSWORD_MANAGER"
    SECURITY_TRAINING = "SECURITY_TRAINING"
    SEPARATION_DATE = "SEPARATION_DATE"
    SERIAL_NUM = "SERIAL_NUM"
    START_DATE = "START_DATE"

    def __str__(self) -> str:
        return str(self.value)
