from enum import Enum


class TrustCenterPublicControllerGetReportReportType(str, Enum):
    ACCESS_REQUESTS_APPROVED_DOMAINS = "ACCESS_REQUESTS_APPROVED_DOMAINS"
    ACCESS_REQUESTS_APPROVED_EMAILS = "ACCESS_REQUESTS_APPROVED_EMAILS"
    ACCESS_REQUESTS_LIST = "ACCESS_REQUESTS_LIST"
    DOCUMENT_REQUESTS_FILE_NAME = "DOCUMENT_REQUESTS_FILE_NAME"
    PRO_REVENUE_INFLUENCED = "PRO_REVENUE_INFLUENCED"
    SUMMARY = "SUMMARY"

    def __str__(self) -> str:
        return str(self.value)
