from enum import Enum


class UsersPublicControllerGetAllDocumentsType(str, Enum):
    ANTIVIRUS_EVIDENCE = "ANTIVIRUS_EVIDENCE"
    AUTO_UPDATES_EVIDENCE = "AUTO_UPDATES_EVIDENCE"
    HARD_DRIVE_ENCRYPTION_EVIDENCE = "HARD_DRIVE_ENCRYPTION_EVIDENCE"
    HIPAA_TRAINING_EVIDENCE = "HIPAA_TRAINING_EVIDENCE"
    LOCK_SCREEN_EVIDENCE = "LOCK_SCREEN_EVIDENCE"
    MFA_EVIDENCE = "MFA_EVIDENCE"
    NIST_AI_TRAINING_EVIDENCE = "NIST_AI_TRAINING_EVIDENCE"
    OFFBOARDING_EVIDENCE = "OFFBOARDING_EVIDENCE"
    PASSWORD_MANAGER_EVIDENCE = "PASSWORD_MANAGER_EVIDENCE"
    SEC_TRAINING = "SEC_TRAINING"

    def __str__(self) -> str:
        return str(self.value)
