from enum import Enum


class UsersPublicControllerListUsersExcludeRolesType0Item(str, Enum):
    ACT_AS_READ_ONLY = "ACT_AS_READ_ONLY"
    ADMIN = "ADMIN"
    APP = "APP"
    AUDITOR = "AUDITOR"
    CONTROL_MANAGER = "CONTROL_MANAGER"
    DEVOPS_ENGINEER = "DEVOPS_ENGINEER"
    EMPLOYEE = "EMPLOYEE"
    KNOWLEDGE_BASE = "KNOWLEDGE_BASE"
    PEOPLE_OPS = "PEOPLE_OPS"
    POLICY_MANAGER = "POLICY_MANAGER"
    REVIEWER = "REVIEWER"
    RISK_MANAGER = "RISK_MANAGER"
    SERVICE_USER = "SERVICE_USER"
    TECHGOV = "TECHGOV"
    TRUST_CENTER_MANAGER = "TRUST_CENTER_MANAGER"
    TRUST_CENTER_REVIEWER = "TRUST_CENTER_REVIEWER"
    WORKSPACE_ADMINISTRATOR = "WORKSPACE_ADMINISTRATOR"

    def __str__(self) -> str:
        return str(self.value)
