from enum import Enum


class VendorDocumentRequestPublicDtoType(str, Enum):
    BRIDGE_LETTER = "BRIDGE_LETTER"
    COMPLIANCE_REPORT = "COMPLIANCE_REPORT"
    COMPLIANCE_REPORT_REVIEW = "COMPLIANCE_REPORT_REVIEW"
    QUESTIONNAIRE_ATTACHMENT = "QUESTIONNAIRE_ATTACHMENT"
    SOC_DOCUMENT = "SOC_DOCUMENT"
    UPLOADED_COMPLIANCE_REPORT_REVIEW = "UPLOADED_COMPLIANCE_REPORT_REVIEW"

    def __str__(self) -> str:
        return str(self.value)
