from enum import Enum


class VendorRequestPublicDtoDataAccessedOrProcessedListType0Item(str, Enum):
    CARDHOLDER_DATA = "CARDHOLDER_DATA"
    CONTROLLED_UNCLASSIFIED = "CONTROLLED_UNCLASSIFIED"
    EMPLOYEE_PERSONNEL = "EMPLOYEE_PERSONNEL"
    FINANCIAL = "FINANCIAL"
    GENERAL = "GENERAL"
    OTHER_PERSONAL_OR_SENSITIVE = "OTHER_PERSONAL_OR_SENSITIVE"
    PERSONAL_IDENTIFIABLE_INFORMATION = "PERSONAL_IDENTIFIABLE_INFORMATION"
    PROPRIETARY = "PROPRIETARY"
    PROTECTED_HEALTH_INFORMATION = "PROTECTED_HEALTH_INFORMATION"
    PUBLIC = "PUBLIC"

    def __str__(self) -> str:
        return str(self.value)
