# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.3.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.


import collections

from sys import version_info as _version_info
if _version_info < (3, 7, 0):
    raise RuntimeError("Python 3.7 or later required")

from . import _ITKCommonPython


from . import _SubdivisionQuadEdgeMeshFilterPython



from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterPython
else:
    import _itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterPython

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


if _swig_python_version_info[0:2] >= (3, 3):
    import collections.abc
else:
    import collections

import itk.itkTriangleEdgeCellSubdivisionQuadEdgeMeshFilterPython
import itk.itkQuadEdgeMeshLineCellPython
import itk.itkGeometricalQuadEdgePython
import itk.itkQuadEdgePython
import itk.pyBasePython
import itk.itkArrayPython
import itk.vnl_vectorPython
import itk.vnl_matrixPython
import itk.stdcomplexPython
import itk.itkQuadEdgeCellTraitsInfoPython
import itk.itkQuadEdgeMeshPointPython
import itk.itkPointPython
import itk.vnl_vector_refPython
import itk.itkVectorPython
import itk.itkFixedArrayPython
import itk.ITKCommonBasePython
import itk.itkMatrixPython
import itk.itkCovariantVectorPython
import itk.vnl_matrix_fixedPython
import itk.itkTriangleCellSubdivisionQuadEdgeMeshFilterPython
import itk.itkSubdivisionQuadEdgeMeshFilterPython
import itk.itkQuadEdgeMeshToQuadEdgeMeshFilterPython
import itk.itkQuadEdgeMeshBasePython
import itk.itkMapContainerPython
import itk.itkImagePython
import itk.itkOffsetPython
import itk.itkSizePython
import itk.itkRGBPixelPython
import itk.itkImageRegionPython
import itk.itkIndexPython
import itk.itkRGBAPixelPython
import itk.itkSymmetricSecondRankTensorPython
import itk.itkVectorContainerPython
import itk.itkContinuousIndexPython

def itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD2_New():
    return itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD2.New()

class itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD2(itk.itkTriangleEdgeCellSubdivisionQuadEdgeMeshFilterPython.itkTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD2):
    r"""Proxy of C++ itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD2 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    @staticmethod
    def __New_orig__():
        r"""__New_orig__() -> itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD2_Pointer"""
        return _itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterPython.itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD2___New_orig__()

    def Clone(self):
        r"""Clone(self) -> itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD2_Pointer"""
        return _itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterPython.itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD2_Clone(self)
    __swig_destroy__ = _itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterPython.delete_itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD2

    @staticmethod
    def cast(obj):
        r"""
        cast(obj) -> itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD2

        Parameters
        ----------
        obj: itkLightObject *

        """
        return _itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterPython.itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD2_cast(obj)

    def New(*args, **kargs):
        """New() -> itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD2

        Create a new object of the class itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD2.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD2.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD2.__New_orig__()
        from itk.support import template_class
        template_class.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD2 in _itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterPython:
_itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterPython.itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD2_swigregister(itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD2)

def itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD3_New():
    return itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD3.New()

class itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD3(itk.itkTriangleEdgeCellSubdivisionQuadEdgeMeshFilterPython.itkTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD3):
    r"""Proxy of C++ itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD3 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    @staticmethod
    def __New_orig__():
        r"""__New_orig__() -> itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD3_Pointer"""
        return _itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterPython.itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD3___New_orig__()

    def Clone(self):
        r"""Clone(self) -> itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD3_Pointer"""
        return _itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterPython.itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD3_Clone(self)
    __swig_destroy__ = _itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterPython.delete_itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD3

    @staticmethod
    def cast(obj):
        r"""
        cast(obj) -> itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD3

        Parameters
        ----------
        obj: itkLightObject *

        """
        return _itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterPython.itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD3_cast(obj)

    def New(*args, **kargs):
        """New() -> itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD3

        Create a new object of the class itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD3.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD3.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD3.__New_orig__()
        from itk.support import template_class
        template_class.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD3 in _itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterPython:
_itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterPython.itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD3_swigregister(itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD3)

def itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD4_New():
    return itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD4.New()

class itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD4(itk.itkTriangleEdgeCellSubdivisionQuadEdgeMeshFilterPython.itkTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD4):
    r"""Proxy of C++ itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD4 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    @staticmethod
    def __New_orig__():
        r"""__New_orig__() -> itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD4_Pointer"""
        return _itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterPython.itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD4___New_orig__()

    def Clone(self):
        r"""Clone(self) -> itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD4_Pointer"""
        return _itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterPython.itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD4_Clone(self)
    __swig_destroy__ = _itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterPython.delete_itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD4

    @staticmethod
    def cast(obj):
        r"""
        cast(obj) -> itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD4

        Parameters
        ----------
        obj: itkLightObject *

        """
        return _itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterPython.itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD4_cast(obj)

    def New(*args, **kargs):
        """New() -> itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD4

        Create a new object of the class itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD4 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD4.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD4.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD4.__New_orig__()
        from itk.support import template_class
        template_class.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD4 in _itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterPython:
_itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterPython.itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD4_swigregister(itkLinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilterQEMD4)

from itk.support import helpers
import itk.support.types as itkt
from typing import Sequence, Tuple, Union

@helpers.accept_array_like_xarray_torch
def linear_triangle_edge_cell_subdivision_quad_edge_mesh_filter(*args: itkt.Mesh,  cells_to_be_subdivided=..., output: itkt.QuadEdgeMesh=...,**kwargs)-> itkt.MeshSourceReturn:
    """Functional interface for LinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilter"""
    import itk

    kwarg_typehints = { 'cells_to_be_subdivided':cells_to_be_subdivided,'output':output }
    specified_kwarg_typehints = { k:v for (k,v) in kwarg_typehints.items() if kwarg_typehints[k] is not ... }
    kwargs.update(specified_kwarg_typehints)


    instance = itk.LinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilter.New(*args, **kwargs)

    return instance.__internal_call__()

def linear_triangle_edge_cell_subdivision_quad_edge_mesh_filter_init_docstring():
    import itk
    from itk.support import template_class

    filter_class = itk.SubdivisionQuadEdgeMeshFilter.LinearTriangleEdgeCellSubdivisionQuadEdgeMeshFilter
    linear_triangle_edge_cell_subdivision_quad_edge_mesh_filter.process_object = filter_class
    is_template = isinstance(filter_class, template_class.itkTemplate)
    if is_template:
        filter_object = filter_class.values()[0]
    else:
        filter_object = filter_class

    linear_triangle_edge_cell_subdivision_quad_edge_mesh_filter.__doc__ = filter_object.__doc__



