// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: common/v1/capability.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Capability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`                    // Id of the agent (either an operator or robot)
	PartId        string                 `protobuf:"bytes,2,opt,name=part_id,json=partId,proto3" json:"part_id,omitempty"`                       // Id of the part that the agent can handle
	EstimatedTime int64                  `protobuf:"varint,3,opt,name=estimated_time,json=estimatedTime,proto3" json:"estimated_time,omitempty"` // Estimated time to complete a task with that part
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capability) Reset() {
	*x = Capability{}
	mi := &file_common_v1_capability_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capability) ProtoMessage() {}

func (x *Capability) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_capability_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capability.ProtoReflect.Descriptor instead.
func (*Capability) Descriptor() ([]byte, []int) {
	return file_common_v1_capability_proto_rawDescGZIP(), []int{0}
}

func (x *Capability) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Capability) GetPartId() string {
	if x != nil {
		return x.PartId
	}
	return ""
}

func (x *Capability) GetEstimatedTime() int64 {
	if x != nil {
		return x.EstimatedTime
	}
	return 0
}

type Capabilities struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capabilities  []*Capability          `protobuf:"bytes,1,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capabilities) Reset() {
	*x = Capabilities{}
	mi := &file_common_v1_capability_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capabilities) ProtoMessage() {}

func (x *Capabilities) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_capability_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capabilities.ProtoReflect.Descriptor instead.
func (*Capabilities) Descriptor() ([]byte, []int) {
	return file_common_v1_capability_proto_rawDescGZIP(), []int{1}
}

func (x *Capabilities) GetCapabilities() []*Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

var File_common_v1_capability_proto protoreflect.FileDescriptor

const file_common_v1_capability_proto_rawDesc = "" +
	"\n" +
	"\x1acommon/v1/capability.proto\x12\tcommon.v1\"g\n" +
	"\n" +
	"Capability\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x17\n" +
	"\apart_id\x18\x02 \x01(\tR\x06partId\x12%\n" +
	"\x0eestimated_time\x18\x03 \x01(\x03R\restimatedTime\"I\n" +
	"\fCapabilities\x129\n" +
	"\fcapabilities\x18\x01 \x03(\v2\x15.common.v1.CapabilityR\fcapabilitiesB\xa7\x01\n" +
	"\rcom.common.v1B\x0fCapabilityProtoP\x01Z7github.com/cobotar/protocol/messages/common/v1;commonv1\xa2\x02\x03CXX\xaa\x02\x12Messages.Common.V1\xca\x02\tCommon\\V1\xe2\x02\x15Common\\V1\\GPBMetadata\xea\x02\n" +
	"Common::V1b\x06proto3"

var (
	file_common_v1_capability_proto_rawDescOnce sync.Once
	file_common_v1_capability_proto_rawDescData []byte
)

func file_common_v1_capability_proto_rawDescGZIP() []byte {
	file_common_v1_capability_proto_rawDescOnce.Do(func() {
		file_common_v1_capability_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_capability_proto_rawDesc), len(file_common_v1_capability_proto_rawDesc)))
	})
	return file_common_v1_capability_proto_rawDescData
}

var file_common_v1_capability_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_v1_capability_proto_goTypes = []any{
	(*Capability)(nil),   // 0: common.v1.Capability
	(*Capabilities)(nil), // 1: common.v1.Capabilities
}
var file_common_v1_capability_proto_depIdxs = []int32{
	0, // 0: common.v1.Capabilities.capabilities:type_name -> common.v1.Capability
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_v1_capability_proto_init() }
func file_common_v1_capability_proto_init() {
	if File_common_v1_capability_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_capability_proto_rawDesc), len(file_common_v1_capability_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_capability_proto_goTypes,
		DependencyIndexes: file_common_v1_capability_proto_depIdxs,
		MessageInfos:      file_common_v1_capability_proto_msgTypes,
	}.Build()
	File_common_v1_capability_proto = out.File
	file_common_v1_capability_proto_goTypes = nil
	file_common_v1_capability_proto_depIdxs = nil
}
