# coding: utf-8

"""
    EDMS Client Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: development
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edms_client_api.models.aggregation_type import AggregationType

class TestAggregationType(unittest.TestCase):
    """AggregationType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAggregationType(self):
        """Test AggregationType"""
        # inst = AggregationType()

if __name__ == '__main__':
    unittest.main()
