# coding: utf-8

"""
    SatNOGS DB

    SatNOGS DB is a crowdsourced database of details about orbital                     satellites and data collected from them.

    The version of the OpenAPI document: 1.1
    Contact: dev@satnogs.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from satnogsdbapiclient.models.optical_observation_create import OpticalObservationCreate

class TestOpticalObservationCreate(unittest.TestCase):
    """OpticalObservationCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OpticalObservationCreate:
        """Test OpticalObservationCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OpticalObservationCreate`
        """
        model = OpticalObservationCreate()
        if include_optional:
            return OpticalObservationCreate(
                data = '',
                diagnostic_plot = ''
            )
        else:
            return OpticalObservationCreate(
                data = '',
                diagnostic_plot = '',
        )
        """

    def testOpticalObservationCreate(self):
        """Test OpticalObservationCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
