# coding: utf-8

"""
    SatNOGS DB

    SatNOGS DB is a crowdsourced database of details about orbital                     satellites and data collected from them.

    The version of the OpenAPI document: 1.1
    Contact: dev@satnogs.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from satnogsdbapiclient.models.paginated_telemetry_list import PaginatedTelemetryList

class TestPaginatedTelemetryList(unittest.TestCase):
    """PaginatedTelemetryList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedTelemetryList:
        """Test PaginatedTelemetryList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedTelemetryList`
        """
        model = PaginatedTelemetryList()
        if include_optional:
            return PaginatedTelemetryList(
                next = 'http://api.example.org/accounts/?cursor=cD00ODY%3D"',
                previous = 'http://api.example.org/accounts/?cursor=cj0xJnA9NDg3',
                results = [
                    satnogsdbapiclient.models.telemetry.Telemetry(
                        sat_id = '', 
                        norad_cat_id = 56, 
                        transmitter = '', 
                        decoded = '', 
                        frame = '', 
                        version = '', 
                        observation_id = 56, 
                        station_id = 56, 
                        associated_satellites = {
                            'key' : null
                            }, )
                    ]
            )
        else:
            return PaginatedTelemetryList(
                results = [
                    satnogsdbapiclient.models.telemetry.Telemetry(
                        sat_id = '', 
                        norad_cat_id = 56, 
                        transmitter = '', 
                        decoded = '', 
                        frame = '', 
                        version = '', 
                        observation_id = 56, 
                        station_id = 56, 
                        associated_satellites = {
                            'key' : null
                            }, )
                    ],
        )
        """

    def testPaginatedTelemetryList(self):
        """Test PaginatedTelemetryList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
