"""
特征配置模块

定义各类水质指标对应的特征计算公式和参数。
可被 Nuitka 编译成二进制。
"""

# 特征配置
FEATURES_CONFIG = {
    "model_params": {"max_features": 5, "min_samples": 6},
    "features": {
        "STZ1": {
            "name": "STZ1",
            "formula": "sum(B1, B2)/sum(B3, B4)",
            "bands": {"B1": 400, "B2": 740, "B3": 400, "B4": 850},
        },
        "STZ2": {
            "name": "STZ2",
            "formula": "sum(B1, B2)/sum(B3, B4)",
            "bands": {"B1": 740, "B2": 850, "B3": 400, "B4": 850},
        },
        "STZ3": {
            "name": "STZ3",
            "formula": "sum(B1, B2)/sum(B3, B4)",
            "bands": {"B1": 400, "B2": 500, "B3": 400, "B4": 850},
        },
        "STZ4": {
            "name": "STZ4",
            "formula": "sum(B1, B2)/sum(B3, B4)",
            "bands": {"B1": 500, "B2": 600, "B3": 400, "B4": 850},
        },
        "STZ5": {
            "name": "STZ5",
            "formula": "sum(B1, B2)/sum(B3, B4)",
            "bands": {"B1": 600, "B2": 655, "B3": 400, "B4": 850},
        },
        "STZ6": {
            "name": "STZ6",
            "formula": "sum(B1, B2)/sum(B3, B4)",
            "bands": {"B1": 655, "B2": 700, "B3": 400, "B4": 850},
        },
        "STZ7": {
            "name": "STZ7",
            "formula": "sum(B1, B2)/sum(B3, B4)",
            "bands": {"B1": 700, "B2": 740, "B3": 400, "B4": 850},
        },
        "STZ8": {
            "name": "STZ8",
            "formula": "sum(B1, B2)/sum(B3, B4)",
            "bands": {"B1": 740, "B2": 810, "B3": 400, "B4": 850},
        },
        "STZ9": {
            "name": "STZ9",
            "formula": "sum(B1, B2)/sum(B3, B4)",
            "bands": {"B1": 810, "B2": 850, "B3": 400, "B4": 850},
        },
        "STZ10": {"name": "STZ10", "formula": "tris(z)/tris(y)", "bands": {}},
        "STZ11": {"name": "STZ11", "formula": "tris(z)/tris(x)", "bands": {}},
        "STZ12": {"name": "STZ12", "formula": "tris(y)/tris(x)", "bands": {}},
        "STZ13": {
            "name": "STZ13",
            "formula": "(mean(B1, B2)-mean(B3, " "B4))/mean(B5, B6)",
            "bands": {"B1": 500, "B2": 600, "B3": 600, "B4": 700, "B5": 750, "B6": 850},
        },
        "STZ14": {
            "name": "STZ14",
            "formula": "(abs((ref(B1)+ref(B2))*45/2-sum(B3, " "B4))/45)/mean(B5, B6)",
            "bands": {"B1": 655, "B2": 700, "B3": 655, "B4": 700, "B5": 750, "B6": 850},
        },
        "STZ15": {
            "name": "STZ15",
            "formula": "(abs((ref(B1)+ref(B2))*55/2-sum(B3, " "B4))/55)/mean(B5, B6)",
            "bands": {"B1": 600, "B2": 655, "B3": 600, "B4": 655, "B5": 750, "B6": 850},
        },
        "STZ16": {
            "name": "STZ16",
            "formula": "(abs((ref(B1)+ref(B2))*70/2-sum(B3, " "B4))/70)/mean(B5, B6)",
            "bands": {"B1": 530, "B2": 600, "B3": 530, "B4": 600, "B5": 750, "B6": 850},
        },
        "STZ17": {
            "name": "STZ17",
            "formula": "(abs((ref(B1)+ref(B2))*125/2-sum(B3, " "B4))/125)/mean(B5, B6)",
            "bands": {"B1": 530, "B2": 655, "B3": 530, "B4": 655, "B5": 750, "B6": 850},
        },
        "STZ18": {
            "name": "STZ18",
            "formula": "sum(B1, B2)/sum(B3, B4)",
            "bands": {"B1": 570, "B2": 850, "B3": 400, "B4": 570},
        },
        "STZ19": {
            "name": "STZ19",
            "formula": "mean(B1, B2)/mean(B3, B4)",
            "bands": {"B1": 740.0, "B2": 850.0, "B3": 700.0, "B4": 740.0},
        },
        "STZ20": {
            "name": "STZ20",
            "formula": "ref(B1)/ref(B2)",
            "bands": {"B1": 700.0, "B2": 680.0},
        },
        "STZ21": {
            "name": "STZ21",
            "formula": "ref(B1)/mean(B2, B3)",
            "bands": {"B1": 700.0, "B2": 750.0, "B3": 800.0},
        },
        "STZ22": {
            "name": "STZ22",
            "formula": "(mean(B1, B2)-ref(B3))/(mean(B4, " "B5)+ref(B6))",
            "bands": {
                "B1": 750.0,
                "B2": 850.0,
                "B3": 680.0,
                "B4": 750.0,
                "B5": 850.0,
                "B6": 680.0,
            },
        },
        "STZ23": {
            "name": "STZ23",
            "formula": "(ref(B1)-mean(B2, " "B3))/(ref(B4)-mean(B5, B6))",
            "bands": {
                "B1": 700.0,
                "B2": 750.0,
                "B3": 850.0,
                "B4": 550.0,
                "B5": 420.0,
                "B6": 450.0,
            },
        },
        "STZ24": {
            "name": "STZ24",
            "formula": "ref(B1)/mean(B2, B3)",
            "bands": {"B1": 680.0, "B2": 420.0, "B3": 450.0},
        },
        "STZ25": {
            "name": "STZ25",
            "formula": "ref(B1)/mean(B2, B3)",
            "bands": {"B1": 680.0, "B2": 750.0, "B3": 850.0},
        },
        "STZ26": {
            "name": "STZ26",
            "formula": "ref(B1)/mean(B2, B3)",
            "bands": {"B1": 680.0, "B2": 810.0, "B3": 850.0},
        },
    },
    "warning_device": {
        "model_params": {"max_features": "all", "min_samples": 6},
        "Turb": {
            "name": "浊度",
            "model_params": {"max_features": "all"},
            "features": [{"feature_id": "STZ18"}],
        },
        "SS": {
            "name": "悬浮物",
            "model_params": {"max_features": "all"},
            "features": [{"feature_id": "STZ18"}],
        },
        "SD": {
            "name": "透明度",
            "model_params": {"max_features": "all"},
            "features": [{"feature_id": "STZ18"}],
        },
        "DO": {
            "name": "溶解氧",
            "model_params": {"max_features": "all"},
            "features": [
                {"feature_id": "STZ3"},
                {"feature_id": "STZ4"},
                {"feature_id": "STZ5"},
                {"feature_id": "STZ6"},
                {"feature_id": "STZ14"},
                {"feature_id": "STZ15"},
                {"feature_id": "STZ17"},
            ],
        },
        "NH3-N": {
            "name": "氨氮",
            "model_params": {"max_features": "all"},
            "features": [
                {"feature_id": "STZ1"},
                {"feature_id": "STZ5"},
                {"feature_id": "STZ9"},
                {"feature_id": "STZ15"},
                {"feature_id": "STZ19"},
            ],
        },
        "CODMn": {
            "name": "高锰酸盐",
            "model_params": {"max_features": "all"},
            "features": [
                {"feature_id": "STZ3"},
                {"feature_id": "STZ4"},
                {"feature_id": "STZ5"},
                {"feature_id": "STZ6"},
                {"feature_id": "STZ15"},
                {"feature_id": "STZ16"},
                {"feature_id": "STZ17"},
            ],
        },
        "COD": {
            "name": "化学需氧量",
            "model_params": {"max_features": "all"},
            "features": [
                {"feature_id": "STZ3"},
                {"feature_id": "STZ4"},
                {"feature_id": "STZ5"},
                {"feature_id": "STZ6"},
                {"feature_id": "STZ15"},
                {"feature_id": "STZ16"},
                {"feature_id": "STZ17"},
            ],
        },
        "Chla": {
            "name": "叶绿素a",
            "model_params": {"max_features": "all"},
            "features": [{"feature_id": "STZ14"}],
        },
        "TN": {
            "name": "总氮",
            "model_params": {"max_features": "all"},
            "features": [
                {"feature_id": "STZ3"},
                {"feature_id": "STZ4"},
                {"feature_id": "STZ5"},
                {"feature_id": "STZ6"},
                {"feature_id": "STZ14"},
                {"feature_id": "STZ15"},
                {"feature_id": "STZ17"},
                {"feature_id": "STZ18"},
            ],
        },
        "TP": {
            "name": "总磷",
            "model_params": {"max_features": "all"},
            "features": [
                {"feature_id": "STZ3"},
                {"feature_id": "STZ4"},
                {"feature_id": "STZ5"},
                {"feature_id": "STZ6"},
                {"feature_id": "STZ14"},
                {"feature_id": "STZ15"},
                {"feature_id": "STZ17"},
            ],
        },
        "default": {
            "name": "默认",
            "model_params": {"min_samples": 6, "max_features": 5},
            "features": [
                {"feature_id": "STZ1"},
                {"feature_id": "STZ2"},
                {"feature_id": "STZ3"},
                {"feature_id": "STZ4"},
                {"feature_id": "STZ5"},
                {"feature_id": "STZ6"},
                {"feature_id": "STZ14"},
                {"feature_id": "STZ15"},
                {"feature_id": "STZ16"},
                {"feature_id": "STZ17"},
                {"feature_id": "STZ18"},
                {"feature_id": "STZ19"},
            ],
        },
    },
    "shore_data": {
        "model_params": {"max_features": "all", "min_samples": 6},
        "Turb": {
            "name": "浊度",
            "model_params": {"max_features": "all"},
            "features": [{"feature_id": "STZ18"}],
        },
        "SS": {
            "name": "悬浮物",
            "model_params": {"max_features": "all"},
            "features": [{"feature_id": "STZ18"}],
        },
        "SD": {
            "name": "透明度",
            "model_params": {"max_features": "all"},
            "features": [{"feature_id": "STZ18"}],
        },
        "DO": {
            "name": "溶解氧",
            "model_params": {"max_features": "all"},
            "features": [
                {"feature_id": "STZ3"},
                {"feature_id": "STZ4"},
                {"feature_id": "STZ5"},
                {"feature_id": "STZ6"},
                {"feature_id": "STZ14"},
                {"feature_id": "STZ15"},
                {"feature_id": "STZ17"},
            ],
        },
        "NH3-N": {
            "name": "氨氮",
            "model_params": {"max_features": "all"},
            "features": [
                {"feature_id": "STZ1"},
                {"feature_id": "STZ5"},
                {"feature_id": "STZ9"},
                {"feature_id": "STZ15"},
                {"feature_id": "STZ19"},
            ],
        },
        "CODMn": {
            "name": "高锰酸盐",
            "model_params": {"max_features": "all"},
            "features": [
                {"feature_id": "STZ3"},
                {"feature_id": "STZ4"},
                {"feature_id": "STZ5"},
                {"feature_id": "STZ6"},
                {"feature_id": "STZ15"},
                {"feature_id": "STZ16"},
                {"feature_id": "STZ17"},
            ],
        },
        "COD": {
            "name": "化学需氧量",
            "model_params": {"max_features": "all"},
            "features": [
                {"feature_id": "STZ3"},
                {"feature_id": "STZ4"},
                {"feature_id": "STZ5"},
                {"feature_id": "STZ6"},
                {"feature_id": "STZ15"},
                {"feature_id": "STZ16"},
                {"feature_id": "STZ17"},
            ],
        },
        "Chla": {
            "name": "叶绿素a",
            "model_params": {"max_features": "all"},
            "features": [{"feature_id": "STZ14"}],
        },
        "TN": {
            "name": "总氮",
            "model_params": {"max_features": "all"},
            "features": [
                {"feature_id": "STZ3"},
                {"feature_id": "STZ4"},
                {"feature_id": "STZ5"},
                {"feature_id": "STZ6"},
                {"feature_id": "STZ14"},
                {"feature_id": "STZ15"},
                {"feature_id": "STZ17"},
                {"feature_id": "STZ18"},
            ],
        },
        "TP": {
            "name": "总磷",
            "model_params": {"max_features": "all"},
            "features": [
                {"feature_id": "STZ3"},
                {"feature_id": "STZ4"},
                {"feature_id": "STZ5"},
                {"feature_id": "STZ6"},
                {"feature_id": "STZ14"},
                {"feature_id": "STZ15"},
                {"feature_id": "STZ17"},
            ],
        },
        "default": {
            "name": "默认",
            "model_params": {"min_samples": 6, "max_features": 5},
            "features": [
                {"feature_id": "STZ1"},
                {"feature_id": "STZ2"},
                {"feature_id": "STZ3"},
                {"feature_id": "STZ4"},
                {"feature_id": "STZ5"},
                {"feature_id": "STZ6"},
                {"feature_id": "STZ14"},
                {"feature_id": "STZ15"},
                {"feature_id": "STZ16"},
                {"feature_id": "STZ17"},
                {"feature_id": "STZ18"},
                {"feature_id": "STZ19"},
            ],
        },
    },
    "smart_water": {
        "model_params": {"max_features": "all", "min_samples": 6},
        "Turb": {
            "name": "浊度",
            "model_params": {"max_features": "all"},
            "features": [{"feature_id": "STZ18"}],
        },
        "SS": {
            "name": "悬浮物",
            "model_params": {"max_features": "all"},
            "features": [{"feature_id": "STZ18"}],
        },
        "SD": {
            "name": "透明度",
            "model_params": {"max_features": "all"},
            "features": [{"feature_id": "STZ18"}],
        },
        "DO": {
            "name": "溶解氧",
            "model_params": {"max_features": "all"},
            "features": [
                {"feature_id": "STZ3"},
                {"feature_id": "STZ4"},
                {"feature_id": "STZ5"},
                {"feature_id": "STZ6"},
                {"feature_id": "STZ14"},
                {"feature_id": "STZ15"},
                {"feature_id": "STZ17"},
            ],
        },
        "NH3-N": {
            "name": "氨氮",
            "model_params": {"max_features": "all"},
            "features": [
                {"feature_id": "STZ1"},
                {"feature_id": "STZ5"},
                {"feature_id": "STZ9"},
                {"feature_id": "STZ15"},
                {"feature_id": "STZ19"},
            ],
        },
        "CODMn": {
            "name": "高锰酸盐",
            "model_params": {"max_features": "all"},
            "features": [
                {"feature_id": "STZ3"},
                {"feature_id": "STZ4"},
                {"feature_id": "STZ5"},
                {"feature_id": "STZ6"},
                {"feature_id": "STZ15"},
                {"feature_id": "STZ16"},
                {"feature_id": "STZ17"},
            ],
        },
        "COD": {
            "name": "化学需氧量",
            "model_params": {"max_features": "all"},
            "features": [
                {"feature_id": "STZ3"},
                {"feature_id": "STZ4"},
                {"feature_id": "STZ5"},
                {"feature_id": "STZ6"},
                {"feature_id": "STZ15"},
                {"feature_id": "STZ16"},
                {"feature_id": "STZ17"},
            ],
        },
        "Chla": {
            "name": "叶绿素a",
            "model_params": {"max_features": "all"},
            "features": [{"feature_id": "STZ14"}],
        },
        "TN": {
            "name": "总氮",
            "model_params": {"max_features": "all"},
            "features": [
                {"feature_id": "STZ3"},
                {"feature_id": "STZ4"},
                {"feature_id": "STZ5"},
                {"feature_id": "STZ6"},
                {"feature_id": "STZ14"},
                {"feature_id": "STZ15"},
                {"feature_id": "STZ17"},
                {"feature_id": "STZ18"},
            ],
        },
        "TP": {
            "name": "总磷",
            "model_params": {"max_features": "all"},
            "features": [
                {"feature_id": "STZ3"},
                {"feature_id": "STZ4"},
                {"feature_id": "STZ5"},
                {"feature_id": "STZ6"},
                {"feature_id": "STZ14"},
                {"feature_id": "STZ15"},
                {"feature_id": "STZ17"},
            ],
        },
        "default": {
            "name": "默认",
            "model_params": {"min_samples": 6, "max_features": 5},
            "features": [
                {"feature_id": "STZ1"},
                {"feature_id": "STZ2"},
                {"feature_id": "STZ3"},
                {"feature_id": "STZ4"},
                {"feature_id": "STZ5"},
                {"feature_id": "STZ6"},
                {"feature_id": "STZ14"},
                {"feature_id": "STZ15"},
                {"feature_id": "STZ16"},
                {"feature_id": "STZ17"},
                {"feature_id": "STZ18"},
                {"feature_id": "STZ19"},
            ],
        },
    },
    "aerospot": {
        "model_params": {"max_features": "all", "min_samples": 6},
        "Turb": {
            "name": "浊度",
            "model_params": {"max_features": "all"},
            "features": [{"feature_id": "STZ18"}],
        },
        "SS": {
            "name": "悬浮物",
            "model_params": {"max_features": "all"},
            "features": [{"feature_id": "STZ18"}],
        },
        "SD": {
            "name": "透明度",
            "model_params": {"max_features": "all"},
            "features": [{"feature_id": "STZ18"}],
        },
        "DO": {
            "name": "溶解氧",
            "model_params": {"max_features": "all"},
            "features": [
                {"feature_id": "STZ3"},
                {"feature_id": "STZ4"},
                {"feature_id": "STZ5"},
                {"feature_id": "STZ6"},
                {"feature_id": "STZ14"},
                {"feature_id": "STZ15"},
                {"feature_id": "STZ17"},
            ],
        },
        "CODMn": {
            "name": "高锰酸盐",
            "model_params": {"max_features": "all"},
            "features": [
                {"feature_id": "STZ3"},
                {"feature_id": "STZ4"},
                {"feature_id": "STZ5"},
                {"feature_id": "STZ6"},
                {"feature_id": "STZ14"},
                {"feature_id": "STZ15"},
                {"feature_id": "STZ17"},
            ],
        },
        "COD": {
            "name": "化学需氧量",
            "model_params": {"max_features": "all"},
            "features": [
                {"feature_id": "STZ3"},
                {"feature_id": "STZ4"},
                {"feature_id": "STZ5"},
                {"feature_id": "STZ6"},
                {"feature_id": "STZ14"},
                {"feature_id": "STZ15"},
                {"feature_id": "STZ17"},
            ],
        },
        "Chla": {
            "name": "叶绿素a",
            "model_params": {"max_features": "all"},
            "features": [{"feature_id": "STZ20"}, {"feature_id": "STZ26"}],
        },
        "TN": {
            "name": "总氮",
            "model_params": {"max_features": "all"},
            "features": [
                {"feature_id": "STZ3"},
                {"feature_id": "STZ4"},
                {"feature_id": "STZ5"},
                {"feature_id": "STZ6"},
                {"feature_id": "STZ14"},
                {"feature_id": "STZ15"},
                {"feature_id": "STZ17"},
            ],
        },
        "TP": {
            "name": "总磷",
            "model_params": {"max_features": "all"},
            "features": [
                {"feature_id": "STZ3"},
                {"feature_id": "STZ4"},
                {"feature_id": "STZ5"},
                {"feature_id": "STZ6"},
                {"feature_id": "STZ14"},
                {"feature_id": "STZ15"},
                {"feature_id": "STZ17"},
            ],
        },
        "Chroma": {
            "name": "色度",
            "model_params": {"max_features": "all"},
            "features": [
                {"feature_id": "STZ10"},
                {"feature_id": "STZ11"},
                {"feature_id": "STZ12"},
            ],
        },
        "NH3-N": {
            "name": "氨氮",
            "model_params": {"max_features": "all"},
            "features": [
                {"feature_id": "STZ1"},
                {"feature_id": "STZ6"},
                {"feature_id": "STZ15"},
                {"feature_id": "STZ17"},
                {"feature_id": "STZ24"},
            ],
        },
        "default": {
            "name": "默认",
            "model_params": {"min_samples": 6, "max_features": 5},
            "features": [
                {"feature_id": "STZ1"},
                {"feature_id": "STZ2"},
                {"feature_id": "STZ3"},
                {"feature_id": "STZ4"},
                {"feature_id": "STZ5"},
                {"feature_id": "STZ6"},
                {"feature_id": "STZ14"},
                {"feature_id": "STZ15"},
                {"feature_id": "STZ16"},
                {"feature_id": "STZ17"},
                {"feature_id": "STZ18"},
                {"feature_id": "STZ19"},
            ],
        },
    },
}


# 便捷访问函数
def get_config() -> dict:
    """获取特征配置"""
    return FEATURES_CONFIG
