from enum import Enum


class ConnectionsPublicControllerGetConnectionsProviderTypesItem(str, Enum):
    BACKGROUND_CHECK = "BACKGROUND_CHECK"
    CODEBASE = "CODEBASE"
    COMMUNICATION = "COMMUNICATION"
    CRM = "CRM"
    CSPM = "CSPM"
    CUSTOM = "CUSTOM"
    CYBER_INSURANCE = "CYBER_INSURANCE"
    DIGITAL_SIGNATURE = "DIGITAL_SIGNATURE"
    EDR = "EDR"
    ENTERPRISE_SSO = "ENTERPRISE_SSO"
    EXTERNAL_POLICY = "EXTERNAL_POLICY"
    HRIS = "HRIS"
    IDENTITY = "IDENTITY"
    INFRASTRUCTURE = "INFRASTRUCTURE"
    MDM = "MDM"
    OBSERVABILITY = "OBSERVABILITY"
    SECURITY_TRAINING = "SECURITY_TRAINING"
    SINGLE_SIGN_ON = "SINGLE_SIGN_ON"
    TICKETING = "TICKETING"
    USER_ACCESS_REVIEW = "USER_ACCESS_REVIEW"
    VERSION_CONTROL = "VERSION_CONTROL"
    VULNERABILITY = "VULNERABILITY"

    def __str__(self) -> str:
        return str(self.value)
