from enum import Enum


class CurrencyCodeEnum(str, Enum):
    BWP = "BWP"
    CAD = "CAD"
    CHF = "CHF"
    CLP = "CLP"
    CNY = "CNY"
    COP = "COP"
    CRC = "CRC"
    CZK = "CZK"
    DKK = "DKK"
    DOP = "DOP"
    EEK = "EEK"
    EUR = "EUR"
    GBP = "GBP"
    GHS = "GHS"
    GTQ = "GTQ"
    HKD = "HKD"
    HRK = "HRK"
    HUF = "HUF"
    IDR = "IDR"
    ILS = "ILS"
    IMP = "IMP"
    INR = "INR"
    ISK = "ISK"
    JPY = "JPY"
    KES = "KES"
    KRW = "KRW"
    KYD = "KYD"
    LKR = "LKR"
    LUF = "LUF"
    LVL = "LVL"
    MTL = "MTL"
    MUR = "MUR"
    MXN = "MXN"
    MYR = "MYR"
    NGN = "NGN"
    NOK = "NOK"
    NZD = "NZD"
    PAB = "PAB"
    PEN = "PEN"
    PHP = "PHP"
    PLN = "PLN"
    RON = "RON"
    RUB = "RUB"
    SEK = "SEK"
    SGD = "SGD"
    SOS = "SOS"
    TOP = "TOP"
    TRY = "TRY"
    UAH = "UAH"
    USD = "USD"
    UYU = "UYU"
    ZAR = "ZAR"

    def __str__(self) -> str:
        return str(self.value)
