from enum import Enum


class GRCPublicControllerGetControlsPciRequirementsItem(str, Enum):
    PCI_ACCESS_RESTRICTION = "PCI_ACCESS_RESTRICTION"
    PCI_DATA_AT_REST_PROTECTION = "PCI_DATA_AT_REST_PROTECTION"
    PCI_DATA_IN_TRANSIT_ENCRYPTION = "PCI_DATA_IN_TRANSIT_ENCRYPTION"
    PCI_FIREWALL = "PCI_FIREWALL"
    PCI_INFORMATION_SECURITY_POLICY = "PCI_INFORMATION_SECURITY_POLICY"
    PCI_MALWARE_PROTECTION = "PCI_MALWARE_PROTECTION"
    PCI_NETWORK_ACCESS_MONITORING = "PCI_NETWORK_ACCESS_MONITORING"
    PCI_PASSWORDS = "PCI_PASSWORDS"
    PCI_PHYSICAL_ACCESS_CONTROL = "PCI_PHYSICAL_ACCESS_CONTROL"
    PCI_SECURE_SYSTEM_MANAGEMENT = "PCI_SECURE_SYSTEM_MANAGEMENT"
    PCI_SYSTEM_ACCESS_CONTROL = "PCI_SYSTEM_ACCESS_CONTROL"
    PCI_VULNERABILITY_TESTING = "PCI_VULNERABILITY_TESTING"

    def __str__(self) -> str:
        return str(self.value)
