from enum import Enum


class GRCPublicControllerGetControlsRegulationsItem(str, Enum):
    CCPA_BUSINESS_PRACTICES_FOR_HANDLING_CONSUMER_REQUESTS = "CCPA_BUSINESS_PRACTICES_FOR_HANDLING_CONSUMER_REQUESTS"
    CCPA_GENERAL_PROVISIONS = "CCPA_GENERAL_PROVISIONS"
    CCPA_NON_DISCRIMINATION = "CCPA_NON_DISCRIMINATION"
    CCPA_NOTICES_TO_CONSUMERS = "CCPA_NOTICES_TO_CONSUMERS"
    CCPA_REQUIRED_DISCLOSURES_TO_CONSUMERS = "CCPA_REQUIRED_DISCLOSURES_TO_CONSUMERS"
    CCPA_SERVICE_PROVIDERS_CONTRACTORS_AND_THIRD_PARTIES = "CCPA_SERVICE_PROVIDERS_CONTRACTORS_AND_THIRD_PARTIES"
    CCPA_SPECIAL_RULES_REGARDING_CONSUMERS_UNDER_16_YEARS_OF_AGE = (
        "CCPA_SPECIAL_RULES_REGARDING_CONSUMERS_UNDER_16_YEARS_OF_AGE"
    )
    CCPA_TRAINING_AND_RECORD_KEEPING = "CCPA_TRAINING_AND_RECORD_KEEPING"
    CCPA_VERIFICATION_OF_REQUESTS = "CCPA_VERIFICATION_OF_REQUESTS"

    def __str__(self) -> str:
        return str(self.value)
