from enum import Enum


class GRCPublicControllerGetControlsSectionsItem(str, Enum):
    MSSSPA_CHOICE_AND_CONSENT = "MSSSPA_CHOICE_AND_CONSENT"
    MSSSPA_COLLECTION = "MSSSPA_COLLECTION"
    MSSSPA_DATA_SUBJECTS = "MSSSPA_DATA_SUBJECTS"
    MSSSPA_DISCLOSURE_TO_THIRD_PARTIES = "MSSSPA_DISCLOSURE_TO_THIRD_PARTIES"
    MSSSPA_MANAGEMENT = "MSSSPA_MANAGEMENT"
    MSSSPA_MONITORING_AND_ENFORCEMENT = "MSSSPA_MONITORING_AND_ENFORCEMENT"
    MSSSPA_NOTICE = "MSSSPA_NOTICE"
    MSSSPA_QUALITY = "MSSSPA_QUALITY"
    MSSSPA_RETENTION = "MSSSPA_RETENTION"
    MSSSPA_SECURITY = "MSSSPA_SECURITY"

    def __str__(self) -> str:
        return str(self.value)
