from enum import Enum


class PersonnelDetailsResponsePublicDtoEmploymentStatus(str, Enum):
    CURRENT_CONTRACTOR = "CURRENT_CONTRACTOR"
    CURRENT_EMPLOYEE = "CURRENT_EMPLOYEE"
    FORMER_CONTRACTOR = "FORMER_CONTRACTOR"
    FORMER_EMPLOYEE = "FORMER_EMPLOYEE"
    FUTURE_HIRE = "FUTURE_HIRE"
    OUT_OF_SCOPE = "OUT_OF_SCOPE"
    SERVICE_ACCOUNT = "SERVICE_ACCOUNT"
    SPECIAL_FORMER_CONTRACTOR = "SPECIAL_FORMER_CONTRACTOR"
    SPECIAL_FORMER_EMPLOYEE = "SPECIAL_FORMER_EMPLOYEE"
    UNKNOWN = "UNKNOWN"

    def __str__(self) -> str:
        return str(self.value)
