TOOL_REQUIRED = {
    "acorn": "shovel",
    "amethyst": "pickaxe",
    "amethyst block": "pickaxe",
    "amethyst boiler": "pickaxe",
    "amethyst dirt": "shovel",
    "amethyst pipe": "pickaxe",
    "amethyst pump": "pickaxe",
    "amethyst rune": "pickaxe",
    "bluebell": "shovel",
    "bluebell grown": "shovel",
    "bluebell jar": "axe",
    "bookshelf": "axe",
    "brick": "pickaxe",
    "brick floor": "pickaxe",
    "burner drill": "pickaxe",
    "campfire": "axe",
    "carrot": "shovel",
    "carrot grown": "shovel",
    "citrine": "pickaxe",
    "citrine block": "pickaxe",
    "citrine rune": "pickaxe",
    "clay": "shovel",
    "coal": "pickaxe",
    "coal block": "pickaxe",
    "coal ore": "pickaxe",
    "coal sapling": "shovel",
    "coal treeling": "axe",
    "coal tree": "axe",
    "composter": "axe",
    "copper anvil": "pickaxe",
    "copper block": "pickaxe",
    "copper boiler": "pickaxe",
    "copper brick": "pickaxe",
    "copper brick floor": "pickaxe",
    "copper constructor": "pickaxe",
    "copper door": "pickaxe",
    "copper door open": "pickaxe",
    "copper gear": "pickaxe",
    "copper ingot": "pickaxe",
    "copper ore": "pickaxe",
    "copper pipe": "pickaxe",
    "copper pit grown": "pickaxe",
    "copper press": "pickaxe",
    "copper pump": "pickaxe",
    "copper sapling": "shovel",
    "copper shaft": "pickaxe",
    "copper sheet": "pickaxe",
    "copper tank": "pickaxe",
    "copper treeling": "axe",
    "copper tree": "axe",
    "dirt": "shovel",
    "dye mixer": "axe",
    "flint": "pickaxe",
    "furless rabbit": "sword",
    "furnace": "pickaxe",
    "ice": "pickaxe",
    "life crystal": "pickaxe",
    "log": "axe",
    "log floor": "axe",
    "mana converter": "axe",
    "manual press": "axe",
    "masonry bench": "axe",
    "moist dirt": "shovel",
    "mushroom": "axe",
    "mushroom block": "hammer",
    "mushroom door": "hammer",
    "mushroom door open": "hammer",
    "mushroom floor": "hammer",
    "mushroom shaper": "hammer",
    "mushroom table": "hammer",
    "obelisk piece": "pickaxe",
    "packager bench": "axe",
    "pebble": "pickaxe",
    "potato": "shovel",
    "potato grown": "shovel",
    "pure crystal": "pickaxe",
    "quartz": "pickaxe",
    "quartz adult": "pickaxe",
    "quartz altar": "pickaxe",
    "quartz block": "pickaxe",
    "quartz child": "pickaxe",
    "rabbit adult": "sword",
    "rabbit child": "sword",
    "rabbit fur": "needle",
    "rail 0": "pickaxe",
    "rail 1": "pickaxe",
    "rail 2": "pickaxe",
    "rail 3": "pickaxe",
    "rail 4": "pickaxe",
    "rail 5": "pickaxe",
    "raw copper": "pickaxe",
    "raw tin": "pickaxe",
    "rock": "pickaxe",
    "sand": "shovel",
    "sapling": "shovel",
    "sawbench": "axe",
    "sewbench": "axe",
    "skeleton": "sword",
    "slife crystal": "picakxe",
    "slime": "sword",
    "slime ball": "hammer",
    "slime block": "hammer",
    "slime crystal": "pickaxe",
    "slime door": "hammer",
    "slime door open": "hammer",
    "slime floor": "hammer",
    "slime shaper": "hammer",
    "slime prince": "sword",
    "slime table": "hammer",
    "small backpack": "needle",
    "small barrel": "axe",
    "small crate": "axe",
    "spore": "shovel",
    "stick": "axe",
    "stone": "pickaxe",
    "stone brick": "pickaxe",
    "stone brick floor": "pickaxe",
    "stone floor": "pickaxe",
    "thread": "needle",
    "tin ingot": "pickaxe",
    "tin ore": "pickaxe",
    "tin treeling": "axe",
    "tin tree": "axe",
    "torch": "axe",
    "tree": "axe",
    "treeling": "axe",
    "tree constructor": "axe",
    "wood": "axe",
    "wood crucible": "axe",
    "wood door": "axe",
    "wood door open": "axe",
    "wood fence": "axe",
    "wood fence pole": "axe",
    "wood fence vertical": "axe",
    "wood floor": "axe",
    "wooden bed": "axe",
    "wooden sieve": "axe",
    "wooden table": "axe",
    "workbench": "axe",
}
TOOL_EFFICIENCY = {"flint": 1, "rock": 2, "water": 2, "amethyst": 3, "copper": 3}
TOOLS = {
    "axe",
    "hammer",
    "needle",
    "pickaxe",
    "shovel",
    "sword",
}
