"""Type stubs for tnfr.extensions.business"""

from typing import Dict, Type
from ..base import TNFRExtension, PatternDefinition, CookbookRecipe

class BusinessExtension(TNFRExtension):
    def get_domain_name(self) -> str: ...
    def get_pattern_definitions(self) -> Dict[str, PatternDefinition]: ...
    def get_health_analyzers(self) -> Dict[str, Type]: ...
    def get_cookbook_recipes(self) -> Dict[str, CookbookRecipe]: ...
    def get_metadata(self) -> Dict[str, object]: ...
