from byte.core.utils.list_to_multiline_text import list_to_multiline_text
from byte.domain.prompt_format.schemas import BoundaryType
from byte.domain.prompt_format.utils import Boundary

edit_format_system = list_to_multiline_text(
    [
        "# *Pseudo-XML Edit Block* Rules:",
        "",
        "Use *Pseudo-XML edit blocks* to make precise edits to files. Each block specifies:",
        "- **What file** to modify (with full path)",
        "- **What operation** to perform (edit, create, delete, replace)",
        "- **What content** to find (search section)",
        "- **What to replace** it with (replace section)",
        "",
        "## Block Format:",
        "",
        "Every *Pseudo-XML edit block* must use this exact format:",
        "```language",
        Boundary.open(BoundaryType.FILE, meta={"path": "full/file/path", "operation": "operation_type"}),
        Boundary.open(BoundaryType.SEARCH),
        "content to find (can be empty)",
        Boundary.close(BoundaryType.SEARCH),
        Boundary.open(BoundaryType.REPLACE),
        "content to replace with (can be empty)",
        Boundary.close(BoundaryType.REPLACE),
        Boundary.close(BoundaryType.FILE),
        "```",
        "",
        "## Operation Types:",
        "- `edit` for **editing** existing file content",
        "- `create` for **creating** new files",
        "- `delete` for **removing** files completely",
        "- `replace` for **replacing entire file contents**",
        "",
        "## Examples:",
        "",
        "**Create a new file:**",
        "```python",
        Boundary.open(BoundaryType.FILE, meta={"path": "mathweb/flask/app.py", "operation": "create"}),
        Boundary.open(BoundaryType.SEARCH),
        Boundary.close(BoundaryType.SEARCH),
        Boundary.open(BoundaryType.REPLACE),
        "import math",
        "from flask import Flask",
        Boundary.close(BoundaryType.REPLACE),
        Boundary.close(BoundaryType.FILE),
        "```",
        "",
        "**Edit existing file content:**",
        "```python",
        Boundary.open(BoundaryType.FILE, meta={"path": "mathweb/flask/app.py", "operation": "edit"}),
        Boundary.open(BoundaryType.SEARCH),
        "from flask import Flask",
        Boundary.close(BoundaryType.SEARCH),
        Boundary.open(BoundaryType.REPLACE),
        "import math",
        "from flask import Flask",
        Boundary.close(BoundaryType.REPLACE),
        Boundary.close(BoundaryType.FILE),
        "```",
        "",
        "**Remove entire file:**",
        "```python",
        Boundary.open(BoundaryType.FILE, meta={"path": "old_config.py", "operation": "delete"}),
        Boundary.open(BoundaryType.SEARCH),
        Boundary.close(BoundaryType.SEARCH),
        Boundary.open(BoundaryType.REPLACE),
        Boundary.close(BoundaryType.REPLACE),
        Boundary.close(BoundaryType.FILE),
        "```",
        "",
        "**Replace all file contents:**",
        "```python",
        Boundary.open(BoundaryType.FILE, meta={"path": "config.py", "operation": "replace"}),
        Boundary.open(BoundaryType.SEARCH),
        Boundary.close(BoundaryType.SEARCH),
        Boundary.open(BoundaryType.REPLACE),
        "import os",
        "from dataclasses import dataclass",
        "",
        "@dataclass",
        "class AppConfig:",
        "    debug: bool = False",
        "    port: int = 8000",
        '    database_url: str = os.getenv("DATABASE_URL", "sqlite:///app.db")',
        Boundary.close(BoundaryType.REPLACE),
        Boundary.close(BoundaryType.FILE),
        "```",
        "",
        "## **CRITICAL RULES:**",
        "",
        "File Paths:",
        "- Use the FULL file path exactly as shown by the user",
        "- No bold asterisks, quotes, or escaping around the path",
        "",
        "Search Content:",
        "- Must EXACTLY MATCH existing file content, character for character",
        "- Include all comments, docstrings, whitespace, etc.",
        "- If file contains wrapped/escaped content, match the literal file contents",
        "",
        "Block Strategy:",
        "- Keep blocks small and focused",
        "- Use multiple blocks for multiple changes to the same file",
        "- Include enough context lines to make each search unique",
        "- Only replace the first occurrence found",
        "",
        "File Operations:",
        "- Only edit files that the user has added to the chat",
        '- For new files: use operation="create" with empty search, content in replace',
        "- To move code: use 2 blocks (1 to delete, 1 to insert)",
        "",
        "User Intent:",
        '- If user says "ok", "go ahead", or "do that" → provide Pseudo-XML edit blocks',
        "- Wait for user confirmation before assuming edits are applied",
        "- ONLY EVER RETURN CODE IN A PSEUDO-XML EDIT BLOCK!",
    ]
)

shell_command_system = list_to_multiline_text(
    [
        "# *Shell Command Block* Rules:",
        "Use *Shell Command blocks* to execute shell commands AFTER file edits are applied.",
        "",
        "Just suggest shell commands this way, not example code.",
        "Only suggest complete shell commands that are ready to execute, without placeholders.",
        "Only suggest at most a few shell commands at a time, not more than 1-3, one per line.",
        "Do not suggest multi-line shell commands.",
        "All shell commands will run from the root directory of the user's project.",
        "",
        "## Block Format:",
        "",
        "```sh",
        Boundary.open(BoundaryType.SHELL_COMMAND),
        "command to execute",
        Boundary.close(BoundaryType.SHELL_COMMAND),
        "```",
        "Or:",
        "```bash",
        Boundary.open(BoundaryType.SHELL_COMMAND),
        "command to execute",
        "second command to execute",
        Boundary.close(BoundaryType.SHELL_COMMAND),
        "```",
        "",
        "## **CRITICAL RULES:**",
        "",
        "When to Use:",
        "- If you changed a CLI program, suggest the command to run it to see the new behavior.",
        "- If you added a test, suggest how to run it with the testing tool used by the project.",
        "- If your code changes add new dependencies, suggest the command to install them.",
        "- Never edit files with shell commands (echo, sed, >>) - use SEARCH/REPLACE instead",
        "",
        "Safety:",
        "- Commands require user confirmation before execution",
        "- Dangerous operations prompt for explicit approval",
        "",
        "Execution:",
        "- Execute AFTER all SEARCH/REPLACE blocks succeed",
        "- Execute sequentially in order they appear",
        "- If file edits fail, shell commands are skipped",
    ]
)

practice_messages = [
    (
        "user",
        list_to_multiline_text(
            [
                "Before we start lets first practice the *Pseudo-XML edit block* format.",
                "",
                "Change get_factorial() to use math.factorial",
            ]
        ),
    ),
    (
        "assistant",
        list_to_multiline_text(
            [
                "To make this change we need to modify `mathweb/flask/app.py` to:",
                "",
                "1. Import the math package.",
                "2. Remove the existing factorial() function.",
                "3. Update get_factorial() to call math.factorial instead.",
                "",
                "Here are the *Pseudo-XML edit* blocks:",
                "",
                "```python",
                Boundary.open(BoundaryType.FILE, meta={"path": "mathweb/flask/app.py", "operation": "edit"}),
                Boundary.open(BoundaryType.SEARCH),
                "from flask import Flask",
                Boundary.close(BoundaryType.SEARCH),
                Boundary.open(BoundaryType.REPLACE),
                "import math",
                "from flask import Flask",
                Boundary.close(BoundaryType.REPLACE),
                Boundary.close(BoundaryType.FILE),
                "```",
                "",
                "```python",
                Boundary.open(BoundaryType.FILE, meta={"path": "mathweb/flask/app.py", "operation": "edit"}),
                Boundary.open(BoundaryType.SEARCH),
                "def factorial(n):",
                '    "compute factorial"',
                "",
                "    if n == 0:",
                "        return 1",
                "    else:",
                "        return n * factorial(n-1)",
                "",
                Boundary.close(BoundaryType.SEARCH),
                Boundary.open(BoundaryType.REPLACE),
                Boundary.close(BoundaryType.REPLACE),
                Boundary.close(BoundaryType.FILE),
                "```",
                "",
                "```python",
                Boundary.open(BoundaryType.FILE, meta={"path": "mathweb/flask/app.py", "operation": "edit"}),
                Boundary.open(BoundaryType.SEARCH),
                "    return str(factorial(n))",
                Boundary.close(BoundaryType.SEARCH),
                Boundary.open(BoundaryType.REPLACE),
                "    return str(math.factorial(n))",
                Boundary.close(BoundaryType.REPLACE),
                Boundary.close(BoundaryType.FILE),
                "```",
            ]
        ),
    ),
    (
        "user",
        "Refactor hello() into its own file.",
    ),
    (
        "assistant",
        list_to_multiline_text(
            [
                "To make this change we need to modify `main.py` and make a new file `hello.py`:",
                "",
                "1. Make a new hello.py file with hello() in it.",
                "2. Remove hello() from main.py and replace it with an import.",
                "",
                "Here are the *Pseudo-XML edit* blocks:",
                "",
                "```python",
                Boundary.open(BoundaryType.FILE, meta={"path": "hello.py", "operation": "create"}),
                Boundary.open(BoundaryType.SEARCH),
                Boundary.close(BoundaryType.SEARCH),
                Boundary.open(BoundaryType.REPLACE),
                "def hello():",
                '    "print a greeting"',
                "",
                '    print("hello")',
                Boundary.close(BoundaryType.REPLACE),
                Boundary.close(BoundaryType.FILE),
                "```",
                "",
                "```python",
                Boundary.open(BoundaryType.FILE, meta={"path": "main.py", "operation": "edit"}),
                Boundary.open(BoundaryType.SEARCH),
                "def hello():",
                '    "print a greeting"',
                "",
                '    print("hello")',
                Boundary.close(BoundaryType.SEARCH),
                Boundary.open(BoundaryType.REPLACE),
                "from hello import hello",
                Boundary.close(BoundaryType.REPLACE),
                Boundary.close(BoundaryType.FILE),
                "```",
            ]
        ),
    ),
    ("user", "Remove the old_config.py file that's no longer needed."),
    (
        "assistant",
        list_to_multiline_text(
            [
                "To remove this file we need to delete `old_config.py`:",
                "",
                "1. Remove the old_config.py file completely from the project.",
                "",
                "Here is the *Pseudo-XML edit* block:",
                "",
                "```python",
                Boundary.open(BoundaryType.FILE, meta={"path": "old_config.py", "operation": "delete"}),
                Boundary.open(BoundaryType.SEARCH),
                Boundary.close(BoundaryType.SEARCH),
                Boundary.open(BoundaryType.REPLACE),
                Boundary.close(BoundaryType.REPLACE),
                Boundary.close(BoundaryType.FILE),
                "```",
            ]
        ),
    ),
    (
        "user",
        "Replace all the contents of config.py with a new configuration structure.",
    ),
    (
        "assistant",
        list_to_multiline_text(
            [
                "To replace all the contents we need to completely rewrite `config.py`:",
                "",
                "1. Replace the entire contents of config.py with the new configuration structure.",
                "",
                "Here is the *Pseudo-XML edit* block:",
                "",
                "```python",
                Boundary.open(BoundaryType.FILE, meta={"path": "config.py", "operation": "replace"}),
                Boundary.open(BoundaryType.SEARCH),
                Boundary.close(BoundaryType.SEARCH),
                Boundary.open(BoundaryType.REPLACE),
                "import os",
                "from dataclasses import dataclass",
                "",
                "@dataclass",
                "class AppConfig:",
                "    debug: bool = False",
                "    port: int = 8000",
                '    database_url: str = os.getenv("DATABASE_URL", "sqlite:///app.db")',
                Boundary.close(BoundaryType.REPLACE),
                Boundary.close(BoundaryType.FILE),
                "```",
            ]
        ),
    ),
    (
        "user",
        "Add error handling to the calculator function and update the docstring.",
    ),
    (
        "assistant",
        list_to_multiline_text(
            [
                "To add error handling we need to modify `calculator.py` in two places:",
                "",
                "1. Update the docstring to mention error handling.",
                "2. Add try-catch block around the calculation.",
                "",
                "Here are the *Pseudo-XML edit* blocks:",
                "",
                "```python",
                Boundary.open(BoundaryType.FILE, meta={"path": "calculator.py", "operation": "edit"}),
                Boundary.open(BoundaryType.SEARCH),
                "def calculate(a, b):",
                '    "Simple calculator function"',
                Boundary.close(BoundaryType.SEARCH),
                Boundary.open(BoundaryType.REPLACE),
                "def calculate(a, b):",
                '    "Simple calculator function with error handling"',
                Boundary.close(BoundaryType.REPLACE),
                Boundary.close(BoundaryType.FILE),
                "```",
                "",
                "```python",
                Boundary.open(BoundaryType.FILE, meta={"path": "calculator.py", "operation": "edit"}),
                Boundary.open(BoundaryType.SEARCH),
                "    return a / b",
                Boundary.close(BoundaryType.SEARCH),
                Boundary.open(BoundaryType.REPLACE),
                "    try:",
                "        return a / b",
                "    except ZeroDivisionError:",
                '        return "Error: Cannot divide by zero"',
                Boundary.close(BoundaryType.REPLACE),
                Boundary.close(BoundaryType.FILE),
                "```",
            ]
        ),
    ),
]


# pseudo_xml_prompts = EditFormatPrompts(
#     system=edit_format_system,
#     examples=practice_messages,
#     shell_system=shell_command_system,
#     shell_examples=[],
# )
