# see https://www.postgresql.org/docs/current/sql-commands.html
SQL_KEYWORDS = {
    'ABORT', 'ALTER', 'ANALYZE', 'BEGIN', 'CALL', 'CHECKPOINT', 'CLOSE', 'CLUSTER', 'COMMENT', 'COMMIT', 'COPY',
    'CREATE', 'DEALLOCATE', 'DECLARE', 'DELETE', 'DISCARD', 'DO', 'DROP', 'END', 'EXECUTE', 'EXPLAIN', 'FETCH', 'FROM',
    'GRANT', 'IMPORT', 'INSERT', 'LISTEN', 'LOAD', 'LOCK', 'MERGE', 'MOVE', 'NOTIFY', 'PREPARE', 'REASSIGN', 'REFRESH',
    'REINDEX', 'RELEASE', 'RESET', 'REVOKE', 'ROLLBACK', 'SAVEPOINT', 'SECURITY', 'SELECT', 'SET', 'SHOW', 'START',
    'TRUNCATE', 'UNLISTEN', 'UPDATE', 'VACUUM', 'VALUES'
}
