# coding: utf-8

"""
    ai/h2o/mlops/storage/v1/artifact.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from _h2o_mlops_client.storage.configuration import Configuration


class StorageNumericColumnStats(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'mean': 'float',
        'std': 'float',
        'min': 'float',
        'max': 'float'
    }

    attribute_map = {
        'mean': 'mean',
        'std': 'std',
        'min': 'min',
        'max': 'max'
    }

    def __init__(self, mean=None, std=None, min=None, max=None, local_vars_configuration=None):  # noqa: E501
        """StorageNumericColumnStats - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._mean = None
        self._std = None
        self._min = None
        self._max = None
        self.discriminator = None

        if mean is not None:
            self.mean = mean
        if std is not None:
            self.std = std
        if min is not None:
            self.min = min
        if max is not None:
            self.max = max

    @property
    def mean(self):
        """Gets the mean of this StorageNumericColumnStats.  # noqa: E501


        :return: The mean of this StorageNumericColumnStats.  # noqa: E501
        :rtype: float
        """
        return self._mean

    @mean.setter
    def mean(self, mean):
        """Sets the mean of this StorageNumericColumnStats.


        :param mean: The mean of this StorageNumericColumnStats.  # noqa: E501
        :type mean: float
        """

        self._mean = mean

    @property
    def std(self):
        """Gets the std of this StorageNumericColumnStats.  # noqa: E501


        :return: The std of this StorageNumericColumnStats.  # noqa: E501
        :rtype: float
        """
        return self._std

    @std.setter
    def std(self, std):
        """Sets the std of this StorageNumericColumnStats.


        :param std: The std of this StorageNumericColumnStats.  # noqa: E501
        :type std: float
        """

        self._std = std

    @property
    def min(self):
        """Gets the min of this StorageNumericColumnStats.  # noqa: E501


        :return: The min of this StorageNumericColumnStats.  # noqa: E501
        :rtype: float
        """
        return self._min

    @min.setter
    def min(self, min):
        """Sets the min of this StorageNumericColumnStats.


        :param min: The min of this StorageNumericColumnStats.  # noqa: E501
        :type min: float
        """

        self._min = min

    @property
    def max(self):
        """Gets the max of this StorageNumericColumnStats.  # noqa: E501


        :return: The max of this StorageNumericColumnStats.  # noqa: E501
        :rtype: float
        """
        return self._max

    @max.setter
    def max(self, max):
        """Sets the max of this StorageNumericColumnStats.


        :param max: The max of this StorageNumericColumnStats.  # noqa: E501
        :type max: float
        """

        self._max = max

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StorageNumericColumnStats):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, StorageNumericColumnStats):
            return True

        return self.to_dict() != other.to_dict()
