# coding: utf-8

"""
    ai/h2o/mlops/storage/v1/artifact.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from _h2o_mlops_client.storage.configuration import Configuration


class StorageModelInfo(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'model_id': 'str',
        'model_name': 'str',
        'model_description': 'str',
        'project_id': 'str',
        'model_owner': 'str',
        'model_version_id': 'str',
        'model_version_number': 'str',
        'model_version_owner': 'str'
    }

    attribute_map = {
        'model_id': 'modelId',
        'model_name': 'modelName',
        'model_description': 'modelDescription',
        'project_id': 'projectId',
        'model_owner': 'modelOwner',
        'model_version_id': 'modelVersionId',
        'model_version_number': 'modelVersionNumber',
        'model_version_owner': 'modelVersionOwner'
    }

    def __init__(self, model_id=None, model_name=None, model_description=None, project_id=None, model_owner=None, model_version_id=None, model_version_number=None, model_version_owner=None, local_vars_configuration=None):  # noqa: E501
        """StorageModelInfo - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._model_id = None
        self._model_name = None
        self._model_description = None
        self._project_id = None
        self._model_owner = None
        self._model_version_id = None
        self._model_version_number = None
        self._model_version_owner = None
        self.discriminator = None

        if model_id is not None:
            self.model_id = model_id
        if model_name is not None:
            self.model_name = model_name
        if model_description is not None:
            self.model_description = model_description
        if project_id is not None:
            self.project_id = project_id
        if model_owner is not None:
            self.model_owner = model_owner
        if model_version_id is not None:
            self.model_version_id = model_version_id
        if model_version_number is not None:
            self.model_version_number = model_version_number
        if model_version_owner is not None:
            self.model_version_owner = model_version_owner

    @property
    def model_id(self):
        """Gets the model_id of this StorageModelInfo.  # noqa: E501


        :return: The model_id of this StorageModelInfo.  # noqa: E501
        :rtype: str
        """
        return self._model_id

    @model_id.setter
    def model_id(self, model_id):
        """Sets the model_id of this StorageModelInfo.


        :param model_id: The model_id of this StorageModelInfo.  # noqa: E501
        :type model_id: str
        """

        self._model_id = model_id

    @property
    def model_name(self):
        """Gets the model_name of this StorageModelInfo.  # noqa: E501


        :return: The model_name of this StorageModelInfo.  # noqa: E501
        :rtype: str
        """
        return self._model_name

    @model_name.setter
    def model_name(self, model_name):
        """Sets the model_name of this StorageModelInfo.


        :param model_name: The model_name of this StorageModelInfo.  # noqa: E501
        :type model_name: str
        """

        self._model_name = model_name

    @property
    def model_description(self):
        """Gets the model_description of this StorageModelInfo.  # noqa: E501


        :return: The model_description of this StorageModelInfo.  # noqa: E501
        :rtype: str
        """
        return self._model_description

    @model_description.setter
    def model_description(self, model_description):
        """Sets the model_description of this StorageModelInfo.


        :param model_description: The model_description of this StorageModelInfo.  # noqa: E501
        :type model_description: str
        """

        self._model_description = model_description

    @property
    def project_id(self):
        """Gets the project_id of this StorageModelInfo.  # noqa: E501


        :return: The project_id of this StorageModelInfo.  # noqa: E501
        :rtype: str
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id):
        """Sets the project_id of this StorageModelInfo.


        :param project_id: The project_id of this StorageModelInfo.  # noqa: E501
        :type project_id: str
        """

        self._project_id = project_id

    @property
    def model_owner(self):
        """Gets the model_owner of this StorageModelInfo.  # noqa: E501


        :return: The model_owner of this StorageModelInfo.  # noqa: E501
        :rtype: str
        """
        return self._model_owner

    @model_owner.setter
    def model_owner(self, model_owner):
        """Sets the model_owner of this StorageModelInfo.


        :param model_owner: The model_owner of this StorageModelInfo.  # noqa: E501
        :type model_owner: str
        """

        self._model_owner = model_owner

    @property
    def model_version_id(self):
        """Gets the model_version_id of this StorageModelInfo.  # noqa: E501


        :return: The model_version_id of this StorageModelInfo.  # noqa: E501
        :rtype: str
        """
        return self._model_version_id

    @model_version_id.setter
    def model_version_id(self, model_version_id):
        """Sets the model_version_id of this StorageModelInfo.


        :param model_version_id: The model_version_id of this StorageModelInfo.  # noqa: E501
        :type model_version_id: str
        """

        self._model_version_id = model_version_id

    @property
    def model_version_number(self):
        """Gets the model_version_number of this StorageModelInfo.  # noqa: E501


        :return: The model_version_number of this StorageModelInfo.  # noqa: E501
        :rtype: str
        """
        return self._model_version_number

    @model_version_number.setter
    def model_version_number(self, model_version_number):
        """Sets the model_version_number of this StorageModelInfo.


        :param model_version_number: The model_version_number of this StorageModelInfo.  # noqa: E501
        :type model_version_number: str
        """

        self._model_version_number = model_version_number

    @property
    def model_version_owner(self):
        """Gets the model_version_owner of this StorageModelInfo.  # noqa: E501


        :return: The model_version_owner of this StorageModelInfo.  # noqa: E501
        :rtype: str
        """
        return self._model_version_owner

    @model_version_owner.setter
    def model_version_owner(self, model_version_owner):
        """Sets the model_version_owner of this StorageModelInfo.


        :param model_version_owner: The model_version_owner of this StorageModelInfo.  # noqa: E501
        :type model_version_owner: str
        """

        self._model_version_owner = model_version_owner

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StorageModelInfo):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, StorageModelInfo):
            return True

        return self.to_dict() != other.to_dict()
