from craftgate.response.common.list_response import ListResponse
from craftgate.response.reporting_payment_transaction_refund_response import ReportingPaymentTransactionRefundResponse


class ReportingPaymentTransactionRefundListResponse(ListResponse[ReportingPaymentTransactionRefundResponse]):
    item_type = ReportingPaymentTransactionRefundResponse
