# Generated by Django 4.2.16 on 2025-08-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corptools", "0125_corporationaudit_last_change_industry_jobs_and_more"),
        ("taxtools", "0024_alter_corporatetaxcredits_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="corptaxperservicemoduleconfiguration",
            name="structure_type_filter",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"group__category_id": 65},
                to="corptools.eveitemtype",
            ),
        ),
    ]
