# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openobd_protocol/Configuration/Messages/KlineBus.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6openobd_protocol/Configuration/Messages/KlineBus.proto\x12\nopenOBD.v1\"|\n\x08KlineBus\x12\x0b\n\x03pin\x18\x01 \x01(\r\x12\x31\n\x0ekline_protocol\x18\x02 \x01(\x0e\x32\x19.openOBD.v1.KlineProtocol\x12\x30\n\x0ekline_bit_rate\x18\x03 \x01(\x0e\x32\x18.openOBD.v1.KlineBitRate*s\n\rKlineProtocol\x12\x1c\n\x18KLINE_PROTOCOL_UNDEFINED\x10\x00\x12!\n\x1cKLINE_PROTOCOL_ISO14230_SLOW\x10\xeb\x07\x12!\n\x1cKLINE_PROTOCOL_ISO14230_FAST\x10\xec\x07*y\n\x0cKlineBitRate\x12\x1c\n\x18KLINE_BIT_RATE_UNDEFINED\x10\x00\x12\x17\n\x13KLINE_BIT_RATE_9600\x10\x07\x12\x18\n\x14KLINE_BIT_RATE_10400\x10\x0b\x12\x18\n\x14KLINE_BIT_RATE_15625\x10\x12\x42/\n+com.jifeline.OpenOBD.Configuration.MessagesP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'openobd_protocol.Configuration.Messages.KlineBus_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n+com.jifeline.OpenOBD.Configuration.MessagesP\001'
  _globals['_KLINEPROTOCOL']._serialized_start=196
  _globals['_KLINEPROTOCOL']._serialized_end=311
  _globals['_KLINEBITRATE']._serialized_start=313
  _globals['_KLINEBITRATE']._serialized_end=434
  _globals['_KLINEBUS']._serialized_start=70
  _globals['_KLINEBUS']._serialized_end=194
# @@protoc_insertion_point(module_scope)
