# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatflow

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from flatflow.ops.graph_generated import Graph
from typing import Optional
np = import_numpy()

class InitRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = InitRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsInitRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # InitRequest
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # InitRequest
    def DataParallelRank(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # InitRequest
    def DataParallelWorldSize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # InitRequest
    def GlobalBatchSize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # InitRequest
    def MicroBatchSize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # InitRequest
    def Graph(self) -> Optional[Graph]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = Graph()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # InitRequest
    def Sizes(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 2))
        return 0

    # InitRequest
    def SizesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint16Flags, o)
        return 0

    # InitRequest
    def SizesLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # InitRequest
    def SizesIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

def InitRequestStart(builder: flatbuffers.Builder):
    builder.StartObject(6)

def InitRequestAddDataParallelRank(builder: flatbuffers.Builder, dataParallelRank: int):
    builder.PrependUint64Slot(0, dataParallelRank, 0)

def InitRequestAddDataParallelWorldSize(builder: flatbuffers.Builder, dataParallelWorldSize: int):
    builder.PrependUint64Slot(1, dataParallelWorldSize, 0)

def InitRequestAddGlobalBatchSize(builder: flatbuffers.Builder, globalBatchSize: int):
    builder.PrependUint64Slot(2, globalBatchSize, 0)

def InitRequestAddMicroBatchSize(builder: flatbuffers.Builder, microBatchSize: int):
    builder.PrependUint64Slot(3, microBatchSize, 0)

def InitRequestAddGraph(builder: flatbuffers.Builder, graph: int):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(graph), 0)

def InitRequestAddSizes(builder: flatbuffers.Builder, sizes: int):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(sizes), 0)

def InitRequestStartSizesVector(builder, numElems: int) -> int:
    return builder.StartVector(2, numElems, 2)

def InitRequestEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()



class ScatterRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ScatterRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsScatterRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ScatterRequest
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ScatterRequest
    def Epoch(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # ScatterRequest
    def Indices(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # ScatterRequest
    def IndicesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint64Flags, o)
        return 0

    # ScatterRequest
    def IndicesLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ScatterRequest
    def IndicesIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def ScatterRequestStart(builder: flatbuffers.Builder):
    builder.StartObject(2)

def ScatterRequestAddEpoch(builder: flatbuffers.Builder, epoch: int):
    builder.PrependUint64Slot(0, epoch, 0)

def ScatterRequestAddIndices(builder: flatbuffers.Builder, indices: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(indices), 0)

def ScatterRequestStartIndicesVector(builder, numElems: int) -> int:
    return builder.StartVector(8, numElems, 8)

def ScatterRequestEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()



class ScatterResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ScatterResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsScatterResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ScatterResponse
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ScatterResponse
    def Indices(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # ScatterResponse
    def IndicesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint64Flags, o)
        return 0

    # ScatterResponse
    def IndicesLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ScatterResponse
    def IndicesIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def ScatterResponseStart(builder: flatbuffers.Builder):
    builder.StartObject(1)

def ScatterResponseAddIndices(builder: flatbuffers.Builder, indices: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(indices), 0)

def ScatterResponseStartIndicesVector(builder, numElems: int) -> int:
    return builder.StartVector(8, numElems, 8)

def ScatterResponseEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()



