from enum import Enum


class ApmAdditionalAction(str, Enum):
    REDIRECT_TO_URL = "REDIRECT_TO_URL"
    OTP_REQUIRED = "OTP_REQUIRED"
    SHOW_HTML_CONTENT = "SHOW_HTML_CONTENT"
    WAIT_FOR_WEBHOOK = "WAIT_FOR_WEBHOOK"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    SHOW_QR_CODE = "SHOW_QR_CODE"
    NONE = "NONE"
