from enum import Enum


class LoyaltyType(str, Enum):
    REWARD_MONEY = "REWARD_MONEY"
    ADDITIONAL_INSTALLMENT = "ADDITIONAL_INSTALLMENT"
    POSTPONING_INSTALLMENT = "POSTPONING_INSTALLMENT"
    EXTRA_POINTS = "EXTRA_POINTS"
    GAINING_MINUTES = "GAINING_MINUTES"
    POSTPONING_STATEMENT = "POSTPONING_STATEMENT"
    POSTPONING_PAYMENT = "POSTPONING_PAYMENT"
