from enum import Enum


class PaymentMethod(str, Enum):
    CARD = "CARD"
    MASTERPASS = "MASTERPASS"
    PAPARA = "PAPARA"
    PAYONEER = "PAYONEER"
    SODEXO = "SODEXO"
    SODEXO_GIFT = "SODEXO_GIFT"
    EDENRED = "EDENRED"
    EDENRED_GIFT = "EDENRED_GIFT"
    ALIPAY = "ALIPAY"
    PAYPAL = "PAYPAL"
    KLARNA = "KLARNA"
    AFTERPAY = "AFTERPAY"
    INSTANT_TRANSFER = "INSTANT_TRANSFER"
    STRIPE = "STRIPE"
    MULTINET = "MULTINET"
    MULTINET_GIFT = "MULTINET_GIFT"
    MULTINET_NEO_GIFT = "MULTINET_NEO_GIFT"
    BIZUM = "BIZUM"
    PAYCELL_DCB = "PAYCELL_DCB"
