# Thrift Compact Protocol constants
THRIFT_VARINT_MASK = 0x7F
THRIFT_VARINT_CONTINUE = 0x80
THRIFT_FIELD_TYPE_MASK = 0x0F
THRIFT_SIZE_SHIFT = 4
THRIFT_SPECIAL_LIST_SIZE = 15
THRIFT_MAP_TYPE_SHIFT = 4

# Default values for thrift operations
DEFAULT_STRING_ENCODING = 'utf-8'
