"""
ⒸAngelaMos | 2025 | CertGames.com
Magic values as constants
"""

CODE_LENGTH: int = 8
CODE_PREFIX: str = "REF"
CODE_SEPARATOR: str = "_"

MIN_CODE_LENGTH: int = 6
MAX_CODE_LENGTH: int = 20

DEFAULT_PAYOUT_CURRENCY: str = "USD"
MIN_PAYOUT_AMOUNT: float = 10.00
MAX_PAYOUT_AMOUNT: float = 100000.00

MAX_CODE_GENERATIONS_PER_USER: int = 10
MAX_CODES_PER_USER_PER_PROGRAM: int = 5
CODE_GENERATION_RETRY_ATTEMPTS: int = 10

DEFAULT_CONVERSION_WINDOW_DAYS: int = 30
MAX_CONVERSION_WINDOW_DAYS: int = 365

MAX_PROGRAM_NAME_LENGTH: int = 255
MAX_PROGRAM_KEY_LENGTH: int = 100

MIN_REWARD_AMOUNT: float = 0.01
MAX_REWARD_AMOUNT: float = 100000.00

CURRENCY_CODE_LENGTH: int = 3

MIN_MAX_REWARDS_PER_USER: int = 1
MAX_MAX_REWARDS_PER_USER: int = 1000

MIN_CONVERSION_WINDOW_DAYS: int = 1

MAX_USER_ID_LENGTH: int = 100
MAX_TRANSACTION_ID_LENGTH: int = 255

MAX_RECIPIENT_DATA_SIZE_BYTES: int = 10240

MAX_ERROR_MESSAGE_LENGTH: int = 500

STRIPE_CONNECT_ACCOUNT_ID_PREFIX: str = "acct_"
STRIPE_TRANSFER_ID_PREFIX: str = "tr_"

MANUAL_PAYOUT_ID_PREFIX: str = "manual_"

DATABASE_CONNECTION_POOL_SIZE: int = 10
DATABASE_CONNECTION_MAX_OVERFLOW: int = 20
DATABASE_CONNECTION_TIMEOUT_SECONDS: int = 30

CACHE_TTL_SECONDS: int = 3600

WEBHOOK_TIMEOUT_SECONDS: int = 10

RATE_LIMIT_PER_MINUTE: int = 60
RATE_LIMIT_PER_HOUR: int = 1000

BATCH_SIZE_PAYOUT_PROCESSING: int = 100

ALLOW_SELF_REFERRAL: bool = False
REQUIRE_RECIPIENT_VALIDATION: bool = True

STRIPE_API_VERSION: str = "2024-11-20.acacia"
