# Generated by Django 3.1.8 on 2021-05-11 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_move_to_new_suggestions_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satelliteentry',
            name='norad_cat_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
