# coding: utf-8

# flake8: noqa
"""
    ai/h2o/mlops/monitoring/v2/aggregate.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from _h2o_mlops_client.monitoring.v2.models.protobuf_any import ProtobufAny
from _h2o_mlops_client.monitoring.v2.models.rpc_status import RpcStatus
from _h2o_mlops_client.monitoring.v2.models.v2_baseline_aggregation import V2BaselineAggregation
from _h2o_mlops_client.monitoring.v2.models.v2_categorical_aggregate import V2CategoricalAggregate
from _h2o_mlops_client.monitoring.v2.models.v2_generate_aggregator_config_response import V2GenerateAggregatorConfigResponse
from _h2o_mlops_client.monitoring.v2.models.v2_list_aggregates_response import V2ListAggregatesResponse
from _h2o_mlops_client.monitoring.v2.models.v2_list_baseline_aggregates_response import V2ListBaselineAggregatesResponse
from _h2o_mlops_client.monitoring.v2.models.v2_logical_type import V2LogicalType
from _h2o_mlops_client.monitoring.v2.models.v2_missing_values import V2MissingValues
from _h2o_mlops_client.monitoring.v2.models.v2_numerical_aggregate import V2NumericalAggregate
from _h2o_mlops_client.monitoring.v2.models.v2_scoring_aggregation import V2ScoringAggregation
