from _typeshed import Incomplete
from pycorelibs.message.message import MessageModel as MessageModel

class RedisMessageQueue:
    redis: Incomplete
    queue_key: Incomplete
    processing_key: Incomplete
    retry_key: Incomplete
    model_class: Incomplete
    def __init__(self, host: str = 'localhost', port: int = 6379, db: int = 0, queue_key: str = 'message_queue', model_class: type[MessageModel] = ...) -> None: ...
    def push(self, message: MessageModel): ...
    def pop(self) -> MessageModel: ...
    def confirm(self, msg_id: str): ...
    def retry_failed(self, delay: int = 10): ...
