depends = ('ITKPyBase', 'ITKTransform', 'ITKSpatialObjects', 'ITKRegistrationCommon', 'ITKOptimizers', 'ITKImageGradient', 'ITKImageFunction', )
templates = (  ('NormalizedCorrelationTwoImageToOneImageMetric', 'itk::NormalizedCorrelationTwoImageToOneImageMetric', 'itkNormalizedCorrelationTwoImageToOneImageMetricISS2ISS2', True, 'itk::Image< signed short,2 >, itk::Image< signed short,2 >'),
  ('NormalizedCorrelationTwoImageToOneImageMetric', 'itk::NormalizedCorrelationTwoImageToOneImageMetric', 'itkNormalizedCorrelationTwoImageToOneImageMetricISS3ISS3', True, 'itk::Image< signed short,3 >, itk::Image< signed short,3 >'),
  ('NormalizedCorrelationTwoImageToOneImageMetric', 'itk::NormalizedCorrelationTwoImageToOneImageMetric', 'itkNormalizedCorrelationTwoImageToOneImageMetricISS4ISS4', True, 'itk::Image< signed short,4 >, itk::Image< signed short,4 >'),
  ('NormalizedCorrelationTwoImageToOneImageMetric', 'itk::NormalizedCorrelationTwoImageToOneImageMetric', 'itkNormalizedCorrelationTwoImageToOneImageMetricIUC2IUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('NormalizedCorrelationTwoImageToOneImageMetric', 'itk::NormalizedCorrelationTwoImageToOneImageMetric', 'itkNormalizedCorrelationTwoImageToOneImageMetricIUC3IUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('NormalizedCorrelationTwoImageToOneImageMetric', 'itk::NormalizedCorrelationTwoImageToOneImageMetric', 'itkNormalizedCorrelationTwoImageToOneImageMetricIUC4IUC4', True, 'itk::Image< unsigned char,4 >, itk::Image< unsigned char,4 >'),
  ('NormalizedCorrelationTwoImageToOneImageMetric', 'itk::NormalizedCorrelationTwoImageToOneImageMetric', 'itkNormalizedCorrelationTwoImageToOneImageMetricIUS2IUS2', True, 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('NormalizedCorrelationTwoImageToOneImageMetric', 'itk::NormalizedCorrelationTwoImageToOneImageMetric', 'itkNormalizedCorrelationTwoImageToOneImageMetricIUS3IUS3', True, 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('NormalizedCorrelationTwoImageToOneImageMetric', 'itk::NormalizedCorrelationTwoImageToOneImageMetric', 'itkNormalizedCorrelationTwoImageToOneImageMetricIUS4IUS4', True, 'itk::Image< unsigned short,4 >, itk::Image< unsigned short,4 >'),
  ('NormalizedCorrelationTwoImageToOneImageMetric', 'itk::NormalizedCorrelationTwoImageToOneImageMetric', 'itkNormalizedCorrelationTwoImageToOneImageMetricIF2IF2', True, 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('NormalizedCorrelationTwoImageToOneImageMetric', 'itk::NormalizedCorrelationTwoImageToOneImageMetric', 'itkNormalizedCorrelationTwoImageToOneImageMetricIF3IF3', True, 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('NormalizedCorrelationTwoImageToOneImageMetric', 'itk::NormalizedCorrelationTwoImageToOneImageMetric', 'itkNormalizedCorrelationTwoImageToOneImageMetricIF4IF4', True, 'itk::Image< float,4 >, itk::Image< float,4 >'),
  ('NormalizedCorrelationTwoImageToOneImageMetric', 'itk::NormalizedCorrelationTwoImageToOneImageMetric', 'itkNormalizedCorrelationTwoImageToOneImageMetricID2ID2', True, 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('NormalizedCorrelationTwoImageToOneImageMetric', 'itk::NormalizedCorrelationTwoImageToOneImageMetric', 'itkNormalizedCorrelationTwoImageToOneImageMetricID3ID3', True, 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('NormalizedCorrelationTwoImageToOneImageMetric', 'itk::NormalizedCorrelationTwoImageToOneImageMetric', 'itkNormalizedCorrelationTwoImageToOneImageMetricID4ID4', True, 'itk::Image< double,4 >, itk::Image< double,4 >'),
  ('SiddonJacobsRayCastInterpolateImageFunction', 'itk::SiddonJacobsRayCastInterpolateImageFunction', 'itkSiddonJacobsRayCastInterpolateImageFunctionISS3D', True, 'itk::Image< signed short,3 >,double'),
  ('SiddonJacobsRayCastInterpolateImageFunction', 'itk::SiddonJacobsRayCastInterpolateImageFunction', 'itkSiddonJacobsRayCastInterpolateImageFunctionIUC3D', True, 'itk::Image< unsigned char,3 >,double'),
  ('SiddonJacobsRayCastInterpolateImageFunction', 'itk::SiddonJacobsRayCastInterpolateImageFunction', 'itkSiddonJacobsRayCastInterpolateImageFunctionIUS3D', True, 'itk::Image< unsigned short,3 >,double'),
  ('SiddonJacobsRayCastInterpolateImageFunction', 'itk::SiddonJacobsRayCastInterpolateImageFunction', 'itkSiddonJacobsRayCastInterpolateImageFunctionIF3D', True, 'itk::Image< float,3 >,double'),
  ('SiddonJacobsRayCastInterpolateImageFunction', 'itk::SiddonJacobsRayCastInterpolateImageFunction', 'itkSiddonJacobsRayCastInterpolateImageFunctionID3D', True, 'itk::Image< double,3 >,double'),
  ('TwoImageToOneImageMetric', 'itk::TwoImageToOneImageMetric', 'itkTwoImageToOneImageMetricISS2ISS2', True, 'itk::Image< signed short,2 >, itk::Image< signed short,2 >'),
  ('TwoImageToOneImageMetric', 'itk::TwoImageToOneImageMetric', 'itkTwoImageToOneImageMetricISS3ISS3', True, 'itk::Image< signed short,3 >, itk::Image< signed short,3 >'),
  ('TwoImageToOneImageMetric', 'itk::TwoImageToOneImageMetric', 'itkTwoImageToOneImageMetricISS4ISS4', True, 'itk::Image< signed short,4 >, itk::Image< signed short,4 >'),
  ('TwoImageToOneImageMetric', 'itk::TwoImageToOneImageMetric', 'itkTwoImageToOneImageMetricIUC2IUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('TwoImageToOneImageMetric', 'itk::TwoImageToOneImageMetric', 'itkTwoImageToOneImageMetricIUC3IUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('TwoImageToOneImageMetric', 'itk::TwoImageToOneImageMetric', 'itkTwoImageToOneImageMetricIUC4IUC4', True, 'itk::Image< unsigned char,4 >, itk::Image< unsigned char,4 >'),
  ('TwoImageToOneImageMetric', 'itk::TwoImageToOneImageMetric', 'itkTwoImageToOneImageMetricIUS2IUS2', True, 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('TwoImageToOneImageMetric', 'itk::TwoImageToOneImageMetric', 'itkTwoImageToOneImageMetricIUS3IUS3', True, 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('TwoImageToOneImageMetric', 'itk::TwoImageToOneImageMetric', 'itkTwoImageToOneImageMetricIUS4IUS4', True, 'itk::Image< unsigned short,4 >, itk::Image< unsigned short,4 >'),
  ('TwoImageToOneImageMetric', 'itk::TwoImageToOneImageMetric', 'itkTwoImageToOneImageMetricIF2IF2', True, 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('TwoImageToOneImageMetric', 'itk::TwoImageToOneImageMetric', 'itkTwoImageToOneImageMetricIF3IF3', True, 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('TwoImageToOneImageMetric', 'itk::TwoImageToOneImageMetric', 'itkTwoImageToOneImageMetricIF4IF4', True, 'itk::Image< float,4 >, itk::Image< float,4 >'),
  ('TwoImageToOneImageMetric', 'itk::TwoImageToOneImageMetric', 'itkTwoImageToOneImageMetricID2ID2', True, 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('TwoImageToOneImageMetric', 'itk::TwoImageToOneImageMetric', 'itkTwoImageToOneImageMetricID3ID3', True, 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('TwoImageToOneImageMetric', 'itk::TwoImageToOneImageMetric', 'itkTwoImageToOneImageMetricID4ID4', True, 'itk::Image< double,4 >, itk::Image< double,4 >'),
  ('TwoProjectionImageRegistrationMethod', 'itk::TwoProjectionImageRegistrationMethod', 'itkTwoProjectionImageRegistrationMethodISS2ISS2', True, 'itk::Image< signed short,2 >, itk::Image< signed short,2 >'),
  ('TwoProjectionImageRegistrationMethod', 'itk::TwoProjectionImageRegistrationMethod', 'itkTwoProjectionImageRegistrationMethodISS3ISS3', True, 'itk::Image< signed short,3 >, itk::Image< signed short,3 >'),
  ('TwoProjectionImageRegistrationMethod', 'itk::TwoProjectionImageRegistrationMethod', 'itkTwoProjectionImageRegistrationMethodISS4ISS4', True, 'itk::Image< signed short,4 >, itk::Image< signed short,4 >'),
  ('TwoProjectionImageRegistrationMethod', 'itk::TwoProjectionImageRegistrationMethod', 'itkTwoProjectionImageRegistrationMethodIUC2IUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('TwoProjectionImageRegistrationMethod', 'itk::TwoProjectionImageRegistrationMethod', 'itkTwoProjectionImageRegistrationMethodIUC3IUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('TwoProjectionImageRegistrationMethod', 'itk::TwoProjectionImageRegistrationMethod', 'itkTwoProjectionImageRegistrationMethodIUC4IUC4', True, 'itk::Image< unsigned char,4 >, itk::Image< unsigned char,4 >'),
  ('TwoProjectionImageRegistrationMethod', 'itk::TwoProjectionImageRegistrationMethod', 'itkTwoProjectionImageRegistrationMethodIUS2IUS2', True, 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('TwoProjectionImageRegistrationMethod', 'itk::TwoProjectionImageRegistrationMethod', 'itkTwoProjectionImageRegistrationMethodIUS3IUS3', True, 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('TwoProjectionImageRegistrationMethod', 'itk::TwoProjectionImageRegistrationMethod', 'itkTwoProjectionImageRegistrationMethodIUS4IUS4', True, 'itk::Image< unsigned short,4 >, itk::Image< unsigned short,4 >'),
  ('TwoProjectionImageRegistrationMethod', 'itk::TwoProjectionImageRegistrationMethod', 'itkTwoProjectionImageRegistrationMethodIF2IF2', True, 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('TwoProjectionImageRegistrationMethod', 'itk::TwoProjectionImageRegistrationMethod', 'itkTwoProjectionImageRegistrationMethodIF3IF3', True, 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('TwoProjectionImageRegistrationMethod', 'itk::TwoProjectionImageRegistrationMethod', 'itkTwoProjectionImageRegistrationMethodIF4IF4', True, 'itk::Image< float,4 >, itk::Image< float,4 >'),
  ('TwoProjectionImageRegistrationMethod', 'itk::TwoProjectionImageRegistrationMethod', 'itkTwoProjectionImageRegistrationMethodID2ID2', True, 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('TwoProjectionImageRegistrationMethod', 'itk::TwoProjectionImageRegistrationMethod', 'itkTwoProjectionImageRegistrationMethodID3ID3', True, 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('TwoProjectionImageRegistrationMethod', 'itk::TwoProjectionImageRegistrationMethod', 'itkTwoProjectionImageRegistrationMethodID4ID4', True, 'itk::Image< double,4 >, itk::Image< double,4 >'),
)
factories = ()
