from enum import Enum


class PaymentType(str, Enum):
    CARD_PAYMENT = "CARD_PAYMENT"
    WALLET_PAYMENT = "WALLET_PAYMENT"
    CARD_AND_WALLET_PAYMENT = "CARD_AND_WALLET_PAYMENT"
    DEPOSIT_PAYMENT = "DEPOSIT_PAYMENT"
    HEPSIPAY_DEPOSIT_PAYMENT = "HEPSIPAY_DEPOSIT_PAYMENT"
    APM = "APM"
