from enum import Enum


class WebhookEventType(str, Enum):
    API_AUTH = "API_AUTH"
    API_VERIFY_AND_AUTH = "API_VERIFY_AND_AUTH"
    CHECKOUTFORM_AUTH = "CHECKOUTFORM_AUTH"
    THREEDS_VERIFY = "THREEDS_VERIFY"
    REFUND = "REFUND"
    REFUND_TX = "REFUND_TX"
    PAYOUT_COMPLETED = "PAYOUT_COMPLETED"
    AUTOPILOT = "AUTOPILOT"
    WALLET_CREATED = "WALLET_CREATED"
    WALLET_TX_CREATED = "WALLET_TX_CREATED"
    BNPL_NOTIFICATION = "BNPL_NOTIFICATION"
    BANK_ACCOUNT_TRACKING_RECORD = "BANK_ACCOUNT_TRACKING_RECORD"
    BKM_EXPRESS_PAYMENT_NOTIFICATION = "BKM_EXPRESS_PAYMENT_NOTIFICATION"
