# This file was auto-generated by Fern from our API Definition.

import typing

from .create_assistant_dto_voicemail_detection_zero import CreateAssistantDtoVoicemailDetectionZero
from .google_voicemail_detection_plan import GoogleVoicemailDetectionPlan
from .open_ai_voicemail_detection_plan import OpenAiVoicemailDetectionPlan
from .twilio_voicemail_detection_plan import TwilioVoicemailDetectionPlan
from .vapi_voicemail_detection_plan import VapiVoicemailDetectionPlan

CreateAssistantDtoVoicemailDetection = typing.Union[
    CreateAssistantDtoVoicemailDetectionZero,
    GoogleVoicemailDetectionPlan,
    OpenAiVoicemailDetectionPlan,
    TwilioVoicemailDetectionPlan,
    VapiVoicemailDetectionPlan,
]
