# This file was auto-generated by Fern from our API Definition.

import typing

JsonSchemaFormat = typing.Union[
    typing.Literal["date-time", "time", "date", "duration", "email", "hostname", "ipv4", "ipv6", "uuid"], typing.Any
]
