# This file was auto-generated by Fern from our API Definition.

import typing

from .call_hook_assistant_speech_interrupted import CallHookAssistantSpeechInterrupted
from .call_hook_call_ending import CallHookCallEnding
from .call_hook_customer_speech_interrupted import CallHookCustomerSpeechInterrupted
from .call_hook_customer_speech_timeout import CallHookCustomerSpeechTimeout
from .call_hook_model_response_timeout import CallHookModelResponseTimeout

WorkflowHooksItem = typing.Union[
    CallHookCallEnding,
    CallHookAssistantSpeechInterrupted,
    CallHookCustomerSpeechInterrupted,
    CallHookCustomerSpeechTimeout,
    CallHookModelResponseTimeout,
]
